// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.4.0
// source: AvatarSatiationData.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AvatarSatiationData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AvatarGuid        uint64  `protobuf:"varint,1,opt,name=avatar_guid,json=avatarGuid,proto3" json:"avatar_guid,omitempty"`
	FinishTime        float32 `protobuf:"fixed32,2,opt,name=finish_time,json=finishTime,proto3" json:"finish_time,omitempty"`
	PenaltyFinishTime float32 `protobuf:"fixed32,3,opt,name=penalty_finish_time,json=penaltyFinishTime,proto3" json:"penalty_finish_time,omitempty"`
}

func (x *AvatarSatiationData) Reset() {
	*x = AvatarSatiationData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_AvatarSatiationData_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AvatarSatiationData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvatarSatiationData) ProtoMessage() {}

func (x *AvatarSatiationData) ProtoReflect() protoreflect.Message {
	mi := &file_AvatarSatiationData_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvatarSatiationData.ProtoReflect.Descriptor instead.
func (*AvatarSatiationData) Descriptor() ([]byte, []int) {
	return file_AvatarSatiationData_proto_rawDescGZIP(), []int{0}
}

func (x *AvatarSatiationData) GetAvatarGuid() uint64 {
	if x != nil {
		return x.AvatarGuid
	}
	return 0
}

func (x *AvatarSatiationData) GetFinishTime() float32 {
	if x != nil {
		return x.FinishTime
	}
	return 0
}

func (x *AvatarSatiationData) GetPenaltyFinishTime() float32 {
	if x != nil {
		return x.PenaltyFinishTime
	}
	return 0
}

var File_AvatarSatiationData_proto protoreflect.FileDescriptor

var file_AvatarSatiationData_proto_rawDesc = []byte{
	0x0a, 0x19, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x53, 0x61, 0x74, 0x69, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x87, 0x01, 0x0a, 0x13, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x53, 0x61, 0x74,
	0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x76,
	0x61, 0x74, 0x61, 0x72, 0x5f, 0x67, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x0a, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x47, 0x75, 0x69, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x66,
	0x69, 0x6e, 0x69, 0x73, 0x68, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x0a, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x2e, 0x0a, 0x13,
	0x70, 0x65, 0x6e, 0x61, 0x6c, 0x74, 0x79, 0x5f, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x5f, 0x74,
	0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x11, 0x70, 0x65, 0x6e, 0x61, 0x6c,
	0x74, 0x79, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x54, 0x69, 0x6d, 0x65, 0x42, 0x0a, 0x5a, 0x08,
	0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_AvatarSatiationData_proto_rawDescOnce sync.Once
	file_AvatarSatiationData_proto_rawDescData = file_AvatarSatiationData_proto_rawDesc
)

func file_AvatarSatiationData_proto_rawDescGZIP() []byte {
	file_AvatarSatiationData_proto_rawDescOnce.Do(func() {
		file_AvatarSatiationData_proto_rawDescData = protoimpl.X.CompressGZIP(file_AvatarSatiationData_proto_rawDescData)
	})
	return file_AvatarSatiationData_proto_rawDescData
}

var file_AvatarSatiationData_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_AvatarSatiationData_proto_goTypes = []interface{}{
	(*AvatarSatiationData)(nil), // 0: proto.AvatarSatiationData
}
var file_AvatarSatiationData_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_AvatarSatiationData_proto_init() }
func file_AvatarSatiationData_proto_init() {
	if File_AvatarSatiationData_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_AvatarSatiationData_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AvatarSatiationData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_AvatarSatiationData_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_AvatarSatiationData_proto_goTypes,
		DependencyIndexes: file_AvatarSatiationData_proto_depIdxs,
		MessageInfos:      file_AvatarSatiationData_proto_msgTypes,
	}.Build()
	File_AvatarSatiationData_proto = out.File
	file_AvatarSatiationData_proto_rawDesc = nil
	file_AvatarSatiationData_proto_goTypes = nil
	file_AvatarSatiationData_proto_depIdxs = nil
}
