// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.4.0
// source: BlossomScheduleState.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BlossomScheduleState int32

const (
	BlossomScheduleState_BLOSSOM_SCHEDULE_NONE        BlossomScheduleState = 0
	BlossomScheduleState_BLOSSOM_SCHEDULE_INIT        BlossomScheduleState = 1
	BlossomScheduleState_BLOSSOM_SCHEDULE_IN_PROGRESS BlossomScheduleState = 2
	BlossomScheduleState_BLOSSOM_SCHEDULE_REWARD      BlossomScheduleState = 3
)

// Enum value maps for BlossomScheduleState.
var (
	BlossomScheduleState_name = map[int32]string{
		0: "BLOSSOM_SCHEDULE_NONE",
		1: "BLOSSOM_SCHEDULE_INIT",
		2: "BLOSSOM_SCHEDULE_IN_PROGRESS",
		3: "BLOSSOM_SCHEDULE_REWARD",
	}
	BlossomScheduleState_value = map[string]int32{
		"BLOSSOM_SCHEDULE_NONE":        0,
		"BLOSSOM_SCHEDULE_INIT":        1,
		"BLOSSOM_SCHEDULE_IN_PROGRESS": 2,
		"BLOSSOM_SCHEDULE_REWARD":      3,
	}
)

func (x BlossomScheduleState) Enum() *BlossomScheduleState {
	p := new(BlossomScheduleState)
	*p = x
	return p
}

func (x BlossomScheduleState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BlossomScheduleState) Descriptor() protoreflect.EnumDescriptor {
	return file_BlossomScheduleState_proto_enumTypes[0].Descriptor()
}

func (BlossomScheduleState) Type() protoreflect.EnumType {
	return &file_BlossomScheduleState_proto_enumTypes[0]
}

func (x BlossomScheduleState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BlossomScheduleState.Descriptor instead.
func (BlossomScheduleState) EnumDescriptor() ([]byte, []int) {
	return file_BlossomScheduleState_proto_rawDescGZIP(), []int{0}
}

var File_BlossomScheduleState_proto protoreflect.FileDescriptor

var file_BlossomScheduleState_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x42, 0x6c, 0x6f, 0x73, 0x73, 0x6f, 0x6d, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c,
	0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2a, 0x8b, 0x01, 0x0a, 0x14, 0x42, 0x6c, 0x6f, 0x73, 0x73, 0x6f, 0x6d, 0x53,
	0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x19, 0x0a, 0x15,
	0x42, 0x4c, 0x4f, 0x53, 0x53, 0x4f, 0x4d, 0x5f, 0x53, 0x43, 0x48, 0x45, 0x44, 0x55, 0x4c, 0x45,
	0x5f, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x19, 0x0a, 0x15, 0x42, 0x4c, 0x4f, 0x53, 0x53,
	0x4f, 0x4d, 0x5f, 0x53, 0x43, 0x48, 0x45, 0x44, 0x55, 0x4c, 0x45, 0x5f, 0x49, 0x4e, 0x49, 0x54,
	0x10, 0x01, 0x12, 0x20, 0x0a, 0x1c, 0x42, 0x4c, 0x4f, 0x53, 0x53, 0x4f, 0x4d, 0x5f, 0x53, 0x43,
	0x48, 0x45, 0x44, 0x55, 0x4c, 0x45, 0x5f, 0x49, 0x4e, 0x5f, 0x50, 0x52, 0x4f, 0x47, 0x52, 0x45,
	0x53, 0x53, 0x10, 0x02, 0x12, 0x1b, 0x0a, 0x17, 0x42, 0x4c, 0x4f, 0x53, 0x53, 0x4f, 0x4d, 0x5f,
	0x53, 0x43, 0x48, 0x45, 0x44, 0x55, 0x4c, 0x45, 0x5f, 0x52, 0x45, 0x57, 0x41, 0x52, 0x44, 0x10,
	0x03, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_BlossomScheduleState_proto_rawDescOnce sync.Once
	file_BlossomScheduleState_proto_rawDescData = file_BlossomScheduleState_proto_rawDesc
)

func file_BlossomScheduleState_proto_rawDescGZIP() []byte {
	file_BlossomScheduleState_proto_rawDescOnce.Do(func() {
		file_BlossomScheduleState_proto_rawDescData = protoimpl.X.CompressGZIP(file_BlossomScheduleState_proto_rawDescData)
	})
	return file_BlossomScheduleState_proto_rawDescData
}

var file_BlossomScheduleState_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_BlossomScheduleState_proto_goTypes = []interface{}{
	(BlossomScheduleState)(0), // 0: proto.BlossomScheduleState
}
var file_BlossomScheduleState_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_BlossomScheduleState_proto_init() }
func file_BlossomScheduleState_proto_init() {
	if File_BlossomScheduleState_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_BlossomScheduleState_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_BlossomScheduleState_proto_goTypes,
		DependencyIndexes: file_BlossomScheduleState_proto_depIdxs,
		EnumInfos:         file_BlossomScheduleState_proto_enumTypes,
	}.Build()
	File_BlossomScheduleState_proto = out.File
	file_BlossomScheduleState_proto_rawDesc = nil
	file_BlossomScheduleState_proto_goTypes = nil
	file_BlossomScheduleState_proto_depIdxs = nil
}
