// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.4.0
// source: ClientReconnectNotify.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientReconnectNotify_CmdId int32

const (
	ClientReconnectNotify_NONE             ClientReconnectNotify_CmdId = 0
	ClientReconnectNotify_CMD_ID           ClientReconnectNotify_CmdId = 12
	ClientReconnectNotify_ENET_CHANNEL_ID  ClientReconnectNotify_CmdId = 0
	ClientReconnectNotify_ENET_IS_RELIABLE ClientReconnectNotify_CmdId = 1
)

// Enum value maps for ClientReconnectNotify_CmdId.
var (
	ClientReconnectNotify_CmdId_name = map[int32]string{
		0:  "NONE",
		12: "CMD_ID",
		// Duplicate value: 0: "ENET_CHANNEL_ID",
		1: "ENET_IS_RELIABLE",
	}
	ClientReconnectNotify_CmdId_value = map[string]int32{
		"NONE":             0,
		"CMD_ID":           12,
		"ENET_CHANNEL_ID":  0,
		"ENET_IS_RELIABLE": 1,
	}
)

func (x ClientReconnectNotify_CmdId) Enum() *ClientReconnectNotify_CmdId {
	p := new(ClientReconnectNotify_CmdId)
	*p = x
	return p
}

func (x ClientReconnectNotify_CmdId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClientReconnectNotify_CmdId) Descriptor() protoreflect.EnumDescriptor {
	return file_ClientReconnectNotify_proto_enumTypes[0].Descriptor()
}

func (ClientReconnectNotify_CmdId) Type() protoreflect.EnumType {
	return &file_ClientReconnectNotify_proto_enumTypes[0]
}

func (x ClientReconnectNotify_CmdId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClientReconnectNotify_CmdId.Descriptor instead.
func (ClientReconnectNotify_CmdId) EnumDescriptor() ([]byte, []int) {
	return file_ClientReconnectNotify_proto_rawDescGZIP(), []int{0, 0}
}

type ClientReconnectNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reason ClientReconnectReason `protobuf:"varint,1,opt,name=reason,proto3,enum=proto.ClientReconnectReason" json:"reason,omitempty"`
}

func (x *ClientReconnectNotify) Reset() {
	*x = ClientReconnectNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ClientReconnectNotify_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientReconnectNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientReconnectNotify) ProtoMessage() {}

func (x *ClientReconnectNotify) ProtoReflect() protoreflect.Message {
	mi := &file_ClientReconnectNotify_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientReconnectNotify.ProtoReflect.Descriptor instead.
func (*ClientReconnectNotify) Descriptor() ([]byte, []int) {
	return file_ClientReconnectNotify_proto_rawDescGZIP(), []int{0}
}

func (x *ClientReconnectNotify) GetReason() ClientReconnectReason {
	if x != nil {
		return x.Reason
	}
	return ClientReconnectReason_CLIENT_RECONNNECT_NONE
}

var File_ClientReconnectNotify_proto protoreflect.FileDescriptor

var file_ClientReconnectNotify_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63,
	0x74, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x63, 0x6f,
	0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x9b, 0x01, 0x0a, 0x15, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x63, 0x6f,
	0x6e, 0x6e, 0x65, 0x63, 0x74, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x34, 0x0a, 0x06, 0x72,
	0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x6e, 0x6e,
	0x65, 0x63, 0x74, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f,
	0x6e, 0x22, 0x4c, 0x0a, 0x05, 0x43, 0x6d, 0x64, 0x49, 0x64, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x4f,
	0x4e, 0x45, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x43, 0x4d, 0x44, 0x5f, 0x49, 0x44, 0x10, 0x0c,
	0x12, 0x13, 0x0a, 0x0f, 0x45, 0x4e, 0x45, 0x54, 0x5f, 0x43, 0x48, 0x41, 0x4e, 0x4e, 0x45, 0x4c,
	0x5f, 0x49, 0x44, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x45, 0x4e, 0x45, 0x54, 0x5f, 0x49, 0x53,
	0x5f, 0x52, 0x45, 0x4c, 0x49, 0x41, 0x42, 0x4c, 0x45, 0x10, 0x01, 0x1a, 0x02, 0x10, 0x01, 0x42,
	0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_ClientReconnectNotify_proto_rawDescOnce sync.Once
	file_ClientReconnectNotify_proto_rawDescData = file_ClientReconnectNotify_proto_rawDesc
)

func file_ClientReconnectNotify_proto_rawDescGZIP() []byte {
	file_ClientReconnectNotify_proto_rawDescOnce.Do(func() {
		file_ClientReconnectNotify_proto_rawDescData = protoimpl.X.CompressGZIP(file_ClientReconnectNotify_proto_rawDescData)
	})
	return file_ClientReconnectNotify_proto_rawDescData
}

var file_ClientReconnectNotify_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ClientReconnectNotify_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ClientReconnectNotify_proto_goTypes = []interface{}{
	(ClientReconnectNotify_CmdId)(0), // 0: proto.ClientReconnectNotify.CmdId
	(*ClientReconnectNotify)(nil),    // 1: proto.ClientReconnectNotify
	(ClientReconnectReason)(0),       // 2: proto.ClientReconnectReason
}
var file_ClientReconnectNotify_proto_depIdxs = []int32{
	2, // 0: proto.ClientReconnectNotify.reason:type_name -> proto.ClientReconnectReason
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ClientReconnectNotify_proto_init() }
func file_ClientReconnectNotify_proto_init() {
	if File_ClientReconnectNotify_proto != nil {
		return
	}
	file_ClientReconnectReason_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_ClientReconnectNotify_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientReconnectNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ClientReconnectNotify_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ClientReconnectNotify_proto_goTypes,
		DependencyIndexes: file_ClientReconnectNotify_proto_depIdxs,
		EnumInfos:         file_ClientReconnectNotify_proto_enumTypes,
		MessageInfos:      file_ClientReconnectNotify_proto_msgTypes,
	}.Build()
	File_ClientReconnectNotify_proto = out.File
	file_ClientReconnectNotify_proto_rawDesc = nil
	file_ClientReconnectNotify_proto_goTypes = nil
	file_ClientReconnectNotify_proto_depIdxs = nil
}
