// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.4.0
// source: CreateMassiveEntityRsp.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateMassiveEntityRsp_CmdId int32

const (
	CreateMassiveEntityRsp_NONE             CreateMassiveEntityRsp_CmdId = 0
	CreateMassiveEntityRsp_CMD_ID           CreateMassiveEntityRsp_CmdId = 344
	CreateMassiveEntityRsp_ENET_CHANNEL_ID  CreateMassiveEntityRsp_CmdId = 0
	CreateMassiveEntityRsp_ENET_IS_RELIABLE CreateMassiveEntityRsp_CmdId = 1
)

// Enum value maps for CreateMassiveEntityRsp_CmdId.
var (
	CreateMassiveEntityRsp_CmdId_name = map[int32]string{
		0:   "NONE",
		344: "CMD_ID",
		// Duplicate value: 0: "ENET_CHANNEL_ID",
		1: "ENET_IS_RELIABLE",
	}
	CreateMassiveEntityRsp_CmdId_value = map[string]int32{
		"NONE":             0,
		"CMD_ID":           344,
		"ENET_CHANNEL_ID":  0,
		"ENET_IS_RELIABLE": 1,
	}
)

func (x CreateMassiveEntityRsp_CmdId) Enum() *CreateMassiveEntityRsp_CmdId {
	p := new(CreateMassiveEntityRsp_CmdId)
	*p = x
	return p
}

func (x CreateMassiveEntityRsp_CmdId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CreateMassiveEntityRsp_CmdId) Descriptor() protoreflect.EnumDescriptor {
	return file_CreateMassiveEntityRsp_proto_enumTypes[0].Descriptor()
}

func (CreateMassiveEntityRsp_CmdId) Type() protoreflect.EnumType {
	return &file_CreateMassiveEntityRsp_proto_enumTypes[0]
}

func (x CreateMassiveEntityRsp_CmdId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CreateMassiveEntityRsp_CmdId.Descriptor instead.
func (CreateMassiveEntityRsp_CmdId) EnumDescriptor() ([]byte, []int) {
	return file_CreateMassiveEntityRsp_proto_rawDescGZIP(), []int{0, 0}
}

type CreateMassiveEntityRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Retcode int32 `protobuf:"varint,1,opt,name=retcode,proto3" json:"retcode,omitempty"`
}

func (x *CreateMassiveEntityRsp) Reset() {
	*x = CreateMassiveEntityRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CreateMassiveEntityRsp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateMassiveEntityRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMassiveEntityRsp) ProtoMessage() {}

func (x *CreateMassiveEntityRsp) ProtoReflect() protoreflect.Message {
	mi := &file_CreateMassiveEntityRsp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMassiveEntityRsp.ProtoReflect.Descriptor instead.
func (*CreateMassiveEntityRsp) Descriptor() ([]byte, []int) {
	return file_CreateMassiveEntityRsp_proto_rawDescGZIP(), []int{0}
}

func (x *CreateMassiveEntityRsp) GetRetcode() int32 {
	if x != nil {
		return x.Retcode
	}
	return 0
}

var File_CreateMassiveEntityRsp_proto protoreflect.FileDescriptor

var file_CreateMassiveEntityRsp_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x61, 0x73, 0x73, 0x69, 0x76, 0x65, 0x45,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x73, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x81, 0x01, 0x0a, 0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x4d, 0x61, 0x73, 0x73, 0x69, 0x76, 0x65, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x73, 0x70,
	0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x74, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x07, 0x72, 0x65, 0x74, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x4d, 0x0a, 0x05, 0x43, 0x6d,
	0x64, 0x49, 0x64, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x0b, 0x0a,
	0x06, 0x43, 0x4d, 0x44, 0x5f, 0x49, 0x44, 0x10, 0xd8, 0x02, 0x12, 0x13, 0x0a, 0x0f, 0x45, 0x4e,
	0x45, 0x54, 0x5f, 0x43, 0x48, 0x41, 0x4e, 0x4e, 0x45, 0x4c, 0x5f, 0x49, 0x44, 0x10, 0x00, 0x12,
	0x14, 0x0a, 0x10, 0x45, 0x4e, 0x45, 0x54, 0x5f, 0x49, 0x53, 0x5f, 0x52, 0x45, 0x4c, 0x49, 0x41,
	0x42, 0x4c, 0x45, 0x10, 0x01, 0x1a, 0x02, 0x10, 0x01, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x3b,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_CreateMassiveEntityRsp_proto_rawDescOnce sync.Once
	file_CreateMassiveEntityRsp_proto_rawDescData = file_CreateMassiveEntityRsp_proto_rawDesc
)

func file_CreateMassiveEntityRsp_proto_rawDescGZIP() []byte {
	file_CreateMassiveEntityRsp_proto_rawDescOnce.Do(func() {
		file_CreateMassiveEntityRsp_proto_rawDescData = protoimpl.X.CompressGZIP(file_CreateMassiveEntityRsp_proto_rawDescData)
	})
	return file_CreateMassiveEntityRsp_proto_rawDescData
}

var file_CreateMassiveEntityRsp_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_CreateMassiveEntityRsp_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_CreateMassiveEntityRsp_proto_goTypes = []interface{}{
	(CreateMassiveEntityRsp_CmdId)(0), // 0: proto.CreateMassiveEntityRsp.CmdId
	(*CreateMassiveEntityRsp)(nil),    // 1: proto.CreateMassiveEntityRsp
}
var file_CreateMassiveEntityRsp_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_CreateMassiveEntityRsp_proto_init() }
func file_CreateMassiveEntityRsp_proto_init() {
	if File_CreateMassiveEntityRsp_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_CreateMassiveEntityRsp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateMassiveEntityRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_CreateMassiveEntityRsp_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_CreateMassiveEntityRsp_proto_goTypes,
		DependencyIndexes: file_CreateMassiveEntityRsp_proto_depIdxs,
		EnumInfos:         file_CreateMassiveEntityRsp_proto_enumTypes,
		MessageInfos:      file_CreateMassiveEntityRsp_proto_msgTypes,
	}.Build()
	File_CreateMassiveEntityRsp_proto = out.File
	file_CreateMassiveEntityRsp_proto_rawDesc = nil
	file_CreateMassiveEntityRsp_proto_goTypes = nil
	file_CreateMassiveEntityRsp_proto_depIdxs = nil
}
