// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.4.0
// source: DungeonCandidateTeamInfoNotify.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DungeonCandidateTeamInfoNotify_CmdId int32

const (
	DungeonCandidateTeamInfoNotify_NONE             DungeonCandidateTeamInfoNotify_CmdId = 0
	DungeonCandidateTeamInfoNotify_CMD_ID           DungeonCandidateTeamInfoNotify_CmdId = 925
	DungeonCandidateTeamInfoNotify_ENET_CHANNEL_ID  DungeonCandidateTeamInfoNotify_CmdId = 0
	DungeonCandidateTeamInfoNotify_ENET_IS_RELIABLE DungeonCandidateTeamInfoNotify_CmdId = 1
)

// Enum value maps for DungeonCandidateTeamInfoNotify_CmdId.
var (
	DungeonCandidateTeamInfoNotify_CmdId_name = map[int32]string{
		0:   "NONE",
		925: "CMD_ID",
		// Duplicate value: 0: "ENET_CHANNEL_ID",
		1: "ENET_IS_RELIABLE",
	}
	DungeonCandidateTeamInfoNotify_CmdId_value = map[string]int32{
		"NONE":             0,
		"CMD_ID":           925,
		"ENET_CHANNEL_ID":  0,
		"ENET_IS_RELIABLE": 1,
	}
)

func (x DungeonCandidateTeamInfoNotify_CmdId) Enum() *DungeonCandidateTeamInfoNotify_CmdId {
	p := new(DungeonCandidateTeamInfoNotify_CmdId)
	*p = x
	return p
}

func (x DungeonCandidateTeamInfoNotify_CmdId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DungeonCandidateTeamInfoNotify_CmdId) Descriptor() protoreflect.EnumDescriptor {
	return file_DungeonCandidateTeamInfoNotify_proto_enumTypes[0].Descriptor()
}

func (DungeonCandidateTeamInfoNotify_CmdId) Type() protoreflect.EnumType {
	return &file_DungeonCandidateTeamInfoNotify_proto_enumTypes[0]
}

func (x DungeonCandidateTeamInfoNotify_CmdId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DungeonCandidateTeamInfoNotify_CmdId.Descriptor instead.
func (DungeonCandidateTeamInfoNotify_CmdId) EnumDescriptor() ([]byte, []int) {
	return file_DungeonCandidateTeamInfoNotify_proto_rawDescGZIP(), []int{0, 0}
}

type DungeonCandidateTeamInfoNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DungeonId      uint32                        `protobuf:"varint,1,opt,name=dungeon_id,json=dungeonId,proto3" json:"dungeon_id,omitempty"`
	AvatarList     []*DungeonCandidateTeamAvatar `protobuf:"bytes,2,rep,name=avatar_list,json=avatarList,proto3" json:"avatar_list,omitempty"`
	ReadyPlayerUid []uint32                      `protobuf:"varint,3,rep,packed,name=ready_player_uid,json=readyPlayerUid,proto3" json:"ready_player_uid,omitempty"`
}

func (x *DungeonCandidateTeamInfoNotify) Reset() {
	*x = DungeonCandidateTeamInfoNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_DungeonCandidateTeamInfoNotify_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DungeonCandidateTeamInfoNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DungeonCandidateTeamInfoNotify) ProtoMessage() {}

func (x *DungeonCandidateTeamInfoNotify) ProtoReflect() protoreflect.Message {
	mi := &file_DungeonCandidateTeamInfoNotify_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DungeonCandidateTeamInfoNotify.ProtoReflect.Descriptor instead.
func (*DungeonCandidateTeamInfoNotify) Descriptor() ([]byte, []int) {
	return file_DungeonCandidateTeamInfoNotify_proto_rawDescGZIP(), []int{0}
}

func (x *DungeonCandidateTeamInfoNotify) GetDungeonId() uint32 {
	if x != nil {
		return x.DungeonId
	}
	return 0
}

func (x *DungeonCandidateTeamInfoNotify) GetAvatarList() []*DungeonCandidateTeamAvatar {
	if x != nil {
		return x.AvatarList
	}
	return nil
}

func (x *DungeonCandidateTeamInfoNotify) GetReadyPlayerUid() []uint32 {
	if x != nil {
		return x.ReadyPlayerUid
	}
	return nil
}

var File_DungeonCandidateTeamInfoNotify_proto protoreflect.FileDescriptor

var file_DungeonCandidateTeamInfoNotify_proto_rawDesc = []byte{
	0x0a, 0x24, 0x44, 0x75, 0x6e, 0x67, 0x65, 0x6f, 0x6e, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61,
	0x74, 0x65, 0x54, 0x65, 0x61, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x20, 0x44,
	0x75, 0x6e, 0x67, 0x65, 0x6f, 0x6e, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x54,
	0x65, 0x61, 0x6d, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xfc, 0x01, 0x0a, 0x1e, 0x44, 0x75, 0x6e, 0x67, 0x65, 0x6f, 0x6e, 0x43, 0x61, 0x6e, 0x64, 0x69,
	0x64, 0x61, 0x74, 0x65, 0x54, 0x65, 0x61, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x4e, 0x6f, 0x74, 0x69,
	0x66, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x64, 0x75, 0x6e, 0x67, 0x65, 0x6f, 0x6e, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x64, 0x75, 0x6e, 0x67, 0x65, 0x6f, 0x6e, 0x49,
	0x64, 0x12, 0x42, 0x0a, 0x0b, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x5f, 0x6c, 0x69, 0x73, 0x74,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44,
	0x75, 0x6e, 0x67, 0x65, 0x6f, 0x6e, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x54,
	0x65, 0x61, 0x6d, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x52, 0x0a, 0x61, 0x76, 0x61, 0x74, 0x61,
	0x72, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x10, 0x72, 0x65, 0x61, 0x64, 0x79, 0x5f, 0x70,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x75, 0x69, 0x64, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0d, 0x52,
	0x0e, 0x72, 0x65, 0x61, 0x64, 0x79, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x55, 0x69, 0x64, 0x22,
	0x4d, 0x0a, 0x05, 0x43, 0x6d, 0x64, 0x49, 0x64, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x4f, 0x4e, 0x45,
	0x10, 0x00, 0x12, 0x0b, 0x0a, 0x06, 0x43, 0x4d, 0x44, 0x5f, 0x49, 0x44, 0x10, 0x9d, 0x07, 0x12,
	0x13, 0x0a, 0x0f, 0x45, 0x4e, 0x45, 0x54, 0x5f, 0x43, 0x48, 0x41, 0x4e, 0x4e, 0x45, 0x4c, 0x5f,
	0x49, 0x44, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x45, 0x4e, 0x45, 0x54, 0x5f, 0x49, 0x53, 0x5f,
	0x52, 0x45, 0x4c, 0x49, 0x41, 0x42, 0x4c, 0x45, 0x10, 0x01, 0x1a, 0x02, 0x10, 0x01, 0x42, 0x0a,
	0x5a, 0x08, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_DungeonCandidateTeamInfoNotify_proto_rawDescOnce sync.Once
	file_DungeonCandidateTeamInfoNotify_proto_rawDescData = file_DungeonCandidateTeamInfoNotify_proto_rawDesc
)

func file_DungeonCandidateTeamInfoNotify_proto_rawDescGZIP() []byte {
	file_DungeonCandidateTeamInfoNotify_proto_rawDescOnce.Do(func() {
		file_DungeonCandidateTeamInfoNotify_proto_rawDescData = protoimpl.X.CompressGZIP(file_DungeonCandidateTeamInfoNotify_proto_rawDescData)
	})
	return file_DungeonCandidateTeamInfoNotify_proto_rawDescData
}

var file_DungeonCandidateTeamInfoNotify_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_DungeonCandidateTeamInfoNotify_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_DungeonCandidateTeamInfoNotify_proto_goTypes = []interface{}{
	(DungeonCandidateTeamInfoNotify_CmdId)(0), // 0: proto.DungeonCandidateTeamInfoNotify.CmdId
	(*DungeonCandidateTeamInfoNotify)(nil),    // 1: proto.DungeonCandidateTeamInfoNotify
	(*DungeonCandidateTeamAvatar)(nil),        // 2: proto.DungeonCandidateTeamAvatar
}
var file_DungeonCandidateTeamInfoNotify_proto_depIdxs = []int32{
	2, // 0: proto.DungeonCandidateTeamInfoNotify.avatar_list:type_name -> proto.DungeonCandidateTeamAvatar
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_DungeonCandidateTeamInfoNotify_proto_init() }
func file_DungeonCandidateTeamInfoNotify_proto_init() {
	if File_DungeonCandidateTeamInfoNotify_proto != nil {
		return
	}
	file_DungeonCandidateTeamAvatar_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_DungeonCandidateTeamInfoNotify_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DungeonCandidateTeamInfoNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_DungeonCandidateTeamInfoNotify_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_DungeonCandidateTeamInfoNotify_proto_goTypes,
		DependencyIndexes: file_DungeonCandidateTeamInfoNotify_proto_depIdxs,
		EnumInfos:         file_DungeonCandidateTeamInfoNotify_proto_enumTypes,
		MessageInfos:      file_DungeonCandidateTeamInfoNotify_proto_msgTypes,
	}.Build()
	File_DungeonCandidateTeamInfoNotify_proto = out.File
	file_DungeonCandidateTeamInfoNotify_proto_rawDesc = nil
	file_DungeonCandidateTeamInfoNotify_proto_goTypes = nil
	file_DungeonCandidateTeamInfoNotify_proto_depIdxs = nil
}
