// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.4.0
// source: DungeonDataType.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DungeonDataType int32

const (
	DungeonDataType_DUNGEON_DATA_NONE                          DungeonDataType = 0
	DungeonDataType_DUNGEON_DATA_END_TIME                      DungeonDataType = 1
	DungeonDataType_DUNGEON_DATA_MONSTER_DIE_COUNT             DungeonDataType = 2
	DungeonDataType_DUNGEON_DATA_LEVEL_CONFIG_ID               DungeonDataType = 3
	DungeonDataType_DUNGEON_DATA_TOWER_MONTHLY_LEVEL_CONFIG_ID DungeonDataType = 4
	DungeonDataType_DUNGEON_DATA_TOWER_FLOOR_LEVEL_CONFIG_ID   DungeonDataType = 5
)

// Enum value maps for DungeonDataType.
var (
	DungeonDataType_name = map[int32]string{
		0: "DUNGEON_DATA_NONE",
		1: "DUNGEON_DATA_END_TIME",
		2: "DUNGEON_DATA_MONSTER_DIE_COUNT",
		3: "DUNGEON_DATA_LEVEL_CONFIG_ID",
		4: "DUNGEON_DATA_TOWER_MONTHLY_LEVEL_CONFIG_ID",
		5: "DUNGEON_DATA_TOWER_FLOOR_LEVEL_CONFIG_ID",
	}
	DungeonDataType_value = map[string]int32{
		"DUNGEON_DATA_NONE":                          0,
		"DUNGEON_DATA_END_TIME":                      1,
		"DUNGEON_DATA_MONSTER_DIE_COUNT":             2,
		"DUNGEON_DATA_LEVEL_CONFIG_ID":               3,
		"DUNGEON_DATA_TOWER_MONTHLY_LEVEL_CONFIG_ID": 4,
		"DUNGEON_DATA_TOWER_FLOOR_LEVEL_CONFIG_ID":   5,
	}
)

func (x DungeonDataType) Enum() *DungeonDataType {
	p := new(DungeonDataType)
	*p = x
	return p
}

func (x DungeonDataType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DungeonDataType) Descriptor() protoreflect.EnumDescriptor {
	return file_DungeonDataType_proto_enumTypes[0].Descriptor()
}

func (DungeonDataType) Type() protoreflect.EnumType {
	return &file_DungeonDataType_proto_enumTypes[0]
}

func (x DungeonDataType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DungeonDataType.Descriptor instead.
func (DungeonDataType) EnumDescriptor() ([]byte, []int) {
	return file_DungeonDataType_proto_rawDescGZIP(), []int{0}
}

var File_DungeonDataType_proto protoreflect.FileDescriptor

var file_DungeonDataType_proto_rawDesc = []byte{
	0x0a, 0x15, 0x44, 0x75, 0x6e, 0x67, 0x65, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2a, 0xe7, 0x01, 0x0a, 0x0f, 0x44, 0x75, 0x6e, 0x67,
	0x65, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x12, 0x15, 0x0a, 0x11, 0x44,
	0x55, 0x4e, 0x47, 0x45, 0x4f, 0x4e, 0x5f, 0x44, 0x41, 0x54, 0x41, 0x5f, 0x4e, 0x4f, 0x4e, 0x45,
	0x10, 0x00, 0x12, 0x19, 0x0a, 0x15, 0x44, 0x55, 0x4e, 0x47, 0x45, 0x4f, 0x4e, 0x5f, 0x44, 0x41,
	0x54, 0x41, 0x5f, 0x45, 0x4e, 0x44, 0x5f, 0x54, 0x49, 0x4d, 0x45, 0x10, 0x01, 0x12, 0x22, 0x0a,
	0x1e, 0x44, 0x55, 0x4e, 0x47, 0x45, 0x4f, 0x4e, 0x5f, 0x44, 0x41, 0x54, 0x41, 0x5f, 0x4d, 0x4f,
	0x4e, 0x53, 0x54, 0x45, 0x52, 0x5f, 0x44, 0x49, 0x45, 0x5f, 0x43, 0x4f, 0x55, 0x4e, 0x54, 0x10,
	0x02, 0x12, 0x20, 0x0a, 0x1c, 0x44, 0x55, 0x4e, 0x47, 0x45, 0x4f, 0x4e, 0x5f, 0x44, 0x41, 0x54,
	0x41, 0x5f, 0x4c, 0x45, 0x56, 0x45, 0x4c, 0x5f, 0x43, 0x4f, 0x4e, 0x46, 0x49, 0x47, 0x5f, 0x49,
	0x44, 0x10, 0x03, 0x12, 0x2e, 0x0a, 0x2a, 0x44, 0x55, 0x4e, 0x47, 0x45, 0x4f, 0x4e, 0x5f, 0x44,
	0x41, 0x54, 0x41, 0x5f, 0x54, 0x4f, 0x57, 0x45, 0x52, 0x5f, 0x4d, 0x4f, 0x4e, 0x54, 0x48, 0x4c,
	0x59, 0x5f, 0x4c, 0x45, 0x56, 0x45, 0x4c, 0x5f, 0x43, 0x4f, 0x4e, 0x46, 0x49, 0x47, 0x5f, 0x49,
	0x44, 0x10, 0x04, 0x12, 0x2c, 0x0a, 0x28, 0x44, 0x55, 0x4e, 0x47, 0x45, 0x4f, 0x4e, 0x5f, 0x44,
	0x41, 0x54, 0x41, 0x5f, 0x54, 0x4f, 0x57, 0x45, 0x52, 0x5f, 0x46, 0x4c, 0x4f, 0x4f, 0x52, 0x5f,
	0x4c, 0x45, 0x56, 0x45, 0x4c, 0x5f, 0x43, 0x4f, 0x4e, 0x46, 0x49, 0x47, 0x5f, 0x49, 0x44, 0x10,
	0x05, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_DungeonDataType_proto_rawDescOnce sync.Once
	file_DungeonDataType_proto_rawDescData = file_DungeonDataType_proto_rawDesc
)

func file_DungeonDataType_proto_rawDescGZIP() []byte {
	file_DungeonDataType_proto_rawDescOnce.Do(func() {
		file_DungeonDataType_proto_rawDescData = protoimpl.X.CompressGZIP(file_DungeonDataType_proto_rawDescData)
	})
	return file_DungeonDataType_proto_rawDescData
}

var file_DungeonDataType_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_DungeonDataType_proto_goTypes = []interface{}{
	(DungeonDataType)(0), // 0: DungeonDataType
}
var file_DungeonDataType_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_DungeonDataType_proto_init() }
func file_DungeonDataType_proto_init() {
	if File_DungeonDataType_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_DungeonDataType_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_DungeonDataType_proto_goTypes,
		DependencyIndexes: file_DungeonDataType_proto_depIdxs,
		EnumInfos:         file_DungeonDataType_proto_enumTypes,
	}.Build()
	File_DungeonDataType_proto = out.File
	file_DungeonDataType_proto_rawDesc = nil
	file_DungeonDataType_proto_goTypes = nil
	file_DungeonDataType_proto_depIdxs = nil
}
