// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.4.0
// source: DungeonCandidateTeamDismissReason.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DungeonCandidateTeamDismissReason int32

const (
	DungeonCandidateTeamDismissReason_DUNGEON_CANDIDATE_TPDR_NORMAL DungeonCandidateTeamDismissReason = 0
	DungeonCandidateTeamDismissReason_DUNGEON_CANDIDATE_TPDR_DIE    DungeonCandidateTeamDismissReason = 1
)

// Enum value maps for DungeonCandidateTeamDismissReason.
var (
	DungeonCandidateTeamDismissReason_name = map[int32]string{
		0: "DUNGEON_CANDIDATE_TPDR_NORMAL",
		1: "DUNGEON_CANDIDATE_TPDR_DIE",
	}
	DungeonCandidateTeamDismissReason_value = map[string]int32{
		"DUNGEON_CANDIDATE_TPDR_NORMAL": 0,
		"DUNGEON_CANDIDATE_TPDR_DIE":    1,
	}
)

func (x DungeonCandidateTeamDismissReason) Enum() *DungeonCandidateTeamDismissReason {
	p := new(DungeonCandidateTeamDismissReason)
	*p = x
	return p
}

func (x DungeonCandidateTeamDismissReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DungeonCandidateTeamDismissReason) Descriptor() protoreflect.EnumDescriptor {
	return file_DungeonCandidateTeamDismissReason_proto_enumTypes[0].Descriptor()
}

func (DungeonCandidateTeamDismissReason) Type() protoreflect.EnumType {
	return &file_DungeonCandidateTeamDismissReason_proto_enumTypes[0]
}

func (x DungeonCandidateTeamDismissReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DungeonCandidateTeamDismissReason.Descriptor instead.
func (DungeonCandidateTeamDismissReason) EnumDescriptor() ([]byte, []int) {
	return file_DungeonCandidateTeamDismissReason_proto_rawDescGZIP(), []int{0}
}

var File_DungeonCandidateTeamDismissReason_proto protoreflect.FileDescriptor

var file_DungeonCandidateTeamDismissReason_proto_rawDesc = []byte{
	0x0a, 0x27, 0x44, 0x75, 0x6e, 0x67, 0x65, 0x6f, 0x6e, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61,
	0x74, 0x65, 0x54, 0x65, 0x61, 0x6d, 0x44, 0x69, 0x73, 0x6d, 0x69, 0x73, 0x73, 0x52, 0x65, 0x61,
	0x73, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2a, 0x66, 0x0a, 0x21, 0x44, 0x75, 0x6e,
	0x67, 0x65, 0x6f, 0x6e, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x54, 0x65, 0x61,
	0x6d, 0x44, 0x69, 0x73, 0x6d, 0x69, 0x73, 0x73, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x21,
	0x0a, 0x1d, 0x44, 0x55, 0x4e, 0x47, 0x45, 0x4f, 0x4e, 0x5f, 0x43, 0x41, 0x4e, 0x44, 0x49, 0x44,
	0x41, 0x54, 0x45, 0x5f, 0x54, 0x50, 0x44, 0x52, 0x5f, 0x4e, 0x4f, 0x52, 0x4d, 0x41, 0x4c, 0x10,
	0x00, 0x12, 0x1e, 0x0a, 0x1a, 0x44, 0x55, 0x4e, 0x47, 0x45, 0x4f, 0x4e, 0x5f, 0x43, 0x41, 0x4e,
	0x44, 0x49, 0x44, 0x41, 0x54, 0x45, 0x5f, 0x54, 0x50, 0x44, 0x52, 0x5f, 0x44, 0x49, 0x45, 0x10,
	0x01, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_DungeonCandidateTeamDismissReason_proto_rawDescOnce sync.Once
	file_DungeonCandidateTeamDismissReason_proto_rawDescData = file_DungeonCandidateTeamDismissReason_proto_rawDesc
)

func file_DungeonCandidateTeamDismissReason_proto_rawDescGZIP() []byte {
	file_DungeonCandidateTeamDismissReason_proto_rawDescOnce.Do(func() {
		file_DungeonCandidateTeamDismissReason_proto_rawDescData = protoimpl.X.CompressGZIP(file_DungeonCandidateTeamDismissReason_proto_rawDescData)
	})
	return file_DungeonCandidateTeamDismissReason_proto_rawDescData
}

var file_DungeonCandidateTeamDismissReason_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_DungeonCandidateTeamDismissReason_proto_goTypes = []interface{}{
	(DungeonCandidateTeamDismissReason)(0), // 0: DungeonCandidateTeamDismissReason
}
var file_DungeonCandidateTeamDismissReason_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_DungeonCandidateTeamDismissReason_proto_init() }
func file_DungeonCandidateTeamDismissReason_proto_init() {
	if File_DungeonCandidateTeamDismissReason_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_DungeonCandidateTeamDismissReason_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_DungeonCandidateTeamDismissReason_proto_goTypes,
		DependencyIndexes: file_DungeonCandidateTeamDismissReason_proto_depIdxs,
		EnumInfos:         file_DungeonCandidateTeamDismissReason_proto_enumTypes,
	}.Build()
	File_DungeonCandidateTeamDismissReason_proto = out.File
	file_DungeonCandidateTeamDismissReason_proto_rawDesc = nil
	file_DungeonCandidateTeamDismissReason_proto_goTypes = nil
	file_DungeonCandidateTeamDismissReason_proto_depIdxs = nil
}
