// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.4.0
// source: EvtRushMoveNotify.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EvtRushMoveNotify_CmdId int32

const (
	EvtRushMoveNotify_NONE             EvtRushMoveNotify_CmdId = 0
	EvtRushMoveNotify_CMD_ID           EvtRushMoveNotify_CmdId = 312
	EvtRushMoveNotify_ENET_CHANNEL_ID  EvtRushMoveNotify_CmdId = 0
	EvtRushMoveNotify_ENET_IS_RELIABLE EvtRushMoveNotify_CmdId = 1
	EvtRushMoveNotify_IS_ALLOW_CLIENT  EvtRushMoveNotify_CmdId = 1
)

// Enum value maps for EvtRushMoveNotify_CmdId.
var (
	EvtRushMoveNotify_CmdId_name = map[int32]string{
		0:   "NONE",
		312: "CMD_ID",
		// Duplicate value: 0: "ENET_CHANNEL_ID",
		1: "ENET_IS_RELIABLE",
		// Duplicate value: 1: "IS_ALLOW_CLIENT",
	}
	EvtRushMoveNotify_CmdId_value = map[string]int32{
		"NONE":             0,
		"CMD_ID":           312,
		"ENET_CHANNEL_ID":  0,
		"ENET_IS_RELIABLE": 1,
		"IS_ALLOW_CLIENT":  1,
	}
)

func (x EvtRushMoveNotify_CmdId) Enum() *EvtRushMoveNotify_CmdId {
	p := new(EvtRushMoveNotify_CmdId)
	*p = x
	return p
}

func (x EvtRushMoveNotify_CmdId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EvtRushMoveNotify_CmdId) Descriptor() protoreflect.EnumDescriptor {
	return file_EvtRushMoveNotify_proto_enumTypes[0].Descriptor()
}

func (EvtRushMoveNotify_CmdId) Type() protoreflect.EnumType {
	return &file_EvtRushMoveNotify_proto_enumTypes[0]
}

func (x EvtRushMoveNotify_CmdId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EvtRushMoveNotify_CmdId.Descriptor instead.
func (EvtRushMoveNotify_CmdId) EnumDescriptor() ([]byte, []int) {
	return file_EvtRushMoveNotify_proto_rawDescGZIP(), []int{0, 0}
}

type EvtRushMoveNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ForwardType     ForwardType      `protobuf:"varint,1,opt,name=forward_type,json=forwardType,proto3,enum=ForwardType" json:"forward_type,omitempty"`
	EvtRushMoveInfo *EvtRushMoveInfo `protobuf:"bytes,2,opt,name=evt_rush_move_info,json=evtRushMoveInfo,proto3" json:"evt_rush_move_info,omitempty"`
}

func (x *EvtRushMoveNotify) Reset() {
	*x = EvtRushMoveNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_EvtRushMoveNotify_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EvtRushMoveNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvtRushMoveNotify) ProtoMessage() {}

func (x *EvtRushMoveNotify) ProtoReflect() protoreflect.Message {
	mi := &file_EvtRushMoveNotify_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvtRushMoveNotify.ProtoReflect.Descriptor instead.
func (*EvtRushMoveNotify) Descriptor() ([]byte, []int) {
	return file_EvtRushMoveNotify_proto_rawDescGZIP(), []int{0}
}

func (x *EvtRushMoveNotify) GetForwardType() ForwardType {
	if x != nil {
		return x.ForwardType
	}
	return ForwardType_FORWARD_LOCAL
}

func (x *EvtRushMoveNotify) GetEvtRushMoveInfo() *EvtRushMoveInfo {
	if x != nil {
		return x.EvtRushMoveInfo
	}
	return nil
}

var File_EvtRushMoveNotify_proto protoreflect.FileDescriptor

var file_EvtRushMoveNotify_proto_rawDesc = []byte{
	0x0a, 0x17, 0x45, 0x76, 0x74, 0x52, 0x75, 0x73, 0x68, 0x4d, 0x6f, 0x76, 0x65, 0x4e, 0x6f, 0x74,
	0x69, 0x66, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x11, 0x46, 0x6f, 0x72, 0x77, 0x61,
	0x72, 0x64, 0x54, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x15, 0x45, 0x76,
	0x74, 0x52, 0x75, 0x73, 0x68, 0x4d, 0x6f, 0x76, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0xe7, 0x01, 0x0a, 0x11, 0x45, 0x76, 0x74, 0x52, 0x75, 0x73, 0x68, 0x4d,
	0x6f, 0x76, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x2f, 0x0a, 0x0c, 0x66, 0x6f, 0x72,
	0x77, 0x61, 0x72, 0x64, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x0c, 0x2e, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0b, 0x66,
	0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x3d, 0x0a, 0x12, 0x65, 0x76,
	0x74, 0x5f, 0x72, 0x75, 0x73, 0x68, 0x5f, 0x6d, 0x6f, 0x76, 0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x45, 0x76, 0x74, 0x52, 0x75, 0x73, 0x68,
	0x4d, 0x6f, 0x76, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0f, 0x65, 0x76, 0x74, 0x52, 0x75, 0x73,
	0x68, 0x4d, 0x6f, 0x76, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x62, 0x0a, 0x05, 0x43, 0x6d, 0x64,
	0x49, 0x64, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x06,
	0x43, 0x4d, 0x44, 0x5f, 0x49, 0x44, 0x10, 0xb8, 0x02, 0x12, 0x13, 0x0a, 0x0f, 0x45, 0x4e, 0x45,
	0x54, 0x5f, 0x43, 0x48, 0x41, 0x4e, 0x4e, 0x45, 0x4c, 0x5f, 0x49, 0x44, 0x10, 0x00, 0x12, 0x14,
	0x0a, 0x10, 0x45, 0x4e, 0x45, 0x54, 0x5f, 0x49, 0x53, 0x5f, 0x52, 0x45, 0x4c, 0x49, 0x41, 0x42,
	0x4c, 0x45, 0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f, 0x49, 0x53, 0x5f, 0x41, 0x4c, 0x4c, 0x4f, 0x57,
	0x5f, 0x43, 0x4c, 0x49, 0x45, 0x4e, 0x54, 0x10, 0x01, 0x1a, 0x02, 0x10, 0x01, 0x42, 0x0a, 0x5a,
	0x08, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_EvtRushMoveNotify_proto_rawDescOnce sync.Once
	file_EvtRushMoveNotify_proto_rawDescData = file_EvtRushMoveNotify_proto_rawDesc
)

func file_EvtRushMoveNotify_proto_rawDescGZIP() []byte {
	file_EvtRushMoveNotify_proto_rawDescOnce.Do(func() {
		file_EvtRushMoveNotify_proto_rawDescData = protoimpl.X.CompressGZIP(file_EvtRushMoveNotify_proto_rawDescData)
	})
	return file_EvtRushMoveNotify_proto_rawDescData
}

var file_EvtRushMoveNotify_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_EvtRushMoveNotify_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_EvtRushMoveNotify_proto_goTypes = []interface{}{
	(EvtRushMoveNotify_CmdId)(0), // 0: EvtRushMoveNotify.CmdId
	(*EvtRushMoveNotify)(nil),    // 1: EvtRushMoveNotify
	(ForwardType)(0),             // 2: ForwardType
	(*EvtRushMoveInfo)(nil),      // 3: EvtRushMoveInfo
}
var file_EvtRushMoveNotify_proto_depIdxs = []int32{
	2, // 0: EvtRushMoveNotify.forward_type:type_name -> ForwardType
	3, // 1: EvtRushMoveNotify.evt_rush_move_info:type_name -> EvtRushMoveInfo
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_EvtRushMoveNotify_proto_init() }
func file_EvtRushMoveNotify_proto_init() {
	if File_EvtRushMoveNotify_proto != nil {
		return
	}
	file_ForwardType_proto_init()
	file_EvtRushMoveInfo_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_EvtRushMoveNotify_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EvtRushMoveNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_EvtRushMoveNotify_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_EvtRushMoveNotify_proto_goTypes,
		DependencyIndexes: file_EvtRushMoveNotify_proto_depIdxs,
		EnumInfos:         file_EvtRushMoveNotify_proto_enumTypes,
		MessageInfos:      file_EvtRushMoveNotify_proto_msgTypes,
	}.Build()
	File_EvtRushMoveNotify_proto = out.File
	file_EvtRushMoveNotify_proto_rawDesc = nil
	file_EvtRushMoveNotify_proto_goTypes = nil
	file_EvtRushMoveNotify_proto_depIdxs = nil
}
