// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.4.0
// source: ExecuteGadgetLuaReq.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecuteGadgetLuaReq_CmdId int32

const (
	ExecuteGadgetLuaReq_NONE             ExecuteGadgetLuaReq_CmdId = 0
	ExecuteGadgetLuaReq_CMD_ID           ExecuteGadgetLuaReq_CmdId = 293
	ExecuteGadgetLuaReq_ENET_CHANNEL_ID  ExecuteGadgetLuaReq_CmdId = 0
	ExecuteGadgetLuaReq_ENET_IS_RELIABLE ExecuteGadgetLuaReq_CmdId = 1
	ExecuteGadgetLuaReq_IS_ALLOW_CLIENT  ExecuteGadgetLuaReq_CmdId = 1
)

// Enum value maps for ExecuteGadgetLuaReq_CmdId.
var (
	ExecuteGadgetLuaReq_CmdId_name = map[int32]string{
		0:   "NONE",
		293: "CMD_ID",
		// Duplicate value: 0: "ENET_CHANNEL_ID",
		1: "ENET_IS_RELIABLE",
		// Duplicate value: 1: "IS_ALLOW_CLIENT",
	}
	ExecuteGadgetLuaReq_CmdId_value = map[string]int32{
		"NONE":             0,
		"CMD_ID":           293,
		"ENET_CHANNEL_ID":  0,
		"ENET_IS_RELIABLE": 1,
		"IS_ALLOW_CLIENT":  1,
	}
)

func (x ExecuteGadgetLuaReq_CmdId) Enum() *ExecuteGadgetLuaReq_CmdId {
	p := new(ExecuteGadgetLuaReq_CmdId)
	*p = x
	return p
}

func (x ExecuteGadgetLuaReq_CmdId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExecuteGadgetLuaReq_CmdId) Descriptor() protoreflect.EnumDescriptor {
	return file_ExecuteGadgetLuaReq_proto_enumTypes[0].Descriptor()
}

func (ExecuteGadgetLuaReq_CmdId) Type() protoreflect.EnumType {
	return &file_ExecuteGadgetLuaReq_proto_enumTypes[0]
}

func (x ExecuteGadgetLuaReq_CmdId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExecuteGadgetLuaReq_CmdId.Descriptor instead.
func (ExecuteGadgetLuaReq_CmdId) EnumDescriptor() ([]byte, []int) {
	return file_ExecuteGadgetLuaReq_proto_rawDescGZIP(), []int{0, 0}
}

type ExecuteGadgetLuaReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SourceEntityId uint32 `protobuf:"varint,1,opt,name=source_entity_id,json=sourceEntityId,proto3" json:"source_entity_id,omitempty"`
	Param1         int32  `protobuf:"varint,2,opt,name=param1,proto3" json:"param1,omitempty"`
	Param2         int32  `protobuf:"varint,3,opt,name=param2,proto3" json:"param2,omitempty"`
	Param3         int32  `protobuf:"varint,4,opt,name=param3,proto3" json:"param3,omitempty"`
}

func (x *ExecuteGadgetLuaReq) Reset() {
	*x = ExecuteGadgetLuaReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ExecuteGadgetLuaReq_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecuteGadgetLuaReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteGadgetLuaReq) ProtoMessage() {}

func (x *ExecuteGadgetLuaReq) ProtoReflect() protoreflect.Message {
	mi := &file_ExecuteGadgetLuaReq_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteGadgetLuaReq.ProtoReflect.Descriptor instead.
func (*ExecuteGadgetLuaReq) Descriptor() ([]byte, []int) {
	return file_ExecuteGadgetLuaReq_proto_rawDescGZIP(), []int{0}
}

func (x *ExecuteGadgetLuaReq) GetSourceEntityId() uint32 {
	if x != nil {
		return x.SourceEntityId
	}
	return 0
}

func (x *ExecuteGadgetLuaReq) GetParam1() int32 {
	if x != nil {
		return x.Param1
	}
	return 0
}

func (x *ExecuteGadgetLuaReq) GetParam2() int32 {
	if x != nil {
		return x.Param2
	}
	return 0
}

func (x *ExecuteGadgetLuaReq) GetParam3() int32 {
	if x != nil {
		return x.Param3
	}
	return 0
}

var File_ExecuteGadgetLuaReq_proto protoreflect.FileDescriptor

var file_ExecuteGadgetLuaReq_proto_rawDesc = []byte{
	0x0a, 0x19, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x47, 0x61, 0x64, 0x67, 0x65, 0x74, 0x4c,
	0x75, 0x61, 0x52, 0x65, 0x71, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0xeb, 0x01, 0x0a, 0x13, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x47, 0x61,
	0x64, 0x67, 0x65, 0x74, 0x4c, 0x75, 0x61, 0x52, 0x65, 0x71, 0x12, 0x28, 0x0a, 0x10, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x5f, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x0e, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x45, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x31, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x31, 0x12, 0x16, 0x0a, 0x06,
	0x70, 0x61, 0x72, 0x61, 0x6d, 0x32, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x70, 0x61,
	0x72, 0x61, 0x6d, 0x32, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x33, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x33, 0x22, 0x62, 0x0a, 0x05,
	0x43, 0x6d, 0x64, 0x49, 0x64, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12,
	0x0b, 0x0a, 0x06, 0x43, 0x4d, 0x44, 0x5f, 0x49, 0x44, 0x10, 0xa5, 0x02, 0x12, 0x13, 0x0a, 0x0f,
	0x45, 0x4e, 0x45, 0x54, 0x5f, 0x43, 0x48, 0x41, 0x4e, 0x4e, 0x45, 0x4c, 0x5f, 0x49, 0x44, 0x10,
	0x00, 0x12, 0x14, 0x0a, 0x10, 0x45, 0x4e, 0x45, 0x54, 0x5f, 0x49, 0x53, 0x5f, 0x52, 0x45, 0x4c,
	0x49, 0x41, 0x42, 0x4c, 0x45, 0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f, 0x49, 0x53, 0x5f, 0x41, 0x4c,
	0x4c, 0x4f, 0x57, 0x5f, 0x43, 0x4c, 0x49, 0x45, 0x4e, 0x54, 0x10, 0x01, 0x1a, 0x02, 0x10, 0x01,
	0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ExecuteGadgetLuaReq_proto_rawDescOnce sync.Once
	file_ExecuteGadgetLuaReq_proto_rawDescData = file_ExecuteGadgetLuaReq_proto_rawDesc
)

func file_ExecuteGadgetLuaReq_proto_rawDescGZIP() []byte {
	file_ExecuteGadgetLuaReq_proto_rawDescOnce.Do(func() {
		file_ExecuteGadgetLuaReq_proto_rawDescData = protoimpl.X.CompressGZIP(file_ExecuteGadgetLuaReq_proto_rawDescData)
	})
	return file_ExecuteGadgetLuaReq_proto_rawDescData
}

var file_ExecuteGadgetLuaReq_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ExecuteGadgetLuaReq_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ExecuteGadgetLuaReq_proto_goTypes = []interface{}{
	(ExecuteGadgetLuaReq_CmdId)(0), // 0: proto.ExecuteGadgetLuaReq.CmdId
	(*ExecuteGadgetLuaReq)(nil),    // 1: proto.ExecuteGadgetLuaReq
}
var file_ExecuteGadgetLuaReq_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ExecuteGadgetLuaReq_proto_init() }
func file_ExecuteGadgetLuaReq_proto_init() {
	if File_ExecuteGadgetLuaReq_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ExecuteGadgetLuaReq_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecuteGadgetLuaReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ExecuteGadgetLuaReq_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ExecuteGadgetLuaReq_proto_goTypes,
		DependencyIndexes: file_ExecuteGadgetLuaReq_proto_depIdxs,
		EnumInfos:         file_ExecuteGadgetLuaReq_proto_enumTypes,
		MessageInfos:      file_ExecuteGadgetLuaReq_proto_msgTypes,
	}.Build()
	File_ExecuteGadgetLuaReq_proto = out.File
	file_ExecuteGadgetLuaReq_proto_rawDesc = nil
	file_ExecuteGadgetLuaReq_proto_goTypes = nil
	file_ExecuteGadgetLuaReq_proto_depIdxs = nil
}
