// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.4.0
// source: ExecuteGadgetLuaRsp.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecuteGadgetLuaRsp_CmdId int32

const (
	ExecuteGadgetLuaRsp_NONE             ExecuteGadgetLuaRsp_CmdId = 0
	ExecuteGadgetLuaRsp_CMD_ID           ExecuteGadgetLuaRsp_CmdId = 294
	ExecuteGadgetLuaRsp_ENET_CHANNEL_ID  ExecuteGadgetLuaRsp_CmdId = 0
	ExecuteGadgetLuaRsp_ENET_IS_RELIABLE ExecuteGadgetLuaRsp_CmdId = 1
)

// Enum value maps for ExecuteGadgetLuaRsp_CmdId.
var (
	ExecuteGadgetLuaRsp_CmdId_name = map[int32]string{
		0:   "NONE",
		294: "CMD_ID",
		// Duplicate value: 0: "ENET_CHANNEL_ID",
		1: "ENET_IS_RELIABLE",
	}
	ExecuteGadgetLuaRsp_CmdId_value = map[string]int32{
		"NONE":             0,
		"CMD_ID":           294,
		"ENET_CHANNEL_ID":  0,
		"ENET_IS_RELIABLE": 1,
	}
)

func (x ExecuteGadgetLuaRsp_CmdId) Enum() *ExecuteGadgetLuaRsp_CmdId {
	p := new(ExecuteGadgetLuaRsp_CmdId)
	*p = x
	return p
}

func (x ExecuteGadgetLuaRsp_CmdId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExecuteGadgetLuaRsp_CmdId) Descriptor() protoreflect.EnumDescriptor {
	return file_ExecuteGadgetLuaRsp_proto_enumTypes[0].Descriptor()
}

func (ExecuteGadgetLuaRsp_CmdId) Type() protoreflect.EnumType {
	return &file_ExecuteGadgetLuaRsp_proto_enumTypes[0]
}

func (x ExecuteGadgetLuaRsp_CmdId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExecuteGadgetLuaRsp_CmdId.Descriptor instead.
func (ExecuteGadgetLuaRsp_CmdId) EnumDescriptor() ([]byte, []int) {
	return file_ExecuteGadgetLuaRsp_proto_rawDescGZIP(), []int{0, 0}
}

type ExecuteGadgetLuaRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Retcode int32 `protobuf:"varint,1,opt,name=retcode,proto3" json:"retcode,omitempty"`
}

func (x *ExecuteGadgetLuaRsp) Reset() {
	*x = ExecuteGadgetLuaRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ExecuteGadgetLuaRsp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecuteGadgetLuaRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteGadgetLuaRsp) ProtoMessage() {}

func (x *ExecuteGadgetLuaRsp) ProtoReflect() protoreflect.Message {
	mi := &file_ExecuteGadgetLuaRsp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteGadgetLuaRsp.ProtoReflect.Descriptor instead.
func (*ExecuteGadgetLuaRsp) Descriptor() ([]byte, []int) {
	return file_ExecuteGadgetLuaRsp_proto_rawDescGZIP(), []int{0}
}

func (x *ExecuteGadgetLuaRsp) GetRetcode() int32 {
	if x != nil {
		return x.Retcode
	}
	return 0
}

var File_ExecuteGadgetLuaRsp_proto protoreflect.FileDescriptor

var file_ExecuteGadgetLuaRsp_proto_rawDesc = []byte{
	0x0a, 0x19, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x47, 0x61, 0x64, 0x67, 0x65, 0x74, 0x4c,
	0x75, 0x61, 0x52, 0x73, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7e, 0x0a, 0x13, 0x45,
	0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x47, 0x61, 0x64, 0x67, 0x65, 0x74, 0x4c, 0x75, 0x61, 0x52,
	0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x74, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x07, 0x72, 0x65, 0x74, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x4d, 0x0a, 0x05,
	0x43, 0x6d, 0x64, 0x49, 0x64, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12,
	0x0b, 0x0a, 0x06, 0x43, 0x4d, 0x44, 0x5f, 0x49, 0x44, 0x10, 0xa6, 0x02, 0x12, 0x13, 0x0a, 0x0f,
	0x45, 0x4e, 0x45, 0x54, 0x5f, 0x43, 0x48, 0x41, 0x4e, 0x4e, 0x45, 0x4c, 0x5f, 0x49, 0x44, 0x10,
	0x00, 0x12, 0x14, 0x0a, 0x10, 0x45, 0x4e, 0x45, 0x54, 0x5f, 0x49, 0x53, 0x5f, 0x52, 0x45, 0x4c,
	0x49, 0x41, 0x42, 0x4c, 0x45, 0x10, 0x01, 0x1a, 0x02, 0x10, 0x01, 0x42, 0x0a, 0x5a, 0x08, 0x2e,
	0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ExecuteGadgetLuaRsp_proto_rawDescOnce sync.Once
	file_ExecuteGadgetLuaRsp_proto_rawDescData = file_ExecuteGadgetLuaRsp_proto_rawDesc
)

func file_ExecuteGadgetLuaRsp_proto_rawDescGZIP() []byte {
	file_ExecuteGadgetLuaRsp_proto_rawDescOnce.Do(func() {
		file_ExecuteGadgetLuaRsp_proto_rawDescData = protoimpl.X.CompressGZIP(file_ExecuteGadgetLuaRsp_proto_rawDescData)
	})
	return file_ExecuteGadgetLuaRsp_proto_rawDescData
}

var file_ExecuteGadgetLuaRsp_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ExecuteGadgetLuaRsp_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ExecuteGadgetLuaRsp_proto_goTypes = []interface{}{
	(ExecuteGadgetLuaRsp_CmdId)(0), // 0: ExecuteGadgetLuaRsp.CmdId
	(*ExecuteGadgetLuaRsp)(nil),    // 1: ExecuteGadgetLuaRsp
}
var file_ExecuteGadgetLuaRsp_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ExecuteGadgetLuaRsp_proto_init() }
func file_ExecuteGadgetLuaRsp_proto_init() {
	if File_ExecuteGadgetLuaRsp_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ExecuteGadgetLuaRsp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecuteGadgetLuaRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ExecuteGadgetLuaRsp_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ExecuteGadgetLuaRsp_proto_goTypes,
		DependencyIndexes: file_ExecuteGadgetLuaRsp_proto_depIdxs,
		EnumInfos:         file_ExecuteGadgetLuaRsp_proto_enumTypes,
		MessageInfos:      file_ExecuteGadgetLuaRsp_proto_msgTypes,
	}.Build()
	File_ExecuteGadgetLuaRsp_proto = out.File
	file_ExecuteGadgetLuaRsp_proto_rawDesc = nil
	file_ExecuteGadgetLuaRsp_proto_goTypes = nil
	file_ExecuteGadgetLuaRsp_proto_depIdxs = nil
}
