// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.4.0
// source: ForgeQueueDataNotify.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ForgeQueueDataNotify_CmdId int32

const (
	ForgeQueueDataNotify_NONE             ForgeQueueDataNotify_CmdId = 0
	ForgeQueueDataNotify_CMD_ID           ForgeQueueDataNotify_CmdId = 636
	ForgeQueueDataNotify_ENET_CHANNEL_ID  ForgeQueueDataNotify_CmdId = 0
	ForgeQueueDataNotify_ENET_IS_RELIABLE ForgeQueueDataNotify_CmdId = 1
	ForgeQueueDataNotify_IS_ALLOW_CLIENT  ForgeQueueDataNotify_CmdId = 1
)

// Enum value maps for ForgeQueueDataNotify_CmdId.
var (
	ForgeQueueDataNotify_CmdId_name = map[int32]string{
		0:   "NONE",
		636: "CMD_ID",
		// Duplicate value: 0: "ENET_CHANNEL_ID",
		1: "ENET_IS_RELIABLE",
		// Duplicate value: 1: "IS_ALLOW_CLIENT",
	}
	ForgeQueueDataNotify_CmdId_value = map[string]int32{
		"NONE":             0,
		"CMD_ID":           636,
		"ENET_CHANNEL_ID":  0,
		"ENET_IS_RELIABLE": 1,
		"IS_ALLOW_CLIENT":  1,
	}
)

func (x ForgeQueueDataNotify_CmdId) Enum() *ForgeQueueDataNotify_CmdId {
	p := new(ForgeQueueDataNotify_CmdId)
	*p = x
	return p
}

func (x ForgeQueueDataNotify_CmdId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ForgeQueueDataNotify_CmdId) Descriptor() protoreflect.EnumDescriptor {
	return file_ForgeQueueDataNotify_proto_enumTypes[0].Descriptor()
}

func (ForgeQueueDataNotify_CmdId) Type() protoreflect.EnumType {
	return &file_ForgeQueueDataNotify_proto_enumTypes[0]
}

func (x ForgeQueueDataNotify_CmdId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ForgeQueueDataNotify_CmdId.Descriptor instead.
func (ForgeQueueDataNotify_CmdId) EnumDescriptor() ([]byte, []int) {
	return file_ForgeQueueDataNotify_proto_rawDescGZIP(), []int{0, 0}
}

type ForgeQueueDataNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ForgeQueueMap         map[uint32]*ForgeQueueData `protobuf:"bytes,1,rep,name=forge_queue_map,json=forgeQueueMap,proto3" json:"forge_queue_map,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	RemovedForgeQueueList []uint32                   `protobuf:"varint,2,rep,packed,name=removed_forge_queue_list,json=removedForgeQueueList,proto3" json:"removed_forge_queue_list,omitempty"`
}

func (x *ForgeQueueDataNotify) Reset() {
	*x = ForgeQueueDataNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ForgeQueueDataNotify_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ForgeQueueDataNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForgeQueueDataNotify) ProtoMessage() {}

func (x *ForgeQueueDataNotify) ProtoReflect() protoreflect.Message {
	mi := &file_ForgeQueueDataNotify_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForgeQueueDataNotify.ProtoReflect.Descriptor instead.
func (*ForgeQueueDataNotify) Descriptor() ([]byte, []int) {
	return file_ForgeQueueDataNotify_proto_rawDescGZIP(), []int{0}
}

func (x *ForgeQueueDataNotify) GetForgeQueueMap() map[uint32]*ForgeQueueData {
	if x != nil {
		return x.ForgeQueueMap
	}
	return nil
}

func (x *ForgeQueueDataNotify) GetRemovedForgeQueueList() []uint32 {
	if x != nil {
		return x.RemovedForgeQueueList
	}
	return nil
}

var File_ForgeQueueDataNotify_proto protoreflect.FileDescriptor

var file_ForgeQueueDataNotify_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x46, 0x6f, 0x72, 0x67, 0x65, 0x51, 0x75, 0x65, 0x75, 0x65, 0x44, 0x61, 0x74, 0x61,
	0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x14, 0x46, 0x6f, 0x72, 0x67, 0x65, 0x51, 0x75, 0x65, 0x75, 0x65, 0x44,
	0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xe4, 0x02, 0x0a, 0x14, 0x46, 0x6f,
	0x72, 0x67, 0x65, 0x51, 0x75, 0x65, 0x75, 0x65, 0x44, 0x61, 0x74, 0x61, 0x4e, 0x6f, 0x74, 0x69,
	0x66, 0x79, 0x12, 0x56, 0x0a, 0x0f, 0x66, 0x6f, 0x72, 0x67, 0x65, 0x5f, 0x71, 0x75, 0x65, 0x75,
	0x65, 0x5f, 0x6d, 0x61, 0x70, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x46, 0x6f, 0x72, 0x67, 0x65, 0x51, 0x75, 0x65, 0x75, 0x65, 0x44, 0x61,
	0x74, 0x61, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x46, 0x6f, 0x72, 0x67, 0x65, 0x51, 0x75,
	0x65, 0x75, 0x65, 0x4d, 0x61, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0d, 0x66, 0x6f, 0x72,
	0x67, 0x65, 0x51, 0x75, 0x65, 0x75, 0x65, 0x4d, 0x61, 0x70, 0x12, 0x37, 0x0a, 0x18, 0x72, 0x65,
	0x6d, 0x6f, 0x76, 0x65, 0x64, 0x5f, 0x66, 0x6f, 0x72, 0x67, 0x65, 0x5f, 0x71, 0x75, 0x65, 0x75,
	0x65, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x15, 0x72, 0x65,
	0x6d, 0x6f, 0x76, 0x65, 0x64, 0x46, 0x6f, 0x72, 0x67, 0x65, 0x51, 0x75, 0x65, 0x75, 0x65, 0x4c,
	0x69, 0x73, 0x74, 0x1a, 0x57, 0x0a, 0x12, 0x46, 0x6f, 0x72, 0x67, 0x65, 0x51, 0x75, 0x65, 0x75,
	0x65, 0x4d, 0x61, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x2b, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x46, 0x6f, 0x72, 0x67, 0x65, 0x51, 0x75, 0x65, 0x75, 0x65, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x62, 0x0a, 0x05,
	0x43, 0x6d, 0x64, 0x49, 0x64, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12,
	0x0b, 0x0a, 0x06, 0x43, 0x4d, 0x44, 0x5f, 0x49, 0x44, 0x10, 0xfc, 0x04, 0x12, 0x13, 0x0a, 0x0f,
	0x45, 0x4e, 0x45, 0x54, 0x5f, 0x43, 0x48, 0x41, 0x4e, 0x4e, 0x45, 0x4c, 0x5f, 0x49, 0x44, 0x10,
	0x00, 0x12, 0x14, 0x0a, 0x10, 0x45, 0x4e, 0x45, 0x54, 0x5f, 0x49, 0x53, 0x5f, 0x52, 0x45, 0x4c,
	0x49, 0x41, 0x42, 0x4c, 0x45, 0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f, 0x49, 0x53, 0x5f, 0x41, 0x4c,
	0x4c, 0x4f, 0x57, 0x5f, 0x43, 0x4c, 0x49, 0x45, 0x4e, 0x54, 0x10, 0x01, 0x1a, 0x02, 0x10, 0x01,
	0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ForgeQueueDataNotify_proto_rawDescOnce sync.Once
	file_ForgeQueueDataNotify_proto_rawDescData = file_ForgeQueueDataNotify_proto_rawDesc
)

func file_ForgeQueueDataNotify_proto_rawDescGZIP() []byte {
	file_ForgeQueueDataNotify_proto_rawDescOnce.Do(func() {
		file_ForgeQueueDataNotify_proto_rawDescData = protoimpl.X.CompressGZIP(file_ForgeQueueDataNotify_proto_rawDescData)
	})
	return file_ForgeQueueDataNotify_proto_rawDescData
}

var file_ForgeQueueDataNotify_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ForgeQueueDataNotify_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ForgeQueueDataNotify_proto_goTypes = []interface{}{
	(ForgeQueueDataNotify_CmdId)(0), // 0: proto.ForgeQueueDataNotify.CmdId
	(*ForgeQueueDataNotify)(nil),    // 1: proto.ForgeQueueDataNotify
	nil,                             // 2: proto.ForgeQueueDataNotify.ForgeQueueMapEntry
	(*ForgeQueueData)(nil),          // 3: proto.ForgeQueueData
}
var file_ForgeQueueDataNotify_proto_depIdxs = []int32{
	2, // 0: proto.ForgeQueueDataNotify.forge_queue_map:type_name -> proto.ForgeQueueDataNotify.ForgeQueueMapEntry
	3, // 1: proto.ForgeQueueDataNotify.ForgeQueueMapEntry.value:type_name -> proto.ForgeQueueData
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_ForgeQueueDataNotify_proto_init() }
func file_ForgeQueueDataNotify_proto_init() {
	if File_ForgeQueueDataNotify_proto != nil {
		return
	}
	file_ForgeQueueData_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_ForgeQueueDataNotify_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ForgeQueueDataNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ForgeQueueDataNotify_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ForgeQueueDataNotify_proto_goTypes,
		DependencyIndexes: file_ForgeQueueDataNotify_proto_depIdxs,
		EnumInfos:         file_ForgeQueueDataNotify_proto_enumTypes,
		MessageInfos:      file_ForgeQueueDataNotify_proto_msgTypes,
	}.Build()
	File_ForgeQueueDataNotify_proto = out.File
	file_ForgeQueueDataNotify_proto_rawDesc = nil
	file_ForgeQueueDataNotify_proto_goTypes = nil
	file_ForgeQueueDataNotify_proto_depIdxs = nil
}
