// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.4.0
// source: GetPlayerBlacklistReq.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPlayerBlacklistReq_CmdId int32

const (
	GetPlayerBlacklistReq_NONE             GetPlayerBlacklistReq_CmdId = 0
	GetPlayerBlacklistReq_CMD_ID           GetPlayerBlacklistReq_CmdId = 4039
	GetPlayerBlacklistReq_ENET_CHANNEL_ID  GetPlayerBlacklistReq_CmdId = 0
	GetPlayerBlacklistReq_ENET_IS_RELIABLE GetPlayerBlacklistReq_CmdId = 1
	GetPlayerBlacklistReq_IS_ALLOW_CLIENT  GetPlayerBlacklistReq_CmdId = 1
)

// Enum value maps for GetPlayerBlacklistReq_CmdId.
var (
	GetPlayerBlacklistReq_CmdId_name = map[int32]string{
		0:    "NONE",
		4039: "CMD_ID",
		// Duplicate value: 0: "ENET_CHANNEL_ID",
		1: "ENET_IS_RELIABLE",
		// Duplicate value: 1: "IS_ALLOW_CLIENT",
	}
	GetPlayerBlacklistReq_CmdId_value = map[string]int32{
		"NONE":             0,
		"CMD_ID":           4039,
		"ENET_CHANNEL_ID":  0,
		"ENET_IS_RELIABLE": 1,
		"IS_ALLOW_CLIENT":  1,
	}
)

func (x GetPlayerBlacklistReq_CmdId) Enum() *GetPlayerBlacklistReq_CmdId {
	p := new(GetPlayerBlacklistReq_CmdId)
	*p = x
	return p
}

func (x GetPlayerBlacklistReq_CmdId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetPlayerBlacklistReq_CmdId) Descriptor() protoreflect.EnumDescriptor {
	return file_GetPlayerBlacklistReq_proto_enumTypes[0].Descriptor()
}

func (GetPlayerBlacklistReq_CmdId) Type() protoreflect.EnumType {
	return &file_GetPlayerBlacklistReq_proto_enumTypes[0]
}

func (x GetPlayerBlacklistReq_CmdId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetPlayerBlacklistReq_CmdId.Descriptor instead.
func (GetPlayerBlacklistReq_CmdId) EnumDescriptor() ([]byte, []int) {
	return file_GetPlayerBlacklistReq_proto_rawDescGZIP(), []int{0, 0}
}

type GetPlayerBlacklistReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetPlayerBlacklistReq) Reset() {
	*x = GetPlayerBlacklistReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GetPlayerBlacklistReq_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPlayerBlacklistReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerBlacklistReq) ProtoMessage() {}

func (x *GetPlayerBlacklistReq) ProtoReflect() protoreflect.Message {
	mi := &file_GetPlayerBlacklistReq_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerBlacklistReq.ProtoReflect.Descriptor instead.
func (*GetPlayerBlacklistReq) Descriptor() ([]byte, []int) {
	return file_GetPlayerBlacklistReq_proto_rawDescGZIP(), []int{0}
}

var File_GetPlayerBlacklistReq_proto protoreflect.FileDescriptor

var file_GetPlayerBlacklistReq_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x47, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x42, 0x6c, 0x61, 0x63, 0x6b,
	0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7b, 0x0a,
	0x15, 0x47, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x42, 0x6c, 0x61, 0x63, 0x6b, 0x6c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x22, 0x62, 0x0a, 0x05, 0x43, 0x6d, 0x64, 0x49, 0x64, 0x12,
	0x08, 0x0a, 0x04, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x06, 0x43, 0x4d, 0x44,
	0x5f, 0x49, 0x44, 0x10, 0xc7, 0x1f, 0x12, 0x13, 0x0a, 0x0f, 0x45, 0x4e, 0x45, 0x54, 0x5f, 0x43,
	0x48, 0x41, 0x4e, 0x4e, 0x45, 0x4c, 0x5f, 0x49, 0x44, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x45,
	0x4e, 0x45, 0x54, 0x5f, 0x49, 0x53, 0x5f, 0x52, 0x45, 0x4c, 0x49, 0x41, 0x42, 0x4c, 0x45, 0x10,
	0x01, 0x12, 0x13, 0x0a, 0x0f, 0x49, 0x53, 0x5f, 0x41, 0x4c, 0x4c, 0x4f, 0x57, 0x5f, 0x43, 0x4c,
	0x49, 0x45, 0x4e, 0x54, 0x10, 0x01, 0x1a, 0x02, 0x10, 0x01, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f,
	0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_GetPlayerBlacklistReq_proto_rawDescOnce sync.Once
	file_GetPlayerBlacklistReq_proto_rawDescData = file_GetPlayerBlacklistReq_proto_rawDesc
)

func file_GetPlayerBlacklistReq_proto_rawDescGZIP() []byte {
	file_GetPlayerBlacklistReq_proto_rawDescOnce.Do(func() {
		file_GetPlayerBlacklistReq_proto_rawDescData = protoimpl.X.CompressGZIP(file_GetPlayerBlacklistReq_proto_rawDescData)
	})
	return file_GetPlayerBlacklistReq_proto_rawDescData
}

var file_GetPlayerBlacklistReq_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_GetPlayerBlacklistReq_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_GetPlayerBlacklistReq_proto_goTypes = []interface{}{
	(GetPlayerBlacklistReq_CmdId)(0), // 0: GetPlayerBlacklistReq.CmdId
	(*GetPlayerBlacklistReq)(nil),    // 1: GetPlayerBlacklistReq
}
var file_GetPlayerBlacklistReq_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_GetPlayerBlacklistReq_proto_init() }
func file_GetPlayerBlacklistReq_proto_init() {
	if File_GetPlayerBlacklistReq_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_GetPlayerBlacklistReq_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPlayerBlacklistReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_GetPlayerBlacklistReq_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_GetPlayerBlacklistReq_proto_goTypes,
		DependencyIndexes: file_GetPlayerBlacklistReq_proto_depIdxs,
		EnumInfos:         file_GetPlayerBlacklistReq_proto_enumTypes,
		MessageInfos:      file_GetPlayerBlacklistReq_proto_msgTypes,
	}.Build()
	File_GetPlayerBlacklistReq_proto = out.File
	file_GetPlayerBlacklistReq_proto_rawDesc = nil
	file_GetPlayerBlacklistReq_proto_goTypes = nil
	file_GetPlayerBlacklistReq_proto_depIdxs = nil
}
