// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.4.0
// source: MonsterGuestBanDrop.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MonsterGuestBanDrop int32

const (
	MonsterGuestBanDrop_MONSTER_GUEST_BAN_NONE         MonsterGuestBanDrop = 0
	MonsterGuestBanDrop_MONSTER_GUEST_BAN_DIE_EXP      MonsterGuestBanDrop = 1
	MonsterGuestBanDrop_MONSTER_GUEST_BAN_DIE_LUA      MonsterGuestBanDrop = 2
	MonsterGuestBanDrop_MONSTER_GUEST_BAN_DIE_EXCEL    MonsterGuestBanDrop = 4
	MonsterGuestBanDrop_MONSTER_GUEST_BAN_DIE_ACTIVITY MonsterGuestBanDrop = 8
	MonsterGuestBanDrop_MONSTER_GUEST_BAN_DROP_HP      MonsterGuestBanDrop = 16
	MonsterGuestBanDrop_MONSTER_GUEST_BAN_SUBFIELD     MonsterGuestBanDrop = 32
)

// Enum value maps for MonsterGuestBanDrop.
var (
	MonsterGuestBanDrop_name = map[int32]string{
		0:  "MONSTER_GUEST_BAN_NONE",
		1:  "MONSTER_GUEST_BAN_DIE_EXP",
		2:  "MONSTER_GUEST_BAN_DIE_LUA",
		4:  "MONSTER_GUEST_BAN_DIE_EXCEL",
		8:  "MONSTER_GUEST_BAN_DIE_ACTIVITY",
		16: "MONSTER_GUEST_BAN_DROP_HP",
		32: "MONSTER_GUEST_BAN_SUBFIELD",
	}
	MonsterGuestBanDrop_value = map[string]int32{
		"MONSTER_GUEST_BAN_NONE":         0,
		"MONSTER_GUEST_BAN_DIE_EXP":      1,
		"MONSTER_GUEST_BAN_DIE_LUA":      2,
		"MONSTER_GUEST_BAN_DIE_EXCEL":    4,
		"MONSTER_GUEST_BAN_DIE_ACTIVITY": 8,
		"MONSTER_GUEST_BAN_DROP_HP":      16,
		"MONSTER_GUEST_BAN_SUBFIELD":     32,
	}
)

func (x MonsterGuestBanDrop) Enum() *MonsterGuestBanDrop {
	p := new(MonsterGuestBanDrop)
	*p = x
	return p
}

func (x MonsterGuestBanDrop) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MonsterGuestBanDrop) Descriptor() protoreflect.EnumDescriptor {
	return file_MonsterGuestBanDrop_proto_enumTypes[0].Descriptor()
}

func (MonsterGuestBanDrop) Type() protoreflect.EnumType {
	return &file_MonsterGuestBanDrop_proto_enumTypes[0]
}

func (x MonsterGuestBanDrop) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MonsterGuestBanDrop.Descriptor instead.
func (MonsterGuestBanDrop) EnumDescriptor() ([]byte, []int) {
	return file_MonsterGuestBanDrop_proto_rawDescGZIP(), []int{0}
}

var File_MonsterGuestBanDrop_proto protoreflect.FileDescriptor

var file_MonsterGuestBanDrop_proto_rawDesc = []byte{
	0x0a, 0x19, 0x4d, 0x6f, 0x6e, 0x73, 0x74, 0x65, 0x72, 0x47, 0x75, 0x65, 0x73, 0x74, 0x42, 0x61,
	0x6e, 0x44, 0x72, 0x6f, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2a, 0xf3, 0x01, 0x0a, 0x13,
	0x4d, 0x6f, 0x6e, 0x73, 0x74, 0x65, 0x72, 0x47, 0x75, 0x65, 0x73, 0x74, 0x42, 0x61, 0x6e, 0x44,
	0x72, 0x6f, 0x70, 0x12, 0x1a, 0x0a, 0x16, 0x4d, 0x4f, 0x4e, 0x53, 0x54, 0x45, 0x52, 0x5f, 0x47,
	0x55, 0x45, 0x53, 0x54, 0x5f, 0x42, 0x41, 0x4e, 0x5f, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12,
	0x1d, 0x0a, 0x19, 0x4d, 0x4f, 0x4e, 0x53, 0x54, 0x45, 0x52, 0x5f, 0x47, 0x55, 0x45, 0x53, 0x54,
	0x5f, 0x42, 0x41, 0x4e, 0x5f, 0x44, 0x49, 0x45, 0x5f, 0x45, 0x58, 0x50, 0x10, 0x01, 0x12, 0x1d,
	0x0a, 0x19, 0x4d, 0x4f, 0x4e, 0x53, 0x54, 0x45, 0x52, 0x5f, 0x47, 0x55, 0x45, 0x53, 0x54, 0x5f,
	0x42, 0x41, 0x4e, 0x5f, 0x44, 0x49, 0x45, 0x5f, 0x4c, 0x55, 0x41, 0x10, 0x02, 0x12, 0x1f, 0x0a,
	0x1b, 0x4d, 0x4f, 0x4e, 0x53, 0x54, 0x45, 0x52, 0x5f, 0x47, 0x55, 0x45, 0x53, 0x54, 0x5f, 0x42,
	0x41, 0x4e, 0x5f, 0x44, 0x49, 0x45, 0x5f, 0x45, 0x58, 0x43, 0x45, 0x4c, 0x10, 0x04, 0x12, 0x22,
	0x0a, 0x1e, 0x4d, 0x4f, 0x4e, 0x53, 0x54, 0x45, 0x52, 0x5f, 0x47, 0x55, 0x45, 0x53, 0x54, 0x5f,
	0x42, 0x41, 0x4e, 0x5f, 0x44, 0x49, 0x45, 0x5f, 0x41, 0x43, 0x54, 0x49, 0x56, 0x49, 0x54, 0x59,
	0x10, 0x08, 0x12, 0x1d, 0x0a, 0x19, 0x4d, 0x4f, 0x4e, 0x53, 0x54, 0x45, 0x52, 0x5f, 0x47, 0x55,
	0x45, 0x53, 0x54, 0x5f, 0x42, 0x41, 0x4e, 0x5f, 0x44, 0x52, 0x4f, 0x50, 0x5f, 0x48, 0x50, 0x10,
	0x10, 0x12, 0x1e, 0x0a, 0x1a, 0x4d, 0x4f, 0x4e, 0x53, 0x54, 0x45, 0x52, 0x5f, 0x47, 0x55, 0x45,
	0x53, 0x54, 0x5f, 0x42, 0x41, 0x4e, 0x5f, 0x53, 0x55, 0x42, 0x46, 0x49, 0x45, 0x4c, 0x44, 0x10,
	0x20, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_MonsterGuestBanDrop_proto_rawDescOnce sync.Once
	file_MonsterGuestBanDrop_proto_rawDescData = file_MonsterGuestBanDrop_proto_rawDesc
)

func file_MonsterGuestBanDrop_proto_rawDescGZIP() []byte {
	file_MonsterGuestBanDrop_proto_rawDescOnce.Do(func() {
		file_MonsterGuestBanDrop_proto_rawDescData = protoimpl.X.CompressGZIP(file_MonsterGuestBanDrop_proto_rawDescData)
	})
	return file_MonsterGuestBanDrop_proto_rawDescData
}

var file_MonsterGuestBanDrop_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_MonsterGuestBanDrop_proto_goTypes = []interface{}{
	(MonsterGuestBanDrop)(0), // 0: MonsterGuestBanDrop
}
var file_MonsterGuestBanDrop_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_MonsterGuestBanDrop_proto_init() }
func file_MonsterGuestBanDrop_proto_init() {
	if File_MonsterGuestBanDrop_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_MonsterGuestBanDrop_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_MonsterGuestBanDrop_proto_goTypes,
		DependencyIndexes: file_MonsterGuestBanDrop_proto_depIdxs,
		EnumInfos:         file_MonsterGuestBanDrop_proto_enumTypes,
	}.Build()
	File_MonsterGuestBanDrop_proto = out.File
	file_MonsterGuestBanDrop_proto_rawDesc = nil
	file_MonsterGuestBanDrop_proto_goTypes = nil
	file_MonsterGuestBanDrop_proto_depIdxs = nil
}
