// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.4.0
// source: PlatformRouteStateNotify.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlatformRouteStateNotify_CmdId int32

const (
	PlatformRouteStateNotify_NONE             PlatformRouteStateNotify_CmdId = 0
	PlatformRouteStateNotify_CMD_ID           PlatformRouteStateNotify_CmdId = 3004
	PlatformRouteStateNotify_ENET_CHANNEL_ID  PlatformRouteStateNotify_CmdId = 0
	PlatformRouteStateNotify_ENET_IS_RELIABLE PlatformRouteStateNotify_CmdId = 1
	PlatformRouteStateNotify_IS_ALLOW_CLIENT  PlatformRouteStateNotify_CmdId = 1
)

// Enum value maps for PlatformRouteStateNotify_CmdId.
var (
	PlatformRouteStateNotify_CmdId_name = map[int32]string{
		0:    "NONE",
		3004: "CMD_ID",
		// Duplicate value: 0: "ENET_CHANNEL_ID",
		1: "ENET_IS_RELIABLE",
		// Duplicate value: 1: "IS_ALLOW_CLIENT",
	}
	PlatformRouteStateNotify_CmdId_value = map[string]int32{
		"NONE":             0,
		"CMD_ID":           3004,
		"ENET_CHANNEL_ID":  0,
		"ENET_IS_RELIABLE": 1,
		"IS_ALLOW_CLIENT":  1,
	}
)

func (x PlatformRouteStateNotify_CmdId) Enum() *PlatformRouteStateNotify_CmdId {
	p := new(PlatformRouteStateNotify_CmdId)
	*p = x
	return p
}

func (x PlatformRouteStateNotify_CmdId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlatformRouteStateNotify_CmdId) Descriptor() protoreflect.EnumDescriptor {
	return file_PlatformRouteStateNotify_proto_enumTypes[0].Descriptor()
}

func (PlatformRouteStateNotify_CmdId) Type() protoreflect.EnumType {
	return &file_PlatformRouteStateNotify_proto_enumTypes[0]
}

func (x PlatformRouteStateNotify_CmdId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlatformRouteStateNotify_CmdId.Descriptor instead.
func (PlatformRouteStateNotify_CmdId) EnumDescriptor() ([]byte, []int) {
	return file_PlatformRouteStateNotify_proto_rawDescGZIP(), []int{0, 0}
}

type PlatformRouteStateNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EntityId  uint32  `protobuf:"varint,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	SceneTime uint32  `protobuf:"varint,2,opt,name=scene_time,json=sceneTime,proto3" json:"scene_time,omitempty"`
	Pos       *Vector `protobuf:"bytes,3,opt,name=pos,proto3" json:"pos,omitempty"`
	Rot       *Vector `protobuf:"bytes,4,opt,name=rot,proto3" json:"rot,omitempty"`
	RouteId   uint32  `protobuf:"varint,5,opt,name=route_id,json=routeId,proto3" json:"route_id,omitempty"`
	IsStarted bool    `protobuf:"varint,6,opt,name=is_started,json=isStarted,proto3" json:"is_started,omitempty"`
}

func (x *PlatformRouteStateNotify) Reset() {
	*x = PlatformRouteStateNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_PlatformRouteStateNotify_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlatformRouteStateNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlatformRouteStateNotify) ProtoMessage() {}

func (x *PlatformRouteStateNotify) ProtoReflect() protoreflect.Message {
	mi := &file_PlatformRouteStateNotify_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlatformRouteStateNotify.ProtoReflect.Descriptor instead.
func (*PlatformRouteStateNotify) Descriptor() ([]byte, []int) {
	return file_PlatformRouteStateNotify_proto_rawDescGZIP(), []int{0}
}

func (x *PlatformRouteStateNotify) GetEntityId() uint32 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *PlatformRouteStateNotify) GetSceneTime() uint32 {
	if x != nil {
		return x.SceneTime
	}
	return 0
}

func (x *PlatformRouteStateNotify) GetPos() *Vector {
	if x != nil {
		return x.Pos
	}
	return nil
}

func (x *PlatformRouteStateNotify) GetRot() *Vector {
	if x != nil {
		return x.Rot
	}
	return nil
}

func (x *PlatformRouteStateNotify) GetRouteId() uint32 {
	if x != nil {
		return x.RouteId
	}
	return 0
}

func (x *PlatformRouteStateNotify) GetIsStarted() bool {
	if x != nil {
		return x.IsStarted
	}
	return false
}

var File_PlatformRouteStateNotify_proto protoreflect.FileDescriptor

var file_PlatformRouteStateNotify_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x0c, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xaa,
	0x02, 0x0a, 0x18, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x52, 0x6f, 0x75, 0x74, 0x65,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x1b, 0x0a, 0x09, 0x65,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08,
	0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x63, 0x65, 0x6e,
	0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x73, 0x63,
	0x65, 0x6e, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x03, 0x70, 0x6f, 0x73, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x03, 0x70,
	0x6f, 0x73, 0x12, 0x19, 0x0a, 0x03, 0x72, 0x6f, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x07, 0x2e, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x03, 0x72, 0x6f, 0x74, 0x12, 0x19, 0x0a,
	0x08, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x07, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x73, 0x5f, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x69, 0x73,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x22, 0x62, 0x0a, 0x05, 0x43, 0x6d, 0x64, 0x49, 0x64,
	0x12, 0x08, 0x0a, 0x04, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x06, 0x43, 0x4d,
	0x44, 0x5f, 0x49, 0x44, 0x10, 0xbc, 0x17, 0x12, 0x13, 0x0a, 0x0f, 0x45, 0x4e, 0x45, 0x54, 0x5f,
	0x43, 0x48, 0x41, 0x4e, 0x4e, 0x45, 0x4c, 0x5f, 0x49, 0x44, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10,
	0x45, 0x4e, 0x45, 0x54, 0x5f, 0x49, 0x53, 0x5f, 0x52, 0x45, 0x4c, 0x49, 0x41, 0x42, 0x4c, 0x45,
	0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f, 0x49, 0x53, 0x5f, 0x41, 0x4c, 0x4c, 0x4f, 0x57, 0x5f, 0x43,
	0x4c, 0x49, 0x45, 0x4e, 0x54, 0x10, 0x01, 0x1a, 0x02, 0x10, 0x01, 0x42, 0x0a, 0x5a, 0x08, 0x2e,
	0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_PlatformRouteStateNotify_proto_rawDescOnce sync.Once
	file_PlatformRouteStateNotify_proto_rawDescData = file_PlatformRouteStateNotify_proto_rawDesc
)

func file_PlatformRouteStateNotify_proto_rawDescGZIP() []byte {
	file_PlatformRouteStateNotify_proto_rawDescOnce.Do(func() {
		file_PlatformRouteStateNotify_proto_rawDescData = protoimpl.X.CompressGZIP(file_PlatformRouteStateNotify_proto_rawDescData)
	})
	return file_PlatformRouteStateNotify_proto_rawDescData
}

var file_PlatformRouteStateNotify_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_PlatformRouteStateNotify_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_PlatformRouteStateNotify_proto_goTypes = []interface{}{
	(PlatformRouteStateNotify_CmdId)(0), // 0: PlatformRouteStateNotify.CmdId
	(*PlatformRouteStateNotify)(nil),    // 1: PlatformRouteStateNotify
	(*Vector)(nil),                      // 2: Vector
}
var file_PlatformRouteStateNotify_proto_depIdxs = []int32{
	2, // 0: PlatformRouteStateNotify.pos:type_name -> Vector
	2, // 1: PlatformRouteStateNotify.rot:type_name -> Vector
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_PlatformRouteStateNotify_proto_init() }
func file_PlatformRouteStateNotify_proto_init() {
	if File_PlatformRouteStateNotify_proto != nil {
		return
	}
	file_Vector_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_PlatformRouteStateNotify_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlatformRouteStateNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_PlatformRouteStateNotify_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_PlatformRouteStateNotify_proto_goTypes,
		DependencyIndexes: file_PlatformRouteStateNotify_proto_depIdxs,
		EnumInfos:         file_PlatformRouteStateNotify_proto_enumTypes,
		MessageInfos:      file_PlatformRouteStateNotify_proto_msgTypes,
	}.Build()
	File_PlatformRouteStateNotify_proto = out.File
	file_PlatformRouteStateNotify_proto_rawDesc = nil
	file_PlatformRouteStateNotify_proto_goTypes = nil
	file_PlatformRouteStateNotify_proto_depIdxs = nil
}
