// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.4.0
// source: PlayerSetOnlyMPWithPSPlayerReq.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlayerSetOnlyMPWithPSPlayerReq_CmdId int32

const (
	PlayerSetOnlyMPWithPSPlayerReq_NONE             PlayerSetOnlyMPWithPSPlayerReq_CmdId = 0
	PlayerSetOnlyMPWithPSPlayerReq_CMD_ID           PlayerSetOnlyMPWithPSPlayerReq_CmdId = 1811
	PlayerSetOnlyMPWithPSPlayerReq_ENET_CHANNEL_ID  PlayerSetOnlyMPWithPSPlayerReq_CmdId = 0
	PlayerSetOnlyMPWithPSPlayerReq_ENET_IS_RELIABLE PlayerSetOnlyMPWithPSPlayerReq_CmdId = 1
	PlayerSetOnlyMPWithPSPlayerReq_IS_ALLOW_CLIENT  PlayerSetOnlyMPWithPSPlayerReq_CmdId = 1
)

// Enum value maps for PlayerSetOnlyMPWithPSPlayerReq_CmdId.
var (
	PlayerSetOnlyMPWithPSPlayerReq_CmdId_name = map[int32]string{
		0:    "NONE",
		1811: "CMD_ID",
		// Duplicate value: 0: "ENET_CHANNEL_ID",
		1: "ENET_IS_RELIABLE",
		// Duplicate value: 1: "IS_ALLOW_CLIENT",
	}
	PlayerSetOnlyMPWithPSPlayerReq_CmdId_value = map[string]int32{
		"NONE":             0,
		"CMD_ID":           1811,
		"ENET_CHANNEL_ID":  0,
		"ENET_IS_RELIABLE": 1,
		"IS_ALLOW_CLIENT":  1,
	}
)

func (x PlayerSetOnlyMPWithPSPlayerReq_CmdId) Enum() *PlayerSetOnlyMPWithPSPlayerReq_CmdId {
	p := new(PlayerSetOnlyMPWithPSPlayerReq_CmdId)
	*p = x
	return p
}

func (x PlayerSetOnlyMPWithPSPlayerReq_CmdId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlayerSetOnlyMPWithPSPlayerReq_CmdId) Descriptor() protoreflect.EnumDescriptor {
	return file_PlayerSetOnlyMPWithPSPlayerReq_proto_enumTypes[0].Descriptor()
}

func (PlayerSetOnlyMPWithPSPlayerReq_CmdId) Type() protoreflect.EnumType {
	return &file_PlayerSetOnlyMPWithPSPlayerReq_proto_enumTypes[0]
}

func (x PlayerSetOnlyMPWithPSPlayerReq_CmdId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlayerSetOnlyMPWithPSPlayerReq_CmdId.Descriptor instead.
func (PlayerSetOnlyMPWithPSPlayerReq_CmdId) EnumDescriptor() ([]byte, []int) {
	return file_PlayerSetOnlyMPWithPSPlayerReq_proto_rawDescGZIP(), []int{0, 0}
}

type PlayerSetOnlyMPWithPSPlayerReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsOnly bool `protobuf:"varint,1,opt,name=is_only,json=isOnly,proto3" json:"is_only,omitempty"`
}

func (x *PlayerSetOnlyMPWithPSPlayerReq) Reset() {
	*x = PlayerSetOnlyMPWithPSPlayerReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_PlayerSetOnlyMPWithPSPlayerReq_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerSetOnlyMPWithPSPlayerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerSetOnlyMPWithPSPlayerReq) ProtoMessage() {}

func (x *PlayerSetOnlyMPWithPSPlayerReq) ProtoReflect() protoreflect.Message {
	mi := &file_PlayerSetOnlyMPWithPSPlayerReq_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerSetOnlyMPWithPSPlayerReq.ProtoReflect.Descriptor instead.
func (*PlayerSetOnlyMPWithPSPlayerReq) Descriptor() ([]byte, []int) {
	return file_PlayerSetOnlyMPWithPSPlayerReq_proto_rawDescGZIP(), []int{0}
}

func (x *PlayerSetOnlyMPWithPSPlayerReq) GetIsOnly() bool {
	if x != nil {
		return x.IsOnly
	}
	return false
}

var File_PlayerSetOnlyMPWithPSPlayerReq_proto protoreflect.FileDescriptor

var file_PlayerSetOnlyMPWithPSPlayerReq_proto_rawDesc = []byte{
	0x0a, 0x24, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x53, 0x65, 0x74, 0x4f, 0x6e, 0x6c, 0x79, 0x4d,
	0x50, 0x57, 0x69, 0x74, 0x68, 0x50, 0x53, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x9d, 0x01,
	0x0a, 0x1e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x53, 0x65, 0x74, 0x4f, 0x6e, 0x6c, 0x79, 0x4d,
	0x50, 0x57, 0x69, 0x74, 0x68, 0x50, 0x53, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x12, 0x17, 0x0a, 0x07, 0x69, 0x73, 0x5f, 0x6f, 0x6e, 0x6c, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x06, 0x69, 0x73, 0x4f, 0x6e, 0x6c, 0x79, 0x22, 0x62, 0x0a, 0x05, 0x43, 0x6d, 0x64,
	0x49, 0x64, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x06,
	0x43, 0x4d, 0x44, 0x5f, 0x49, 0x44, 0x10, 0x93, 0x0e, 0x12, 0x13, 0x0a, 0x0f, 0x45, 0x4e, 0x45,
	0x54, 0x5f, 0x43, 0x48, 0x41, 0x4e, 0x4e, 0x45, 0x4c, 0x5f, 0x49, 0x44, 0x10, 0x00, 0x12, 0x14,
	0x0a, 0x10, 0x45, 0x4e, 0x45, 0x54, 0x5f, 0x49, 0x53, 0x5f, 0x52, 0x45, 0x4c, 0x49, 0x41, 0x42,
	0x4c, 0x45, 0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f, 0x49, 0x53, 0x5f, 0x41, 0x4c, 0x4c, 0x4f, 0x57,
	0x5f, 0x43, 0x4c, 0x49, 0x45, 0x4e, 0x54, 0x10, 0x01, 0x1a, 0x02, 0x10, 0x01, 0x42, 0x0a, 0x5a,
	0x08, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_PlayerSetOnlyMPWithPSPlayerReq_proto_rawDescOnce sync.Once
	file_PlayerSetOnlyMPWithPSPlayerReq_proto_rawDescData = file_PlayerSetOnlyMPWithPSPlayerReq_proto_rawDesc
)

func file_PlayerSetOnlyMPWithPSPlayerReq_proto_rawDescGZIP() []byte {
	file_PlayerSetOnlyMPWithPSPlayerReq_proto_rawDescOnce.Do(func() {
		file_PlayerSetOnlyMPWithPSPlayerReq_proto_rawDescData = protoimpl.X.CompressGZIP(file_PlayerSetOnlyMPWithPSPlayerReq_proto_rawDescData)
	})
	return file_PlayerSetOnlyMPWithPSPlayerReq_proto_rawDescData
}

var file_PlayerSetOnlyMPWithPSPlayerReq_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_PlayerSetOnlyMPWithPSPlayerReq_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_PlayerSetOnlyMPWithPSPlayerReq_proto_goTypes = []interface{}{
	(PlayerSetOnlyMPWithPSPlayerReq_CmdId)(0), // 0: proto.PlayerSetOnlyMPWithPSPlayerReq.CmdId
	(*PlayerSetOnlyMPWithPSPlayerReq)(nil),    // 1: proto.PlayerSetOnlyMPWithPSPlayerReq
}
var file_PlayerSetOnlyMPWithPSPlayerReq_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_PlayerSetOnlyMPWithPSPlayerReq_proto_init() }
func file_PlayerSetOnlyMPWithPSPlayerReq_proto_init() {
	if File_PlayerSetOnlyMPWithPSPlayerReq_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_PlayerSetOnlyMPWithPSPlayerReq_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerSetOnlyMPWithPSPlayerReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_PlayerSetOnlyMPWithPSPlayerReq_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_PlayerSetOnlyMPWithPSPlayerReq_proto_goTypes,
		DependencyIndexes: file_PlayerSetOnlyMPWithPSPlayerReq_proto_depIdxs,
		EnumInfos:         file_PlayerSetOnlyMPWithPSPlayerReq_proto_enumTypes,
		MessageInfos:      file_PlayerSetOnlyMPWithPSPlayerReq_proto_msgTypes,
	}.Build()
	File_PlayerSetOnlyMPWithPSPlayerReq_proto = out.File
	file_PlayerSetOnlyMPWithPSPlayerReq_proto_rawDesc = nil
	file_PlayerSetOnlyMPWithPSPlayerReq_proto_goTypes = nil
	file_PlayerSetOnlyMPWithPSPlayerReq_proto_depIdxs = nil
}
