// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.4.0
// source: PlayerInvestigationAllInfoNotify.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlayerInvestigationAllInfoNotify_CmdId int32

const (
	PlayerInvestigationAllInfoNotify_NONE             PlayerInvestigationAllInfoNotify_CmdId = 0
	PlayerInvestigationAllInfoNotify_CMD_ID           PlayerInvestigationAllInfoNotify_CmdId = 1901
	PlayerInvestigationAllInfoNotify_ENET_CHANNEL_ID  PlayerInvestigationAllInfoNotify_CmdId = 0
	PlayerInvestigationAllInfoNotify_ENET_IS_RELIABLE PlayerInvestigationAllInfoNotify_CmdId = 1
)

// Enum value maps for PlayerInvestigationAllInfoNotify_CmdId.
var (
	PlayerInvestigationAllInfoNotify_CmdId_name = map[int32]string{
		0:    "NONE",
		1901: "CMD_ID",
		// Duplicate value: 0: "ENET_CHANNEL_ID",
		1: "ENET_IS_RELIABLE",
	}
	PlayerInvestigationAllInfoNotify_CmdId_value = map[string]int32{
		"NONE":             0,
		"CMD_ID":           1901,
		"ENET_CHANNEL_ID":  0,
		"ENET_IS_RELIABLE": 1,
	}
)

func (x PlayerInvestigationAllInfoNotify_CmdId) Enum() *PlayerInvestigationAllInfoNotify_CmdId {
	p := new(PlayerInvestigationAllInfoNotify_CmdId)
	*p = x
	return p
}

func (x PlayerInvestigationAllInfoNotify_CmdId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlayerInvestigationAllInfoNotify_CmdId) Descriptor() protoreflect.EnumDescriptor {
	return file_PlayerInvestigationAllInfoNotify_proto_enumTypes[0].Descriptor()
}

func (PlayerInvestigationAllInfoNotify_CmdId) Type() protoreflect.EnumType {
	return &file_PlayerInvestigationAllInfoNotify_proto_enumTypes[0]
}

func (x PlayerInvestigationAllInfoNotify_CmdId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlayerInvestigationAllInfoNotify_CmdId.Descriptor instead.
func (PlayerInvestigationAllInfoNotify_CmdId) EnumDescriptor() ([]byte, []int) {
	return file_PlayerInvestigationAllInfoNotify_proto_rawDescGZIP(), []int{0, 0}
}

type PlayerInvestigationAllInfoNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InvestigationList       []*Investigation       `protobuf:"bytes,1,rep,name=investigation_list,json=investigationList,proto3" json:"investigation_list,omitempty"`
	InvestigationTargetList []*InvestigationTarget `protobuf:"bytes,2,rep,name=investigation_target_list,json=investigationTargetList,proto3" json:"investigation_target_list,omitempty"`
}

func (x *PlayerInvestigationAllInfoNotify) Reset() {
	*x = PlayerInvestigationAllInfoNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_PlayerInvestigationAllInfoNotify_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerInvestigationAllInfoNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerInvestigationAllInfoNotify) ProtoMessage() {}

func (x *PlayerInvestigationAllInfoNotify) ProtoReflect() protoreflect.Message {
	mi := &file_PlayerInvestigationAllInfoNotify_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerInvestigationAllInfoNotify.ProtoReflect.Descriptor instead.
func (*PlayerInvestigationAllInfoNotify) Descriptor() ([]byte, []int) {
	return file_PlayerInvestigationAllInfoNotify_proto_rawDescGZIP(), []int{0}
}

func (x *PlayerInvestigationAllInfoNotify) GetInvestigationList() []*Investigation {
	if x != nil {
		return x.InvestigationList
	}
	return nil
}

func (x *PlayerInvestigationAllInfoNotify) GetInvestigationTargetList() []*InvestigationTarget {
	if x != nil {
		return x.InvestigationTargetList
	}
	return nil
}

var File_PlayerInvestigationAllInfoNotify_proto protoreflect.FileDescriptor

var file_PlayerInvestigationAllInfoNotify_proto_rawDesc = []byte{
	0x0a, 0x26, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x76, 0x65, 0x73, 0x74, 0x69, 0x67,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x6c, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x4e, 0x6f, 0x74, 0x69,
	0x66, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x13, 0x49, 0x6e, 0x76, 0x65, 0x73, 0x74, 0x69, 0x67, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x49, 0x6e, 0x76, 0x65, 0x73, 0x74, 0x69, 0x67, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x8e, 0x02, 0x0a, 0x20, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x76, 0x65, 0x73, 0x74,
	0x69, 0x67, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x6c, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x4e, 0x6f,
	0x74, 0x69, 0x66, 0x79, 0x12, 0x43, 0x0a, 0x12, 0x69, 0x6e, 0x76, 0x65, 0x73, 0x74, 0x69, 0x67,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x49, 0x6e, 0x76, 0x65, 0x73, 0x74, 0x69,
	0x67, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x11, 0x69, 0x6e, 0x76, 0x65, 0x73, 0x74, 0x69, 0x67,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x56, 0x0a, 0x19, 0x69, 0x6e, 0x76,
	0x65, 0x73, 0x74, 0x69, 0x67, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x61, 0x72, 0x67, 0x65,
	0x74, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x49, 0x6e, 0x76, 0x65, 0x73, 0x74, 0x69, 0x67, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x52, 0x17, 0x69, 0x6e, 0x76, 0x65, 0x73, 0x74,
	0x69, 0x67, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x4c, 0x69, 0x73,
	0x74, 0x22, 0x4d, 0x0a, 0x05, 0x43, 0x6d, 0x64, 0x49, 0x64, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x4f,
	0x4e, 0x45, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x06, 0x43, 0x4d, 0x44, 0x5f, 0x49, 0x44, 0x10, 0xed,
	0x0e, 0x12, 0x13, 0x0a, 0x0f, 0x45, 0x4e, 0x45, 0x54, 0x5f, 0x43, 0x48, 0x41, 0x4e, 0x4e, 0x45,
	0x4c, 0x5f, 0x49, 0x44, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x45, 0x4e, 0x45, 0x54, 0x5f, 0x49,
	0x53, 0x5f, 0x52, 0x45, 0x4c, 0x49, 0x41, 0x42, 0x4c, 0x45, 0x10, 0x01, 0x1a, 0x02, 0x10, 0x01,
	0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_PlayerInvestigationAllInfoNotify_proto_rawDescOnce sync.Once
	file_PlayerInvestigationAllInfoNotify_proto_rawDescData = file_PlayerInvestigationAllInfoNotify_proto_rawDesc
)

func file_PlayerInvestigationAllInfoNotify_proto_rawDescGZIP() []byte {
	file_PlayerInvestigationAllInfoNotify_proto_rawDescOnce.Do(func() {
		file_PlayerInvestigationAllInfoNotify_proto_rawDescData = protoimpl.X.CompressGZIP(file_PlayerInvestigationAllInfoNotify_proto_rawDescData)
	})
	return file_PlayerInvestigationAllInfoNotify_proto_rawDescData
}

var file_PlayerInvestigationAllInfoNotify_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_PlayerInvestigationAllInfoNotify_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_PlayerInvestigationAllInfoNotify_proto_goTypes = []interface{}{
	(PlayerInvestigationAllInfoNotify_CmdId)(0), // 0: proto.PlayerInvestigationAllInfoNotify.CmdId
	(*PlayerInvestigationAllInfoNotify)(nil),    // 1: proto.PlayerInvestigationAllInfoNotify
	(*Investigation)(nil),                       // 2: proto.Investigation
	(*InvestigationTarget)(nil),                 // 3: proto.InvestigationTarget
}
var file_PlayerInvestigationAllInfoNotify_proto_depIdxs = []int32{
	2, // 0: proto.PlayerInvestigationAllInfoNotify.investigation_list:type_name -> proto.Investigation
	3, // 1: proto.PlayerInvestigationAllInfoNotify.investigation_target_list:type_name -> proto.InvestigationTarget
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_PlayerInvestigationAllInfoNotify_proto_init() }
func file_PlayerInvestigationAllInfoNotify_proto_init() {
	if File_PlayerInvestigationAllInfoNotify_proto != nil {
		return
	}
	file_Investigation_proto_init()
	file_InvestigationTarget_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_PlayerInvestigationAllInfoNotify_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerInvestigationAllInfoNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_PlayerInvestigationAllInfoNotify_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_PlayerInvestigationAllInfoNotify_proto_goTypes,
		DependencyIndexes: file_PlayerInvestigationAllInfoNotify_proto_depIdxs,
		EnumInfos:         file_PlayerInvestigationAllInfoNotify_proto_enumTypes,
		MessageInfos:      file_PlayerInvestigationAllInfoNotify_proto_msgTypes,
	}.Build()
	File_PlayerInvestigationAllInfoNotify_proto = out.File
	file_PlayerInvestigationAllInfoNotify_proto_rawDesc = nil
	file_PlayerInvestigationAllInfoNotify_proto_goTypes = nil
	file_PlayerInvestigationAllInfoNotify_proto_depIdxs = nil
}
