// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.4.0
// source: PlayerLogoutReq.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlayerLogoutReq_Reason int32

const (
	PlayerLogoutReq_DISCONNECT              PlayerLogoutReq_Reason = 0
	PlayerLogoutReq_CLIENT_REQ              PlayerLogoutReq_Reason = 1
	PlayerLogoutReq_TIMEOUT                 PlayerLogoutReq_Reason = 2
	PlayerLogoutReq_ADMIN_REQ               PlayerLogoutReq_Reason = 3
	PlayerLogoutReq_SERVER_CLOSE            PlayerLogoutReq_Reason = 4
	PlayerLogoutReq_GM_CLEAR                PlayerLogoutReq_Reason = 5
	PlayerLogoutReq_PLAYER_TRANSFER         PlayerLogoutReq_Reason = 6
	PlayerLogoutReq_CLIENT_CHECKSUM_INVALID PlayerLogoutReq_Reason = 7
)

// Enum value maps for PlayerLogoutReq_Reason.
var (
	PlayerLogoutReq_Reason_name = map[int32]string{
		0: "DISCONNECT",
		1: "CLIENT_REQ",
		2: "TIMEOUT",
		3: "ADMIN_REQ",
		4: "SERVER_CLOSE",
		5: "GM_CLEAR",
		6: "PLAYER_TRANSFER",
		7: "CLIENT_CHECKSUM_INVALID",
	}
	PlayerLogoutReq_Reason_value = map[string]int32{
		"DISCONNECT":              0,
		"CLIENT_REQ":              1,
		"TIMEOUT":                 2,
		"ADMIN_REQ":               3,
		"SERVER_CLOSE":            4,
		"GM_CLEAR":                5,
		"PLAYER_TRANSFER":         6,
		"CLIENT_CHECKSUM_INVALID": 7,
	}
)

func (x PlayerLogoutReq_Reason) Enum() *PlayerLogoutReq_Reason {
	p := new(PlayerLogoutReq_Reason)
	*p = x
	return p
}

func (x PlayerLogoutReq_Reason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlayerLogoutReq_Reason) Descriptor() protoreflect.EnumDescriptor {
	return file_PlayerLogoutReq_proto_enumTypes[0].Descriptor()
}

func (PlayerLogoutReq_Reason) Type() protoreflect.EnumType {
	return &file_PlayerLogoutReq_proto_enumTypes[0]
}

func (x PlayerLogoutReq_Reason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlayerLogoutReq_Reason.Descriptor instead.
func (PlayerLogoutReq_Reason) EnumDescriptor() ([]byte, []int) {
	return file_PlayerLogoutReq_proto_rawDescGZIP(), []int{0, 0}
}

type PlayerLogoutReq_CmdId int32

const (
	PlayerLogoutReq_NONE             PlayerLogoutReq_CmdId = 0
	PlayerLogoutReq_CMD_ID           PlayerLogoutReq_CmdId = 105
	PlayerLogoutReq_ENET_CHANNEL_ID  PlayerLogoutReq_CmdId = 0
	PlayerLogoutReq_ENET_IS_RELIABLE PlayerLogoutReq_CmdId = 1
	PlayerLogoutReq_IS_ALLOW_CLIENT  PlayerLogoutReq_CmdId = 1
)

// Enum value maps for PlayerLogoutReq_CmdId.
var (
	PlayerLogoutReq_CmdId_name = map[int32]string{
		0:   "NONE",
		105: "CMD_ID",
		// Duplicate value: 0: "ENET_CHANNEL_ID",
		1: "ENET_IS_RELIABLE",
		// Duplicate value: 1: "IS_ALLOW_CLIENT",
	}
	PlayerLogoutReq_CmdId_value = map[string]int32{
		"NONE":             0,
		"CMD_ID":           105,
		"ENET_CHANNEL_ID":  0,
		"ENET_IS_RELIABLE": 1,
		"IS_ALLOW_CLIENT":  1,
	}
)

func (x PlayerLogoutReq_CmdId) Enum() *PlayerLogoutReq_CmdId {
	p := new(PlayerLogoutReq_CmdId)
	*p = x
	return p
}

func (x PlayerLogoutReq_CmdId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlayerLogoutReq_CmdId) Descriptor() protoreflect.EnumDescriptor {
	return file_PlayerLogoutReq_proto_enumTypes[1].Descriptor()
}

func (PlayerLogoutReq_CmdId) Type() protoreflect.EnumType {
	return &file_PlayerLogoutReq_proto_enumTypes[1]
}

func (x PlayerLogoutReq_CmdId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlayerLogoutReq_CmdId.Descriptor instead.
func (PlayerLogoutReq_CmdId) EnumDescriptor() ([]byte, []int) {
	return file_PlayerLogoutReq_proto_rawDescGZIP(), []int{0, 1}
}

type PlayerLogoutReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reason PlayerLogoutReq_Reason `protobuf:"varint,1,opt,name=reason,proto3,enum=proto.PlayerLogoutReq_Reason" json:"reason,omitempty"`
}

func (x *PlayerLogoutReq) Reset() {
	*x = PlayerLogoutReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_PlayerLogoutReq_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerLogoutReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerLogoutReq) ProtoMessage() {}

func (x *PlayerLogoutReq) ProtoReflect() protoreflect.Message {
	mi := &file_PlayerLogoutReq_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerLogoutReq.ProtoReflect.Descriptor instead.
func (*PlayerLogoutReq) Descriptor() ([]byte, []int) {
	return file_PlayerLogoutReq_proto_rawDescGZIP(), []int{0}
}

func (x *PlayerLogoutReq) GetReason() PlayerLogoutReq_Reason {
	if x != nil {
		return x.Reason
	}
	return PlayerLogoutReq_DISCONNECT
}

var File_PlayerLogoutReq_proto protoreflect.FileDescriptor

var file_PlayerLogoutReq_proto_rawDesc = []byte{
	0x0a, 0x15, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x52, 0x65,
	0x71, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc4,
	0x02, 0x0a, 0x0f, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x52,
	0x65, 0x71, 0x12, 0x35, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x4c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x52, 0x65, 0x71, 0x2e, 0x52, 0x65, 0x61, 0x73, 0x6f,
	0x6e, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22, 0x96, 0x01, 0x0a, 0x06, 0x52, 0x65,
	0x61, 0x73, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x0a, 0x44, 0x49, 0x53, 0x43, 0x4f, 0x4e, 0x4e, 0x45,
	0x43, 0x54, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x43, 0x4c, 0x49, 0x45, 0x4e, 0x54, 0x5f, 0x52,
	0x45, 0x51, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x54, 0x49, 0x4d, 0x45, 0x4f, 0x55, 0x54, 0x10,
	0x02, 0x12, 0x0d, 0x0a, 0x09, 0x41, 0x44, 0x4d, 0x49, 0x4e, 0x5f, 0x52, 0x45, 0x51, 0x10, 0x03,
	0x12, 0x10, 0x0a, 0x0c, 0x53, 0x45, 0x52, 0x56, 0x45, 0x52, 0x5f, 0x43, 0x4c, 0x4f, 0x53, 0x45,
	0x10, 0x04, 0x12, 0x0c, 0x0a, 0x08, 0x47, 0x4d, 0x5f, 0x43, 0x4c, 0x45, 0x41, 0x52, 0x10, 0x05,
	0x12, 0x13, 0x0a, 0x0f, 0x50, 0x4c, 0x41, 0x59, 0x45, 0x52, 0x5f, 0x54, 0x52, 0x41, 0x4e, 0x53,
	0x46, 0x45, 0x52, 0x10, 0x06, 0x12, 0x1b, 0x0a, 0x17, 0x43, 0x4c, 0x49, 0x45, 0x4e, 0x54, 0x5f,
	0x43, 0x48, 0x45, 0x43, 0x4b, 0x53, 0x55, 0x4d, 0x5f, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44,
	0x10, 0x07, 0x22, 0x61, 0x0a, 0x05, 0x43, 0x6d, 0x64, 0x49, 0x64, 0x12, 0x08, 0x0a, 0x04, 0x4e,
	0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x43, 0x4d, 0x44, 0x5f, 0x49, 0x44, 0x10,
	0x69, 0x12, 0x13, 0x0a, 0x0f, 0x45, 0x4e, 0x45, 0x54, 0x5f, 0x43, 0x48, 0x41, 0x4e, 0x4e, 0x45,
	0x4c, 0x5f, 0x49, 0x44, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x45, 0x4e, 0x45, 0x54, 0x5f, 0x49,
	0x53, 0x5f, 0x52, 0x45, 0x4c, 0x49, 0x41, 0x42, 0x4c, 0x45, 0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f,
	0x49, 0x53, 0x5f, 0x41, 0x4c, 0x4c, 0x4f, 0x57, 0x5f, 0x43, 0x4c, 0x49, 0x45, 0x4e, 0x54, 0x10,
	0x01, 0x1a, 0x02, 0x10, 0x01, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_PlayerLogoutReq_proto_rawDescOnce sync.Once
	file_PlayerLogoutReq_proto_rawDescData = file_PlayerLogoutReq_proto_rawDesc
)

func file_PlayerLogoutReq_proto_rawDescGZIP() []byte {
	file_PlayerLogoutReq_proto_rawDescOnce.Do(func() {
		file_PlayerLogoutReq_proto_rawDescData = protoimpl.X.CompressGZIP(file_PlayerLogoutReq_proto_rawDescData)
	})
	return file_PlayerLogoutReq_proto_rawDescData
}

var file_PlayerLogoutReq_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_PlayerLogoutReq_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_PlayerLogoutReq_proto_goTypes = []interface{}{
	(PlayerLogoutReq_Reason)(0), // 0: proto.PlayerLogoutReq.Reason
	(PlayerLogoutReq_CmdId)(0),  // 1: proto.PlayerLogoutReq.CmdId
	(*PlayerLogoutReq)(nil),     // 2: proto.PlayerLogoutReq
}
var file_PlayerLogoutReq_proto_depIdxs = []int32{
	0, // 0: proto.PlayerLogoutReq.reason:type_name -> proto.PlayerLogoutReq.Reason
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_PlayerLogoutReq_proto_init() }
func file_PlayerLogoutReq_proto_init() {
	if File_PlayerLogoutReq_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_PlayerLogoutReq_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerLogoutReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_PlayerLogoutReq_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_PlayerLogoutReq_proto_goTypes,
		DependencyIndexes: file_PlayerLogoutReq_proto_depIdxs,
		EnumInfos:         file_PlayerLogoutReq_proto_enumTypes,
		MessageInfos:      file_PlayerLogoutReq_proto_msgTypes,
	}.Build()
	File_PlayerLogoutReq_proto = out.File
	file_PlayerLogoutReq_proto_rawDesc = nil
	file_PlayerLogoutReq_proto_goTypes = nil
	file_PlayerLogoutReq_proto_depIdxs = nil
}
