// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.4.0
// source: PlayerCookRsp.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlayerCookRsp_CmdId int32

const (
	PlayerCookRsp_NONE             PlayerCookRsp_CmdId = 0
	PlayerCookRsp_CMD_ID           PlayerCookRsp_CmdId = 127
	PlayerCookRsp_ENET_CHANNEL_ID  PlayerCookRsp_CmdId = 0
	PlayerCookRsp_ENET_IS_RELIABLE PlayerCookRsp_CmdId = 1
)

// Enum value maps for PlayerCookRsp_CmdId.
var (
	PlayerCookRsp_CmdId_name = map[int32]string{
		0:   "NONE",
		127: "CMD_ID",
		// Duplicate value: 0: "ENET_CHANNEL_ID",
		1: "ENET_IS_RELIABLE",
	}
	PlayerCookRsp_CmdId_value = map[string]int32{
		"NONE":             0,
		"CMD_ID":           127,
		"ENET_CHANNEL_ID":  0,
		"ENET_IS_RELIABLE": 1,
	}
)

func (x PlayerCookRsp_CmdId) Enum() *PlayerCookRsp_CmdId {
	p := new(PlayerCookRsp_CmdId)
	*p = x
	return p
}

func (x PlayerCookRsp_CmdId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlayerCookRsp_CmdId) Descriptor() protoreflect.EnumDescriptor {
	return file_PlayerCookRsp_proto_enumTypes[0].Descriptor()
}

func (PlayerCookRsp_CmdId) Type() protoreflect.EnumType {
	return &file_PlayerCookRsp_proto_enumTypes[0]
}

func (x PlayerCookRsp_CmdId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlayerCookRsp_CmdId.Descriptor instead.
func (PlayerCookRsp_CmdId) EnumDescriptor() ([]byte, []int) {
	return file_PlayerCookRsp_proto_rawDescGZIP(), []int{0, 0}
}

type PlayerCookRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Retcode    uint32          `protobuf:"varint,1,opt,name=retcode,proto3" json:"retcode,omitempty"`
	RecipeData *CookRecipeData `protobuf:"bytes,2,opt,name=recipe_data,json=recipeData,proto3" json:"recipe_data,omitempty"`
	ItemList   []*ItemParam    `protobuf:"bytes,3,rep,name=item_list,json=itemList,proto3" json:"item_list,omitempty"`
	QteQuality uint32          `protobuf:"varint,4,opt,name=qte_quality,json=qteQuality,proto3" json:"qte_quality,omitempty"`
	CookCount  uint32          `protobuf:"varint,5,opt,name=cook_count,json=cookCount,proto3" json:"cook_count,omitempty"`
}

func (x *PlayerCookRsp) Reset() {
	*x = PlayerCookRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_PlayerCookRsp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerCookRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerCookRsp) ProtoMessage() {}

func (x *PlayerCookRsp) ProtoReflect() protoreflect.Message {
	mi := &file_PlayerCookRsp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerCookRsp.ProtoReflect.Descriptor instead.
func (*PlayerCookRsp) Descriptor() ([]byte, []int) {
	return file_PlayerCookRsp_proto_rawDescGZIP(), []int{0}
}

func (x *PlayerCookRsp) GetRetcode() uint32 {
	if x != nil {
		return x.Retcode
	}
	return 0
}

func (x *PlayerCookRsp) GetRecipeData() *CookRecipeData {
	if x != nil {
		return x.RecipeData
	}
	return nil
}

func (x *PlayerCookRsp) GetItemList() []*ItemParam {
	if x != nil {
		return x.ItemList
	}
	return nil
}

func (x *PlayerCookRsp) GetQteQuality() uint32 {
	if x != nil {
		return x.QteQuality
	}
	return 0
}

func (x *PlayerCookRsp) GetCookCount() uint32 {
	if x != nil {
		return x.CookCount
	}
	return 0
}

var File_PlayerCookRsp_proto protoreflect.FileDescriptor

var file_PlayerCookRsp_proto_rawDesc = []byte{
	0x0a, 0x13, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x43, 0x6f, 0x6f, 0x6b, 0x52, 0x73, 0x70, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0f, 0x49, 0x74,
	0x65, 0x6d, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x14, 0x43,
	0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x63, 0x69, 0x70, 0x65, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x9e, 0x02, 0x0a, 0x0d, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x43, 0x6f,
	0x6f, 0x6b, 0x52, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x74, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x72, 0x65, 0x74, 0x63, 0x6f, 0x64, 0x65, 0x12,
	0x36, 0x0a, 0x0b, 0x72, 0x65, 0x63, 0x69, 0x70, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6f, 0x6f,
	0x6b, 0x52, 0x65, 0x63, 0x69, 0x70, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x0a, 0x72, 0x65, 0x63,
	0x69, 0x70, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x2d, 0x0a, 0x09, 0x69, 0x74, 0x65, 0x6d, 0x5f,
	0x6c, 0x69, 0x73, 0x74, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x52, 0x08, 0x69, 0x74,
	0x65, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x71, 0x74, 0x65, 0x5f, 0x71, 0x75,
	0x61, 0x6c, 0x69, 0x74, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x71, 0x74, 0x65,
	0x51, 0x75, 0x61, 0x6c, 0x69, 0x74, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6f, 0x6f, 0x6b, 0x5f,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x63, 0x6f, 0x6f,
	0x6b, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x4c, 0x0a, 0x05, 0x43, 0x6d, 0x64, 0x49, 0x64, 0x12,
	0x08, 0x0a, 0x04, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x43, 0x4d, 0x44,
	0x5f, 0x49, 0x44, 0x10, 0x7f, 0x12, 0x13, 0x0a, 0x0f, 0x45, 0x4e, 0x45, 0x54, 0x5f, 0x43, 0x48,
	0x41, 0x4e, 0x4e, 0x45, 0x4c, 0x5f, 0x49, 0x44, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x45, 0x4e,
	0x45, 0x54, 0x5f, 0x49, 0x53, 0x5f, 0x52, 0x45, 0x4c, 0x49, 0x41, 0x42, 0x4c, 0x45, 0x10, 0x01,
	0x1a, 0x02, 0x10, 0x01, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_PlayerCookRsp_proto_rawDescOnce sync.Once
	file_PlayerCookRsp_proto_rawDescData = file_PlayerCookRsp_proto_rawDesc
)

func file_PlayerCookRsp_proto_rawDescGZIP() []byte {
	file_PlayerCookRsp_proto_rawDescOnce.Do(func() {
		file_PlayerCookRsp_proto_rawDescData = protoimpl.X.CompressGZIP(file_PlayerCookRsp_proto_rawDescData)
	})
	return file_PlayerCookRsp_proto_rawDescData
}

var file_PlayerCookRsp_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_PlayerCookRsp_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_PlayerCookRsp_proto_goTypes = []interface{}{
	(PlayerCookRsp_CmdId)(0), // 0: proto.PlayerCookRsp.CmdId
	(*PlayerCookRsp)(nil),    // 1: proto.PlayerCookRsp
	(*CookRecipeData)(nil),   // 2: proto.CookRecipeData
	(*ItemParam)(nil),        // 3: proto.ItemParam
}
var file_PlayerCookRsp_proto_depIdxs = []int32{
	2, // 0: proto.PlayerCookRsp.recipe_data:type_name -> proto.CookRecipeData
	3, // 1: proto.PlayerCookRsp.item_list:type_name -> proto.ItemParam
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_PlayerCookRsp_proto_init() }
func file_PlayerCookRsp_proto_init() {
	if File_PlayerCookRsp_proto != nil {
		return
	}
	file_ItemParam_proto_init()
	file_CookRecipeData_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_PlayerCookRsp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerCookRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_PlayerCookRsp_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_PlayerCookRsp_proto_goTypes,
		DependencyIndexes: file_PlayerCookRsp_proto_depIdxs,
		EnumInfos:         file_PlayerCookRsp_proto_enumTypes,
		MessageInfos:      file_PlayerCookRsp_proto_msgTypes,
	}.Build()
	File_PlayerCookRsp_proto = out.File
	file_PlayerCookRsp_proto_rawDesc = nil
	file_PlayerCookRsp_proto_goTypes = nil
	file_PlayerCookRsp_proto_depIdxs = nil
}
