// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.4.0
// source: SceneEntitiesMovesRsp.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SceneEntitiesMovesRsp_CmdId int32

const (
	SceneEntitiesMovesRsp_NONE             SceneEntitiesMovesRsp_CmdId = 0
	SceneEntitiesMovesRsp_CMD_ID           SceneEntitiesMovesRsp_CmdId = 300
	SceneEntitiesMovesRsp_ENET_CHANNEL_ID  SceneEntitiesMovesRsp_CmdId = 1
	SceneEntitiesMovesRsp_ENET_IS_RELIABLE SceneEntitiesMovesRsp_CmdId = 0
)

// Enum value maps for SceneEntitiesMovesRsp_CmdId.
var (
	SceneEntitiesMovesRsp_CmdId_name = map[int32]string{
		0:   "NONE",
		300: "CMD_ID",
		1:   "ENET_CHANNEL_ID",
		// Duplicate value: 0: "ENET_IS_RELIABLE",
	}
	SceneEntitiesMovesRsp_CmdId_value = map[string]int32{
		"NONE":             0,
		"CMD_ID":           300,
		"ENET_CHANNEL_ID":  1,
		"ENET_IS_RELIABLE": 0,
	}
)

func (x SceneEntitiesMovesRsp_CmdId) Enum() *SceneEntitiesMovesRsp_CmdId {
	p := new(SceneEntitiesMovesRsp_CmdId)
	*p = x
	return p
}

func (x SceneEntitiesMovesRsp_CmdId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SceneEntitiesMovesRsp_CmdId) Descriptor() protoreflect.EnumDescriptor {
	return file_SceneEntitiesMovesRsp_proto_enumTypes[0].Descriptor()
}

func (SceneEntitiesMovesRsp_CmdId) Type() protoreflect.EnumType {
	return &file_SceneEntitiesMovesRsp_proto_enumTypes[0]
}

func (x SceneEntitiesMovesRsp_CmdId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SceneEntitiesMovesRsp_CmdId.Descriptor instead.
func (SceneEntitiesMovesRsp_CmdId) EnumDescriptor() ([]byte, []int) {
	return file_SceneEntitiesMovesRsp_proto_rawDescGZIP(), []int{0, 0}
}

type SceneEntitiesMovesRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EntityMoveFailInfoList []*EntityMoveFailInfo `protobuf:"bytes,1,rep,name=entity_move_fail_info_list,json=entityMoveFailInfoList,proto3" json:"entity_move_fail_info_list,omitempty"`
}

func (x *SceneEntitiesMovesRsp) Reset() {
	*x = SceneEntitiesMovesRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_SceneEntitiesMovesRsp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SceneEntitiesMovesRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SceneEntitiesMovesRsp) ProtoMessage() {}

func (x *SceneEntitiesMovesRsp) ProtoReflect() protoreflect.Message {
	mi := &file_SceneEntitiesMovesRsp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SceneEntitiesMovesRsp.ProtoReflect.Descriptor instead.
func (*SceneEntitiesMovesRsp) Descriptor() ([]byte, []int) {
	return file_SceneEntitiesMovesRsp_proto_rawDescGZIP(), []int{0}
}

func (x *SceneEntitiesMovesRsp) GetEntityMoveFailInfoList() []*EntityMoveFailInfo {
	if x != nil {
		return x.EntityMoveFailInfoList
	}
	return nil
}

var File_SceneEntitiesMovesRsp_proto protoreflect.FileDescriptor

var file_SceneEntitiesMovesRsp_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x4d,
	0x6f, 0x76, 0x65, 0x73, 0x52, 0x73, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x18, 0x45,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x4d, 0x6f, 0x76, 0x65, 0x46, 0x61, 0x69, 0x6c, 0x49, 0x6e, 0x66,
	0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb7, 0x01, 0x0a, 0x15, 0x53, 0x63, 0x65, 0x6e,
	0x65, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x4d, 0x6f, 0x76, 0x65, 0x73, 0x52, 0x73,
	0x70, 0x12, 0x4f, 0x0a, 0x1a, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x6d, 0x6f, 0x76, 0x65,
	0x5f, 0x66, 0x61, 0x69, 0x6c, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x4d, 0x6f,
	0x76, 0x65, 0x46, 0x61, 0x69, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x16, 0x65, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x4d, 0x6f, 0x76, 0x65, 0x46, 0x61, 0x69, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x4c, 0x69,
	0x73, 0x74, 0x22, 0x4d, 0x0a, 0x05, 0x43, 0x6d, 0x64, 0x49, 0x64, 0x12, 0x08, 0x0a, 0x04, 0x4e,
	0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x06, 0x43, 0x4d, 0x44, 0x5f, 0x49, 0x44, 0x10,
	0xac, 0x02, 0x12, 0x13, 0x0a, 0x0f, 0x45, 0x4e, 0x45, 0x54, 0x5f, 0x43, 0x48, 0x41, 0x4e, 0x4e,
	0x45, 0x4c, 0x5f, 0x49, 0x44, 0x10, 0x01, 0x12, 0x14, 0x0a, 0x10, 0x45, 0x4e, 0x45, 0x54, 0x5f,
	0x49, 0x53, 0x5f, 0x52, 0x45, 0x4c, 0x49, 0x41, 0x42, 0x4c, 0x45, 0x10, 0x00, 0x1a, 0x02, 0x10,
	0x01, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_SceneEntitiesMovesRsp_proto_rawDescOnce sync.Once
	file_SceneEntitiesMovesRsp_proto_rawDescData = file_SceneEntitiesMovesRsp_proto_rawDesc
)

func file_SceneEntitiesMovesRsp_proto_rawDescGZIP() []byte {
	file_SceneEntitiesMovesRsp_proto_rawDescOnce.Do(func() {
		file_SceneEntitiesMovesRsp_proto_rawDescData = protoimpl.X.CompressGZIP(file_SceneEntitiesMovesRsp_proto_rawDescData)
	})
	return file_SceneEntitiesMovesRsp_proto_rawDescData
}

var file_SceneEntitiesMovesRsp_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_SceneEntitiesMovesRsp_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_SceneEntitiesMovesRsp_proto_goTypes = []interface{}{
	(SceneEntitiesMovesRsp_CmdId)(0), // 0: SceneEntitiesMovesRsp.CmdId
	(*SceneEntitiesMovesRsp)(nil),    // 1: SceneEntitiesMovesRsp
	(*EntityMoveFailInfo)(nil),       // 2: EntityMoveFailInfo
}
var file_SceneEntitiesMovesRsp_proto_depIdxs = []int32{
	2, // 0: SceneEntitiesMovesRsp.entity_move_fail_info_list:type_name -> EntityMoveFailInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_SceneEntitiesMovesRsp_proto_init() }
func file_SceneEntitiesMovesRsp_proto_init() {
	if File_SceneEntitiesMovesRsp_proto != nil {
		return
	}
	file_EntityMoveFailInfo_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_SceneEntitiesMovesRsp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SceneEntitiesMovesRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_SceneEntitiesMovesRsp_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_SceneEntitiesMovesRsp_proto_goTypes,
		DependencyIndexes: file_SceneEntitiesMovesRsp_proto_depIdxs,
		EnumInfos:         file_SceneEntitiesMovesRsp_proto_enumTypes,
		MessageInfos:      file_SceneEntitiesMovesRsp_proto_msgTypes,
	}.Build()
	File_SceneEntitiesMovesRsp_proto = out.File
	file_SceneEntitiesMovesRsp_proto_rawDesc = nil
	file_SceneEntitiesMovesRsp_proto_goTypes = nil
	file_SceneEntitiesMovesRsp_proto_depIdxs = nil
}
