// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.4.0
// source: SceneAreaExploreNotify.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SceneAreaExploreNotify_CmdId int32

const (
	SceneAreaExploreNotify_NONE             SceneAreaExploreNotify_CmdId = 0
	SceneAreaExploreNotify_CMD_ID           SceneAreaExploreNotify_CmdId = 237
	SceneAreaExploreNotify_ENET_CHANNEL_ID  SceneAreaExploreNotify_CmdId = 0
	SceneAreaExploreNotify_ENET_IS_RELIABLE SceneAreaExploreNotify_CmdId = 1
)

// Enum value maps for SceneAreaExploreNotify_CmdId.
var (
	SceneAreaExploreNotify_CmdId_name = map[int32]string{
		0:   "NONE",
		237: "CMD_ID",
		// Duplicate value: 0: "ENET_CHANNEL_ID",
		1: "ENET_IS_RELIABLE",
	}
	SceneAreaExploreNotify_CmdId_value = map[string]int32{
		"NONE":             0,
		"CMD_ID":           237,
		"ENET_CHANNEL_ID":  0,
		"ENET_IS_RELIABLE": 1,
	}
)

func (x SceneAreaExploreNotify_CmdId) Enum() *SceneAreaExploreNotify_CmdId {
	p := new(SceneAreaExploreNotify_CmdId)
	*p = x
	return p
}

func (x SceneAreaExploreNotify_CmdId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SceneAreaExploreNotify_CmdId) Descriptor() protoreflect.EnumDescriptor {
	return file_SceneAreaExploreNotify_proto_enumTypes[0].Descriptor()
}

func (SceneAreaExploreNotify_CmdId) Type() protoreflect.EnumType {
	return &file_SceneAreaExploreNotify_proto_enumTypes[0]
}

func (x SceneAreaExploreNotify_CmdId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SceneAreaExploreNotify_CmdId.Descriptor instead.
func (SceneAreaExploreNotify_CmdId) EnumDescriptor() ([]byte, []int) {
	return file_SceneAreaExploreNotify_proto_rawDescGZIP(), []int{0, 0}
}

type SceneAreaExploreNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AreaId         uint32  `protobuf:"varint,1,opt,name=area_id,json=areaId,proto3" json:"area_id,omitempty"`
	ExplorePercent float32 `protobuf:"fixed32,2,opt,name=explore_percent,json=explorePercent,proto3" json:"explore_percent,omitempty"`
	EventId        uint32  `protobuf:"varint,3,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
}

func (x *SceneAreaExploreNotify) Reset() {
	*x = SceneAreaExploreNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_SceneAreaExploreNotify_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SceneAreaExploreNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SceneAreaExploreNotify) ProtoMessage() {}

func (x *SceneAreaExploreNotify) ProtoReflect() protoreflect.Message {
	mi := &file_SceneAreaExploreNotify_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SceneAreaExploreNotify.ProtoReflect.Descriptor instead.
func (*SceneAreaExploreNotify) Descriptor() ([]byte, []int) {
	return file_SceneAreaExploreNotify_proto_rawDescGZIP(), []int{0}
}

func (x *SceneAreaExploreNotify) GetAreaId() uint32 {
	if x != nil {
		return x.AreaId
	}
	return 0
}

func (x *SceneAreaExploreNotify) GetExplorePercent() float32 {
	if x != nil {
		return x.ExplorePercent
	}
	return 0
}

func (x *SceneAreaExploreNotify) GetEventId() uint32 {
	if x != nil {
		return x.EventId
	}
	return 0
}

var File_SceneAreaExploreNotify_proto protoreflect.FileDescriptor

var file_SceneAreaExploreNotify_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x41, 0x72, 0x65, 0x61, 0x45, 0x78, 0x70, 0x6c, 0x6f,
	0x72, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc4,
	0x01, 0x0a, 0x16, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x41, 0x72, 0x65, 0x61, 0x45, 0x78, 0x70, 0x6c,
	0x6f, 0x72, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x17, 0x0a, 0x07, 0x61, 0x72, 0x65,
	0x61, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x61, 0x72, 0x65, 0x61,
	0x49, 0x64, 0x12, 0x27, 0x0a, 0x0f, 0x65, 0x78, 0x70, 0x6c, 0x6f, 0x72, 0x65, 0x5f, 0x70, 0x65,
	0x72, 0x63, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0e, 0x65, 0x78, 0x70,
	0x6c, 0x6f, 0x72, 0x65, 0x50, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x65,
	0x76, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x65,
	0x76, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x4d, 0x0a, 0x05, 0x43, 0x6d, 0x64, 0x49, 0x64, 0x12,
	0x08, 0x0a, 0x04, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x06, 0x43, 0x4d, 0x44,
	0x5f, 0x49, 0x44, 0x10, 0xed, 0x01, 0x12, 0x13, 0x0a, 0x0f, 0x45, 0x4e, 0x45, 0x54, 0x5f, 0x43,
	0x48, 0x41, 0x4e, 0x4e, 0x45, 0x4c, 0x5f, 0x49, 0x44, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x45,
	0x4e, 0x45, 0x54, 0x5f, 0x49, 0x53, 0x5f, 0x52, 0x45, 0x4c, 0x49, 0x41, 0x42, 0x4c, 0x45, 0x10,
	0x01, 0x1a, 0x02, 0x10, 0x01, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_SceneAreaExploreNotify_proto_rawDescOnce sync.Once
	file_SceneAreaExploreNotify_proto_rawDescData = file_SceneAreaExploreNotify_proto_rawDesc
)

func file_SceneAreaExploreNotify_proto_rawDescGZIP() []byte {
	file_SceneAreaExploreNotify_proto_rawDescOnce.Do(func() {
		file_SceneAreaExploreNotify_proto_rawDescData = protoimpl.X.CompressGZIP(file_SceneAreaExploreNotify_proto_rawDescData)
	})
	return file_SceneAreaExploreNotify_proto_rawDescData
}

var file_SceneAreaExploreNotify_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_SceneAreaExploreNotify_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_SceneAreaExploreNotify_proto_goTypes = []interface{}{
	(SceneAreaExploreNotify_CmdId)(0), // 0: SceneAreaExploreNotify.CmdId
	(*SceneAreaExploreNotify)(nil),    // 1: SceneAreaExploreNotify
}
var file_SceneAreaExploreNotify_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_SceneAreaExploreNotify_proto_init() }
func file_SceneAreaExploreNotify_proto_init() {
	if File_SceneAreaExploreNotify_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_SceneAreaExploreNotify_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SceneAreaExploreNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_SceneAreaExploreNotify_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_SceneAreaExploreNotify_proto_goTypes,
		DependencyIndexes: file_SceneAreaExploreNotify_proto_depIdxs,
		EnumInfos:         file_SceneAreaExploreNotify_proto_enumTypes,
		MessageInfos:      file_SceneAreaExploreNotify_proto_msgTypes,
	}.Build()
	File_SceneAreaExploreNotify_proto = out.File
	file_SceneAreaExploreNotify_proto_rawDesc = nil
	file_SceneAreaExploreNotify_proto_goTypes = nil
	file_SceneAreaExploreNotify_proto_depIdxs = nil
}
