// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.4.0
// source: SceneCreateEntityRsp.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SceneCreateEntityRsp_CmdId int32

const (
	SceneCreateEntityRsp_NONE             SceneCreateEntityRsp_CmdId = 0
	SceneCreateEntityRsp_CMD_ID           SceneCreateEntityRsp_CmdId = 228
	SceneCreateEntityRsp_ENET_CHANNEL_ID  SceneCreateEntityRsp_CmdId = 0
	SceneCreateEntityRsp_ENET_IS_RELIABLE SceneCreateEntityRsp_CmdId = 1
)

// Enum value maps for SceneCreateEntityRsp_CmdId.
var (
	SceneCreateEntityRsp_CmdId_name = map[int32]string{
		0:   "NONE",
		228: "CMD_ID",
		// Duplicate value: 0: "ENET_CHANNEL_ID",
		1: "ENET_IS_RELIABLE",
	}
	SceneCreateEntityRsp_CmdId_value = map[string]int32{
		"NONE":             0,
		"CMD_ID":           228,
		"ENET_CHANNEL_ID":  0,
		"ENET_IS_RELIABLE": 1,
	}
)

func (x SceneCreateEntityRsp_CmdId) Enum() *SceneCreateEntityRsp_CmdId {
	p := new(SceneCreateEntityRsp_CmdId)
	*p = x
	return p
}

func (x SceneCreateEntityRsp_CmdId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SceneCreateEntityRsp_CmdId) Descriptor() protoreflect.EnumDescriptor {
	return file_SceneCreateEntityRsp_proto_enumTypes[0].Descriptor()
}

func (SceneCreateEntityRsp_CmdId) Type() protoreflect.EnumType {
	return &file_SceneCreateEntityRsp_proto_enumTypes[0]
}

func (x SceneCreateEntityRsp_CmdId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SceneCreateEntityRsp_CmdId.Descriptor instead.
func (SceneCreateEntityRsp_CmdId) EnumDescriptor() ([]byte, []int) {
	return file_SceneCreateEntityRsp_proto_rawDescGZIP(), []int{0, 0}
}

type SceneCreateEntityRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Retcode  int32             `protobuf:"varint,1,opt,name=retcode,proto3" json:"retcode,omitempty"`
	EntityId uint32            `protobuf:"varint,2,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Entity   *CreateEntityInfo `protobuf:"bytes,3,opt,name=entity,proto3" json:"entity,omitempty"`
}

func (x *SceneCreateEntityRsp) Reset() {
	*x = SceneCreateEntityRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_SceneCreateEntityRsp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SceneCreateEntityRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SceneCreateEntityRsp) ProtoMessage() {}

func (x *SceneCreateEntityRsp) ProtoReflect() protoreflect.Message {
	mi := &file_SceneCreateEntityRsp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SceneCreateEntityRsp.ProtoReflect.Descriptor instead.
func (*SceneCreateEntityRsp) Descriptor() ([]byte, []int) {
	return file_SceneCreateEntityRsp_proto_rawDescGZIP(), []int{0}
}

func (x *SceneCreateEntityRsp) GetRetcode() int32 {
	if x != nil {
		return x.Retcode
	}
	return 0
}

func (x *SceneCreateEntityRsp) GetEntityId() uint32 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *SceneCreateEntityRsp) GetEntity() *CreateEntityInfo {
	if x != nil {
		return x.Entity
	}
	return nil
}

var File_SceneCreateEntityRsp_proto protoreflect.FileDescriptor

var file_SceneCreateEntityRsp_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x52, 0x73, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xcd, 0x01, 0x0a, 0x14,
	0x53, 0x63, 0x65, 0x6e, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x52, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x74, 0x63, 0x6f, 0x64, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x72, 0x65, 0x74, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x1b,
	0x0a, 0x09, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x08, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x64, 0x12, 0x2f, 0x0a, 0x06, 0x65,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x06, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x22, 0x4d, 0x0a, 0x05,
	0x43, 0x6d, 0x64, 0x49, 0x64, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12,
	0x0b, 0x0a, 0x06, 0x43, 0x4d, 0x44, 0x5f, 0x49, 0x44, 0x10, 0xe4, 0x01, 0x12, 0x13, 0x0a, 0x0f,
	0x45, 0x4e, 0x45, 0x54, 0x5f, 0x43, 0x48, 0x41, 0x4e, 0x4e, 0x45, 0x4c, 0x5f, 0x49, 0x44, 0x10,
	0x00, 0x12, 0x14, 0x0a, 0x10, 0x45, 0x4e, 0x45, 0x54, 0x5f, 0x49, 0x53, 0x5f, 0x52, 0x45, 0x4c,
	0x49, 0x41, 0x42, 0x4c, 0x45, 0x10, 0x01, 0x1a, 0x02, 0x10, 0x01, 0x42, 0x0a, 0x5a, 0x08, 0x2e,
	0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_SceneCreateEntityRsp_proto_rawDescOnce sync.Once
	file_SceneCreateEntityRsp_proto_rawDescData = file_SceneCreateEntityRsp_proto_rawDesc
)

func file_SceneCreateEntityRsp_proto_rawDescGZIP() []byte {
	file_SceneCreateEntityRsp_proto_rawDescOnce.Do(func() {
		file_SceneCreateEntityRsp_proto_rawDescData = protoimpl.X.CompressGZIP(file_SceneCreateEntityRsp_proto_rawDescData)
	})
	return file_SceneCreateEntityRsp_proto_rawDescData
}

var file_SceneCreateEntityRsp_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_SceneCreateEntityRsp_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_SceneCreateEntityRsp_proto_goTypes = []interface{}{
	(SceneCreateEntityRsp_CmdId)(0), // 0: proto.SceneCreateEntityRsp.CmdId
	(*SceneCreateEntityRsp)(nil),    // 1: proto.SceneCreateEntityRsp
	(*CreateEntityInfo)(nil),        // 2: proto.CreateEntityInfo
}
var file_SceneCreateEntityRsp_proto_depIdxs = []int32{
	2, // 0: proto.SceneCreateEntityRsp.entity:type_name -> proto.CreateEntityInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_SceneCreateEntityRsp_proto_init() }
func file_SceneCreateEntityRsp_proto_init() {
	if File_SceneCreateEntityRsp_proto != nil {
		return
	}
	file_CreateEntityInfo_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_SceneCreateEntityRsp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SceneCreateEntityRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_SceneCreateEntityRsp_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_SceneCreateEntityRsp_proto_goTypes,
		DependencyIndexes: file_SceneCreateEntityRsp_proto_depIdxs,
		EnumInfos:         file_SceneCreateEntityRsp_proto_enumTypes,
		MessageInfos:      file_SceneCreateEntityRsp_proto_msgTypes,
	}.Build()
	File_SceneCreateEntityRsp_proto = out.File
	file_SceneCreateEntityRsp_proto_rawDesc = nil
	file_SceneCreateEntityRsp_proto_goTypes = nil
	file_SceneCreateEntityRsp_proto_depIdxs = nil
}
