// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.4.0
// source: UnlockPersonalLineRsp.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UnlockPersonalLineRsp_CmdId int32

const (
	UnlockPersonalLineRsp_NONE             UnlockPersonalLineRsp_CmdId = 0
	UnlockPersonalLineRsp_CMD_ID           UnlockPersonalLineRsp_CmdId = 440
	UnlockPersonalLineRsp_ENET_CHANNEL_ID  UnlockPersonalLineRsp_CmdId = 0
	UnlockPersonalLineRsp_ENET_IS_RELIABLE UnlockPersonalLineRsp_CmdId = 1
)

// Enum value maps for UnlockPersonalLineRsp_CmdId.
var (
	UnlockPersonalLineRsp_CmdId_name = map[int32]string{
		0:   "NONE",
		440: "CMD_ID",
		// Duplicate value: 0: "ENET_CHANNEL_ID",
		1: "ENET_IS_RELIABLE",
	}
	UnlockPersonalLineRsp_CmdId_value = map[string]int32{
		"NONE":             0,
		"CMD_ID":           440,
		"ENET_CHANNEL_ID":  0,
		"ENET_IS_RELIABLE": 1,
	}
)

func (x UnlockPersonalLineRsp_CmdId) Enum() *UnlockPersonalLineRsp_CmdId {
	p := new(UnlockPersonalLineRsp_CmdId)
	*p = x
	return p
}

func (x UnlockPersonalLineRsp_CmdId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UnlockPersonalLineRsp_CmdId) Descriptor() protoreflect.EnumDescriptor {
	return file_UnlockPersonalLineRsp_proto_enumTypes[0].Descriptor()
}

func (UnlockPersonalLineRsp_CmdId) Type() protoreflect.EnumType {
	return &file_UnlockPersonalLineRsp_proto_enumTypes[0]
}

func (x UnlockPersonalLineRsp_CmdId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UnlockPersonalLineRsp_CmdId.Descriptor instead.
func (UnlockPersonalLineRsp_CmdId) EnumDescriptor() ([]byte, []int) {
	return file_UnlockPersonalLineRsp_proto_rawDescGZIP(), []int{0, 0}
}

type UnlockPersonalLineRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Retcode        int32  `protobuf:"varint,1,opt,name=retcode,proto3" json:"retcode,omitempty"`
	PersonalLineId uint32 `protobuf:"varint,2,opt,name=personal_line_id,json=personalLineId,proto3" json:"personal_line_id,omitempty"`
	// Types that are assignable to Param:
	//
	//	*UnlockPersonalLineRsp_Level
	//	*UnlockPersonalLineRsp_ChapterId
	Param isUnlockPersonalLineRsp_Param `protobuf_oneof:"param"`
}

func (x *UnlockPersonalLineRsp) Reset() {
	*x = UnlockPersonalLineRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_UnlockPersonalLineRsp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnlockPersonalLineRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlockPersonalLineRsp) ProtoMessage() {}

func (x *UnlockPersonalLineRsp) ProtoReflect() protoreflect.Message {
	mi := &file_UnlockPersonalLineRsp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlockPersonalLineRsp.ProtoReflect.Descriptor instead.
func (*UnlockPersonalLineRsp) Descriptor() ([]byte, []int) {
	return file_UnlockPersonalLineRsp_proto_rawDescGZIP(), []int{0}
}

func (x *UnlockPersonalLineRsp) GetRetcode() int32 {
	if x != nil {
		return x.Retcode
	}
	return 0
}

func (x *UnlockPersonalLineRsp) GetPersonalLineId() uint32 {
	if x != nil {
		return x.PersonalLineId
	}
	return 0
}

func (m *UnlockPersonalLineRsp) GetParam() isUnlockPersonalLineRsp_Param {
	if m != nil {
		return m.Param
	}
	return nil
}

func (x *UnlockPersonalLineRsp) GetLevel() uint32 {
	if x, ok := x.GetParam().(*UnlockPersonalLineRsp_Level); ok {
		return x.Level
	}
	return 0
}

func (x *UnlockPersonalLineRsp) GetChapterId() uint32 {
	if x, ok := x.GetParam().(*UnlockPersonalLineRsp_ChapterId); ok {
		return x.ChapterId
	}
	return 0
}

type isUnlockPersonalLineRsp_Param interface {
	isUnlockPersonalLineRsp_Param()
}

type UnlockPersonalLineRsp_Level struct {
	Level uint32 `protobuf:"varint,3,opt,name=level,proto3,oneof"`
}

type UnlockPersonalLineRsp_ChapterId struct {
	ChapterId uint32 `protobuf:"varint,4,opt,name=chapter_id,json=chapterId,proto3,oneof"`
}

func (*UnlockPersonalLineRsp_Level) isUnlockPersonalLineRsp_Param() {}

func (*UnlockPersonalLineRsp_ChapterId) isUnlockPersonalLineRsp_Param() {}

var File_UnlockPersonalLineRsp_proto protoreflect.FileDescriptor

var file_UnlockPersonalLineRsp_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x55, 0x6e, 0x6c, 0x6f, 0x63, 0x6b, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c,
	0x4c, 0x69, 0x6e, 0x65, 0x52, 0x73, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0xec, 0x01, 0x0a, 0x15, 0x55, 0x6e, 0x6c, 0x6f, 0x63, 0x6b, 0x50,
	0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x4c, 0x69, 0x6e, 0x65, 0x52, 0x73, 0x70, 0x12, 0x18,
	0x0a, 0x07, 0x72, 0x65, 0x74, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x07, 0x72, 0x65, 0x74, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x28, 0x0a, 0x10, 0x70, 0x65, 0x72, 0x73,
	0x6f, 0x6e, 0x61, 0x6c, 0x5f, 0x6c, 0x69, 0x6e, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x0e, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x4c, 0x69, 0x6e, 0x65,
	0x49, 0x64, 0x12, 0x16, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0d, 0x48, 0x00, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x1f, 0x0a, 0x0a, 0x63, 0x68,
	0x61, 0x70, 0x74, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x00,
	0x52, 0x09, 0x63, 0x68, 0x61, 0x70, 0x74, 0x65, 0x72, 0x49, 0x64, 0x22, 0x4d, 0x0a, 0x05, 0x43,
	0x6d, 0x64, 0x49, 0x64, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x0b,
	0x0a, 0x06, 0x43, 0x4d, 0x44, 0x5f, 0x49, 0x44, 0x10, 0xb8, 0x03, 0x12, 0x13, 0x0a, 0x0f, 0x45,
	0x4e, 0x45, 0x54, 0x5f, 0x43, 0x48, 0x41, 0x4e, 0x4e, 0x45, 0x4c, 0x5f, 0x49, 0x44, 0x10, 0x00,
	0x12, 0x14, 0x0a, 0x10, 0x45, 0x4e, 0x45, 0x54, 0x5f, 0x49, 0x53, 0x5f, 0x52, 0x45, 0x4c, 0x49,
	0x41, 0x42, 0x4c, 0x45, 0x10, 0x01, 0x1a, 0x02, 0x10, 0x01, 0x42, 0x07, 0x0a, 0x05, 0x70, 0x61,
	0x72, 0x61, 0x6d, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_UnlockPersonalLineRsp_proto_rawDescOnce sync.Once
	file_UnlockPersonalLineRsp_proto_rawDescData = file_UnlockPersonalLineRsp_proto_rawDesc
)

func file_UnlockPersonalLineRsp_proto_rawDescGZIP() []byte {
	file_UnlockPersonalLineRsp_proto_rawDescOnce.Do(func() {
		file_UnlockPersonalLineRsp_proto_rawDescData = protoimpl.X.CompressGZIP(file_UnlockPersonalLineRsp_proto_rawDescData)
	})
	return file_UnlockPersonalLineRsp_proto_rawDescData
}

var file_UnlockPersonalLineRsp_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_UnlockPersonalLineRsp_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_UnlockPersonalLineRsp_proto_goTypes = []interface{}{
	(UnlockPersonalLineRsp_CmdId)(0), // 0: proto.UnlockPersonalLineRsp.CmdId
	(*UnlockPersonalLineRsp)(nil),    // 1: proto.UnlockPersonalLineRsp
}
var file_UnlockPersonalLineRsp_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_UnlockPersonalLineRsp_proto_init() }
func file_UnlockPersonalLineRsp_proto_init() {
	if File_UnlockPersonalLineRsp_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_UnlockPersonalLineRsp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnlockPersonalLineRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_UnlockPersonalLineRsp_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*UnlockPersonalLineRsp_Level)(nil),
		(*UnlockPersonalLineRsp_ChapterId)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_UnlockPersonalLineRsp_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_UnlockPersonalLineRsp_proto_goTypes,
		DependencyIndexes: file_UnlockPersonalLineRsp_proto_depIdxs,
		EnumInfos:         file_UnlockPersonalLineRsp_proto_enumTypes,
		MessageInfos:      file_UnlockPersonalLineRsp_proto_msgTypes,
	}.Build()
	File_UnlockPersonalLineRsp_proto = out.File
	file_UnlockPersonalLineRsp_proto_rawDesc = nil
	file_UnlockPersonalLineRsp_proto_goTypes = nil
	file_UnlockPersonalLineRsp_proto_depIdxs = nil
}
