package cmd

import (
	"reflect"
	"sync"

	"github.com/mari-track/MariGS/pkg/logger"
	"github.com/mari-track/MariGS/protocol/proto"
	pb "google.golang.org/protobuf/proto"
)

var sharedCmdProtoMap *CmdProtoMap
var cmdProtoMapOnce sync.Once

type CmdProtoMap struct {
	cmdIdProtoObjMap        map[uint16]reflect.Type
	protoObjCmdIdMap        map[reflect.Type]uint16
	cmdDeDupMap             map[uint16]bool
	cmdIdCmdNameMap         map[uint16]string
	cmdNameCmdIdMap         map[string]uint16
	cmdIdProtoObjCacheMap   map[uint16]*sync.Pool
	cmdIdProtoObjFastNewMap map[uint16]func() any
}

func GetSharedCmdProtoMap() *CmdProtoMap {
	cmdProtoMapOnce.Do(func() {
		sharedCmdProtoMap = NewCmdProtoMap()
	})
	return sharedCmdProtoMap
}

func NewCmdProtoMap() (r *CmdProtoMap) {
	r = new(CmdProtoMap)
	r.cmdIdProtoObjMap = make(map[uint16]reflect.Type)
	r.protoObjCmdIdMap = make(map[reflect.Type]uint16)
	r.cmdDeDupMap = make(map[uint16]bool)
	r.cmdIdCmdNameMap = make(map[uint16]string)
	r.cmdNameCmdIdMap = make(map[string]uint16)
	r.cmdIdProtoObjCacheMap = make(map[uint16]*sync.Pool)
	r.cmdIdProtoObjFastNewMap = make(map[uint16]func() any)
	r.registerAllMessage()

	return r
}

func (c *CmdProtoMap) registerMessage() {
	c.regMsg(GetPlayerTokenReq, func() any { return new(proto.GetPlayerTokenReq) })
	c.regMsg(GetShopReq, func() any { return new(proto.GetShopReq) })
	c.regMsg(GetShopRsp, func() any { return new(proto.GetShopRsp) })
	c.regMsg(BuyGoodsReq, func() any { return new(proto.BuyGoodsReq) })
	c.regMsg(BuyGoodsRsp, func() any { return new(proto.BuyGoodsRsp) })
	c.regMsg(GetShopmallDataReq, func() any { return new(proto.GetShopmallDataReq) })
	c.regMsg(GetShopmallDataRsp, func() any { return new(proto.GetShopmallDataRsp) })
	c.regMsg(OpActivityStateNotify, func() any { return new(proto.OpActivityStateNotify) })
	c.regMsg(SignInInfoReq, func() any { return new(proto.SignInInfoReq) })
	c.regMsg(SignInInfoRsp, func() any { return new(proto.SignInInfoRsp) })
	c.regMsg(GetSignInRewardReq, func() any { return new(proto.GetSignInRewardReq) })
	c.regMsg(GetSignInRewardRsp, func() any { return new(proto.GetSignInRewardRsp) })
	c.regMsg(BonusActivityUpdateNotify, func() any { return new(proto.BonusActivityUpdateNotify) })
	c.regMsg(BonusActivityInfoReq, func() any { return new(proto.BonusActivityInfoReq) })
	c.regMsg(BonusActivityInfoRsp, func() any { return new(proto.BonusActivityInfoRsp) })
	c.regMsg(GetBonusActivityRewardReq, func() any { return new(proto.GetBonusActivityRewardReq) })
	c.regMsg(GetBonusActivityRewardRsp, func() any { return new(proto.GetBonusActivityRewardRsp) })
	c.regMsg(UnlockAvatarTalentReq, func() any { return new(proto.UnlockAvatarTalentReq) })
	c.regMsg(UnlockAvatarTalentRsp, func() any { return new(proto.UnlockAvatarTalentRsp) })
	c.regMsg(AvatarUnlockTalentNotify, func() any { return new(proto.AvatarUnlockTalentNotify) })
	c.regMsg(AvatarSkillDepotChangeNotify, func() any { return new(proto.AvatarSkillDepotChangeNotify) })
	c.regMsg(BigTalentPointConvertReq, func() any { return new(proto.BigTalentPointConvertReq) })
	c.regMsg(BigTalentPointConvertRsp, func() any { return new(proto.BigTalentPointConvertRsp) })
	c.regMsg(AvatarSkillMaxChargeCountNotify, func() any { return new(proto.AvatarSkillMaxChargeCountNotify) })
	c.regMsg(AvatarSkillInfoNotify, func() any { return new(proto.AvatarSkillInfoNotify) })
	c.regMsg(ProudSkillUpgradeReq, func() any { return new(proto.ProudSkillUpgradeReq) })
	c.regMsg(ProudSkillUpgradeRsp, func() any { return new(proto.ProudSkillUpgradeRsp) })
	c.regMsg(ProudSkillChangeNotify, func() any { return new(proto.ProudSkillChangeNotify) })
	c.regMsg(AvatarSkillUpgradeReq, func() any { return new(proto.AvatarSkillUpgradeReq) })
	c.regMsg(AvatarSkillUpgradeRsp, func() any { return new(proto.AvatarSkillUpgradeRsp) })
	c.regMsg(AvatarSkillChangeNotify, func() any { return new(proto.AvatarSkillChangeNotify) })
	c.regMsg(ProudSkillExtraLevelNotify, func() any { return new(proto.ProudSkillExtraLevelNotify) })
	c.regMsg(CanUseSkillNotify, func() any { return new(proto.CanUseSkillNotify) })
	c.regMsg(TeamResonanceChangeNotify, func() any { return new(proto.TeamResonanceChangeNotify) })
	c.regMsg(GetPlayerFriendListReq, func() any { return new(proto.GetPlayerFriendListReq) })
	c.regMsg(GetPlayerFriendListRsp, func() any { return new(proto.GetPlayerFriendListRsp) })
	c.regMsg(AskAddFriendReq, func() any { return new(proto.AskAddFriendReq) })
	c.regMsg(AskAddFriendRsp, func() any { return new(proto.AskAddFriendRsp) })
	c.regMsg(DealAddFriendReq, func() any { return new(proto.DealAddFriendReq) })
	c.regMsg(DealAddFriendRsp, func() any { return new(proto.DealAddFriendRsp) })
	c.regMsg(GetPlayerSocialDetailReq, func() any { return new(proto.GetPlayerSocialDetailReq) })
	c.regMsg(GetPlayerSocialDetailRsp, func() any { return new(proto.GetPlayerSocialDetailRsp) })
	c.regMsg(DeleteFriendReq, func() any { return new(proto.DeleteFriendReq) })
	c.regMsg(DeleteFriendRsp, func() any { return new(proto.DeleteFriendRsp) })
	c.regMsg(SetPlayerBirthdayReq, func() any { return new(proto.SetPlayerBirthdayReq) })
	c.regMsg(SetPlayerBirthdayRsp, func() any { return new(proto.SetPlayerBirthdayRsp) })
	c.regMsg(SetPlayerSignatureReq, func() any { return new(proto.SetPlayerSignatureReq) })
	c.regMsg(SetPlayerSignatureRsp, func() any { return new(proto.SetPlayerSignatureRsp) })
	c.regMsg(SetPlayerHeadImageReq, func() any { return new(proto.SetPlayerHeadImageReq) })
	c.regMsg(SetPlayerHeadImageRsp, func() any { return new(proto.SetPlayerHeadImageRsp) })
	c.regMsg(UpdatePS4FriendListNotify, func() any { return new(proto.UpdatePS4FriendListNotify) })
	c.regMsg(DeleteFriendNotify, func() any { return new(proto.DeleteFriendNotify) })
	c.regMsg(AddFriendNotify, func() any { return new(proto.AddFriendNotify) })
	c.regMsg(AskAddFriendNotify, func() any { return new(proto.AskAddFriendNotify) })
	c.regMsg(SetNameCardReq, func() any { return new(proto.SetNameCardReq) })
	c.regMsg(SetNameCardRsp, func() any { return new(proto.SetNameCardRsp) })
	c.regMsg(GetAllUnlockNameCardReq, func() any { return new(proto.GetAllUnlockNameCardReq) })
	c.regMsg(GetAllUnlockNameCardRsp, func() any { return new(proto.GetAllUnlockNameCardRsp) })
	c.regMsg(AddBlacklistReq, func() any { return new(proto.AddBlacklistReq) })
	c.regMsg(AddBlacklistRsp, func() any { return new(proto.AddBlacklistRsp) })
	c.regMsg(RemoveBlacklistReq, func() any { return new(proto.RemoveBlacklistReq) })
	c.regMsg(RemoveBlacklistRsp, func() any { return new(proto.RemoveBlacklistRsp) })
	c.regMsg(UnlockNameCardNotify, func() any { return new(proto.UnlockNameCardNotify) })
	c.regMsg(GetRecentMpPlayerListReq, func() any { return new(proto.GetRecentMpPlayerListReq) })
	c.regMsg(GetRecentMpPlayerListRsp, func() any { return new(proto.GetRecentMpPlayerListRsp) })
	c.regMsg(SocialDataNotify, func() any { return new(proto.SocialDataNotify) })
	c.regMsg(TakeFirstShareRewardReq, func() any { return new(proto.TakeFirstShareRewardReq) })
	c.regMsg(TakeFirstShareRewardRsp, func() any { return new(proto.TakeFirstShareRewardRsp) })
	c.regMsg(UpdatePS4BlockListReq, func() any { return new(proto.UpdatePS4BlockListReq) })
	c.regMsg(UpdatePS4BlockListRsp, func() any { return new(proto.UpdatePS4BlockListRsp) })
	c.regMsg(GetPlayerBlacklistReq, func() any { return new(proto.GetPlayerBlacklistReq) })
	c.regMsg(GetPlayerBlacklistRsp, func() any { return new(proto.GetPlayerBlacklistRsp) })
	c.regMsg(AbilityInvocationFixedNotify, func() any { return new(proto.AbilityInvocationFixedNotify) })
	c.regMsg(AbilityInvocationsNotify, func() any { return new(proto.AbilityInvocationsNotify) })
	c.regMsg(ClientAbilityInitBeginNotify, func() any { return new(proto.ClientAbilityInitBeginNotify) })
	c.regMsg(ClientAbilityInitFinishNotify, func() any { return new(proto.ClientAbilityInitFinishNotify) })
	c.regMsg(AbilityInvocationFailNotify, func() any { return new(proto.AbilityInvocationFailNotify) })
	c.regMsg(ClientAbilitiesInitFinishCombineNotify, func() any { return new(proto.ClientAbilitiesInitFinishCombineNotify) })
	c.regMsg(WindSeedClientNotify, func() any { return new(proto.WindSeedClientNotify) })
	c.regMsg(AbilityChangeNotify, func() any { return new(proto.AbilityChangeNotify) })
	c.regMsg(ClientAbilityChangeNotify, func() any { return new(proto.ClientAbilityChangeNotify) })
	c.regMsg(AchievementAllDataNotify, func() any { return new(proto.AchievementAllDataNotify) })
	c.regMsg(AchievementUpdateNotify, func() any { return new(proto.AchievementUpdateNotify) })
	c.regMsg(TakeAchievementRewardReq, func() any { return new(proto.TakeAchievementRewardReq) })
	c.regMsg(TakeAchievementRewardRsp, func() any { return new(proto.TakeAchievementRewardRsp) })
	c.regMsg(TakeAchievementGoalRewardReq, func() any { return new(proto.TakeAchievementGoalRewardReq) })
	c.regMsg(TakeAchievementGoalRewardRsp, func() any { return new(proto.TakeAchievementGoalRewardRsp) })
	c.regMsg(GetActivityScheduleReq, func() any { return new(proto.GetActivityScheduleReq) })
	c.regMsg(GetActivityScheduleRsp, func() any { return new(proto.GetActivityScheduleRsp) })
	c.regMsg(GetActivityInfoReq, func() any { return new(proto.GetActivityInfoReq) })
	c.regMsg(GetActivityInfoRsp, func() any { return new(proto.GetActivityInfoRsp) })
	c.regMsg(ActivityPlayOpenAnimNotify, func() any { return new(proto.ActivityPlayOpenAnimNotify) })
	c.regMsg(ActivityInfoNotify, func() any { return new(proto.ActivityInfoNotify) })
	c.regMsg(ActivityScheduleInfoNotify, func() any { return new(proto.ActivityScheduleInfoNotify) })
	c.regMsg(ActivityTakeWatcherRewardReq, func() any { return new(proto.ActivityTakeWatcherRewardReq) })
	c.regMsg(ActivityTakeWatcherRewardRsp, func() any { return new(proto.ActivityTakeWatcherRewardRsp) })
	c.regMsg(ActivityUpdateWatcherNotify, func() any { return new(proto.ActivityUpdateWatcherNotify) })
	c.regMsg(SeaLampFlyLampReq, func() any { return new(proto.SeaLampFlyLampReq) })
	c.regMsg(SeaLampFlyLampRsp, func() any { return new(proto.SeaLampFlyLampRsp) })
	c.regMsg(SeaLampTakeContributionRewardReq, func() any { return new(proto.SeaLampTakeContributionRewardReq) })
	c.regMsg(SeaLampTakeContributionRewardRsp, func() any { return new(proto.SeaLampTakeContributionRewardRsp) })
	c.regMsg(SeaLampTakePhaseRewardReq, func() any { return new(proto.SeaLampTakePhaseRewardReq) })
	c.regMsg(SeaLampTakePhaseRewardRsp, func() any { return new(proto.SeaLampTakePhaseRewardRsp) })
	c.regMsg(SeaLampContributeItemReq, func() any { return new(proto.SeaLampContributeItemReq) })
	c.regMsg(SeaLampContributeItemRsp, func() any { return new(proto.SeaLampContributeItemRsp) })
	c.regMsg(LoadActivityTerrainNotify, func() any { return new(proto.LoadActivityTerrainNotify) })
	c.regMsg(ServerAnnounceNotify, func() any { return new(proto.ServerAnnounceNotify) })
	c.regMsg(ServerAnnounceRevokeNotify, func() any { return new(proto.ServerAnnounceRevokeNotify) })
	c.regMsg(SalesmanDeliverItemReq, func() any { return new(proto.SalesmanDeliverItemReq) })
	c.regMsg(SalesmanDeliverItemRsp, func() any { return new(proto.SalesmanDeliverItemRsp) })
	c.regMsg(SalesmanTakeRewardReq, func() any { return new(proto.SalesmanTakeRewardReq) })
	c.regMsg(SalesmanTakeRewardRsp, func() any { return new(proto.SalesmanTakeRewardRsp) })
	c.regMsg(ActivityCondStateChangeNotify, func() any { return new(proto.ActivityCondStateChangeNotify) })
	c.regMsg(EnterTrialAvatarActivityDungeonReq, func() any { return new(proto.EnterTrialAvatarActivityDungeonReq) })
	c.regMsg(EnterTrialAvatarActivityDungeonRsp, func() any { return new(proto.EnterTrialAvatarActivityDungeonRsp) })
	c.regMsg(ReceivedTrialAvatarActivityRewardReq, func() any { return new(proto.ReceivedTrialAvatarActivityRewardReq) })
	c.regMsg(ReceivedTrialAvatarActivityRewardRsp, func() any { return new(proto.ReceivedTrialAvatarActivityRewardRsp) })
	c.regMsg(TrialAvatarFirstPassDungeonNotify, func() any { return new(proto.TrialAvatarFirstPassDungeonNotify) })
	c.regMsg(TrialAvatarInDungeonIndexNotify, func() any { return new(proto.TrialAvatarInDungeonIndexNotify) })
	c.regMsg(AvatarAddNotify, func() any { return new(proto.AvatarAddNotify) })
	c.regMsg(AvatarDelNotify, func() any { return new(proto.AvatarDelNotify) })
	c.regMsg(SetUpAvatarTeamReq, func() any { return new(proto.SetUpAvatarTeamReq) })
	c.regMsg(SetUpAvatarTeamRsp, func() any { return new(proto.SetUpAvatarTeamRsp) })
	c.regMsg(ChooseCurAvatarTeamReq, func() any { return new(proto.ChooseCurAvatarTeamReq) })
	c.regMsg(ChooseCurAvatarTeamRsp, func() any { return new(proto.ChooseCurAvatarTeamRsp) })
	c.regMsg(ChangeAvatarReq, func() any { return new(proto.ChangeAvatarReq) })
	c.regMsg(ChangeAvatarRsp, func() any { return new(proto.ChangeAvatarRsp) })
	c.regMsg(AvatarPromoteReq, func() any { return new(proto.AvatarPromoteReq) })
	c.regMsg(AvatarPromoteRsp, func() any { return new(proto.AvatarPromoteRsp) })
	c.regMsg(SpringUseReq, func() any { return new(proto.SpringUseReq) })
	c.regMsg(SpringUseRsp, func() any { return new(proto.SpringUseRsp) })
	c.regMsg(RefreshBackgroundAvatarReq, func() any { return new(proto.RefreshBackgroundAvatarReq) })
	c.regMsg(RefreshBackgroundAvatarRsp, func() any { return new(proto.RefreshBackgroundAvatarRsp) })
	c.regMsg(AvatarTeamUpdateNotify, func() any { return new(proto.AvatarTeamUpdateNotify) })
	c.regMsg(AvatarDataNotify, func() any { return new(proto.AvatarDataNotify) })
	c.regMsg(AvatarUpgradeReq, func() any { return new(proto.AvatarUpgradeReq) })
	c.regMsg(AvatarUpgradeRsp, func() any { return new(proto.AvatarUpgradeRsp) })
	c.regMsg(AvatarDieAnimationEndReq, func() any { return new(proto.AvatarDieAnimationEndReq) })
	c.regMsg(AvatarDieAnimationEndRsp, func() any { return new(proto.AvatarDieAnimationEndRsp) })
	c.regMsg(AvatarChangeElementTypeReq, func() any { return new(proto.AvatarChangeElementTypeReq) })
	c.regMsg(AvatarChangeElementTypeRsp, func() any { return new(proto.AvatarChangeElementTypeRsp) })
	c.regMsg(AvatarFetterDataNotify, func() any { return new(proto.AvatarFetterDataNotify) })
	c.regMsg(AvatarExpeditionDataNotify, func() any { return new(proto.AvatarExpeditionDataNotify) })
	c.regMsg(AvatarExpeditionAllDataReq, func() any { return new(proto.AvatarExpeditionAllDataReq) })
	c.regMsg(AvatarExpeditionAllDataRsp, func() any { return new(proto.AvatarExpeditionAllDataRsp) })
	c.regMsg(AvatarExpeditionStartReq, func() any { return new(proto.AvatarExpeditionStartReq) })
	c.regMsg(AvatarExpeditionStartRsp, func() any { return new(proto.AvatarExpeditionStartRsp) })
	c.regMsg(AvatarExpeditionCallBackReq, func() any { return new(proto.AvatarExpeditionCallBackReq) })
	c.regMsg(AvatarExpeditionCallBackRsp, func() any { return new(proto.AvatarExpeditionCallBackRsp) })
	c.regMsg(AvatarExpeditionGetRewardReq, func() any { return new(proto.AvatarExpeditionGetRewardReq) })
	c.regMsg(AvatarExpeditionGetRewardRsp, func() any { return new(proto.AvatarExpeditionGetRewardRsp) })
	c.regMsg(ChangeMpTeamAvatarReq, func() any { return new(proto.ChangeMpTeamAvatarReq) })
	c.regMsg(ChangeMpTeamAvatarRsp, func() any { return new(proto.ChangeMpTeamAvatarRsp) })
	c.regMsg(ChangeTeamNameReq, func() any { return new(proto.ChangeTeamNameReq) })
	c.regMsg(ChangeTeamNameRsp, func() any { return new(proto.ChangeTeamNameRsp) })
	c.regMsg(SceneTeamUpdateNotify, func() any { return new(proto.SceneTeamUpdateNotify) })
	c.regMsg(FocusAvatarReq, func() any { return new(proto.FocusAvatarReq) })
	c.regMsg(FocusAvatarRsp, func() any { return new(proto.FocusAvatarRsp) })
	c.regMsg(AvatarSatiationDataNotify, func() any { return new(proto.AvatarSatiationDataNotify) })
	c.regMsg(AvatarWearFlycloakReq, func() any { return new(proto.AvatarWearFlycloakReq) })
	c.regMsg(AvatarWearFlycloakRsp, func() any { return new(proto.AvatarWearFlycloakRsp) })
	c.regMsg(AvatarFlycloakChangeNotify, func() any { return new(proto.AvatarFlycloakChangeNotify) })
	c.regMsg(AvatarGainFlycloakNotify, func() any { return new(proto.AvatarGainFlycloakNotify) })
	c.regMsg(AvatarEquipAffixStartNotify, func() any { return new(proto.AvatarEquipAffixStartNotify) })
	c.regMsg(AvatarFetterLevelRewardReq, func() any { return new(proto.AvatarFetterLevelRewardReq) })
	c.regMsg(AvatarFetterLevelRewardRsp, func() any { return new(proto.AvatarFetterLevelRewardRsp) })
	c.regMsg(BattlePassAllDataNotify, func() any { return new(proto.BattlePassAllDataNotify) })
	c.regMsg(BattlePassMissionUpdateNotify, func() any { return new(proto.BattlePassMissionUpdateNotify) })
	c.regMsg(BattlePassMissionDelNotify, func() any { return new(proto.BattlePassMissionDelNotify) })
	c.regMsg(BattlePassCurScheduleUpdateNotify, func() any { return new(proto.BattlePassCurScheduleUpdateNotify) })
	c.regMsg(TakeBattlePassRewardReq, func() any { return new(proto.TakeBattlePassRewardReq) })
	c.regMsg(TakeBattlePassRewardRsp, func() any { return new(proto.TakeBattlePassRewardRsp) })
	c.regMsg(TakeBattlePassMissionPointReq, func() any { return new(proto.TakeBattlePassMissionPointReq) })
	c.regMsg(TakeBattlePassMissionPointRsp, func() any { return new(proto.TakeBattlePassMissionPointRsp) })
	c.regMsg(GetBattlePassProductReq, func() any { return new(proto.GetBattlePassProductReq) })
	c.regMsg(GetBattlePassProductRsp, func() any { return new(proto.GetBattlePassProductRsp) })
	c.regMsg(SetBattlePassViewedReq, func() any { return new(proto.SetBattlePassViewedReq) })
	c.regMsg(SetBattlePassViewedRsp, func() any { return new(proto.SetBattlePassViewedRsp) })
	c.regMsg(BattlePassBuySuccNotify, func() any { return new(proto.BattlePassBuySuccNotify) })
	c.regMsg(BuyBattlePassLevelReq, func() any { return new(proto.BuyBattlePassLevelReq) })
	c.regMsg(BuyBattlePassLevelRsp, func() any { return new(proto.BuyBattlePassLevelRsp) })
	c.regMsg(TowerBriefDataNotify, func() any { return new(proto.TowerBriefDataNotify) })
	c.regMsg(TowerFloorRecordChangeNotify, func() any { return new(proto.TowerFloorRecordChangeNotify) })
	c.regMsg(TowerCurLevelRecordChangeNotify, func() any { return new(proto.TowerCurLevelRecordChangeNotify) })
	c.regMsg(TowerDailyRewardProgressChangeNotify, func() any { return new(proto.TowerDailyRewardProgressChangeNotify) })
	c.regMsg(TowerTeamSelectReq, func() any { return new(proto.TowerTeamSelectReq) })
	c.regMsg(TowerTeamSelectRsp, func() any { return new(proto.TowerTeamSelectRsp) })
	c.regMsg(TowerAllDataReq, func() any { return new(proto.TowerAllDataReq) })
	c.regMsg(TowerAllDataRsp, func() any { return new(proto.TowerAllDataRsp) })
	c.regMsg(TowerEnterLevelReq, func() any { return new(proto.TowerEnterLevelReq) })
	c.regMsg(TowerEnterLevelRsp, func() any { return new(proto.TowerEnterLevelRsp) })
	c.regMsg(TowerBuffSelectReq, func() any { return new(proto.TowerBuffSelectReq) })
	c.regMsg(TowerBuffSelectRsp, func() any { return new(proto.TowerBuffSelectRsp) })
	c.regMsg(TowerSurrenderReq, func() any { return new(proto.TowerSurrenderReq) })
	c.regMsg(TowerSurrenderRsp, func() any { return new(proto.TowerSurrenderRsp) })
	c.regMsg(TowerGetFloorStarRewardReq, func() any { return new(proto.TowerGetFloorStarRewardReq) })
	c.regMsg(TowerGetFloorStarRewardRsp, func() any { return new(proto.TowerGetFloorStarRewardRsp) })
	c.regMsg(TowerLevelEndNotify, func() any { return new(proto.TowerLevelEndNotify) })
	c.regMsg(TowerLevelStarCondNotify, func() any { return new(proto.TowerLevelStarCondNotify) })
	c.regMsg(TowerMiddleLevelChangeTeamNotify, func() any { return new(proto.TowerMiddleLevelChangeTeamNotify) })
	c.regMsg(TowerRecordHandbookReq, func() any { return new(proto.TowerRecordHandbookReq) })
	c.regMsg(TowerRecordHandbookRsp, func() any { return new(proto.TowerRecordHandbookRsp) })
	c.regMsg(WatcherAllDataNotify, func() any { return new(proto.WatcherAllDataNotify) })
	c.regMsg(WatcherChangeNotify, func() any { return new(proto.WatcherChangeNotify) })
	c.regMsg(WatcherEventNotify, func() any { return new(proto.WatcherEventNotify) })
	c.regMsg(WatcherEventTypeNotify, func() any { return new(proto.WatcherEventTypeNotify) })
	c.regMsg(PushTipsAllDataNotify, func() any { return new(proto.PushTipsAllDataNotify) })
	c.regMsg(PushTipsChangeNotify, func() any { return new(proto.PushTipsChangeNotify) })
	c.regMsg(PushTipsReadFinishReq, func() any { return new(proto.PushTipsReadFinishReq) })
	c.regMsg(PushTipsReadFinishRsp, func() any { return new(proto.PushTipsReadFinishRsp) })
	c.regMsg(GetPushTipsRewardReq, func() any { return new(proto.GetPushTipsRewardReq) })
	c.regMsg(GetPushTipsRewardRsp, func() any { return new(proto.GetPushTipsRewardRsp) })
	c.regMsg(GetBlossomBriefInfoListReq, func() any { return new(proto.GetBlossomBriefInfoListReq) })
	c.regMsg(GetBlossomBriefInfoListRsp, func() any { return new(proto.GetBlossomBriefInfoListRsp) })
	c.regMsg(BlossomBriefInfoNotify, func() any { return new(proto.BlossomBriefInfoNotify) })
	c.regMsg(WorldOwnerBlossomBriefInfoNotify, func() any { return new(proto.WorldOwnerBlossomBriefInfoNotify) })
	c.regMsg(WorldOwnerBlossomScheduleInfoNotify, func() any { return new(proto.WorldOwnerBlossomScheduleInfoNotify) })
	c.regMsg(BlossomChestCreateNotify, func() any { return new(proto.BlossomChestCreateNotify) })
	c.regMsg(OpenBlossomCircleCampGuideNotify, func() any { return new(proto.OpenBlossomCircleCampGuideNotify) })
	c.regMsg(CodexDataFullNotify, func() any { return new(proto.CodexDataFullNotify) })
	c.regMsg(CodexDataUpdataNotify, func() any { return new(proto.CodexDataUpdataNotify) })
	c.regMsg(QueryCodexMonsterBeKilledNumReq, func() any { return new(proto.QueryCodexMonsterBeKilledNumReq) })
	c.regMsg(QueryCodexMonsterBeKilledNumRsp, func() any { return new(proto.QueryCodexMonsterBeKilledNumRsp) })
	c.regMsg(DungeonEntryInfoReq, func() any { return new(proto.DungeonEntryInfoReq) })
	c.regMsg(DungeonEntryInfoRsp, func() any { return new(proto.DungeonEntryInfoRsp) })
	c.regMsg(PlayerEnterDungeonReq, func() any { return new(proto.PlayerEnterDungeonReq) })
	c.regMsg(PlayerEnterDungeonRsp, func() any { return new(proto.PlayerEnterDungeonRsp) })
	c.regMsg(PlayerQuitDungeonReq, func() any { return new(proto.PlayerQuitDungeonReq) })
	c.regMsg(PlayerQuitDungeonRsp, func() any { return new(proto.PlayerQuitDungeonRsp) })
	c.regMsg(DungeonWayPointNotify, func() any { return new(proto.DungeonWayPointNotify) })
	c.regMsg(DungeonWayPointActivateReq, func() any { return new(proto.DungeonWayPointActivateReq) })
	c.regMsg(DungeonWayPointActivateRsp, func() any { return new(proto.DungeonWayPointActivateRsp) })
	c.regMsg(DungeonSettleNotify, func() any { return new(proto.DungeonSettleNotify) })
	c.regMsg(DungeonPlayerDieNotify, func() any { return new(proto.DungeonPlayerDieNotify) })
	c.regMsg(DungeonDieOptionReq, func() any { return new(proto.DungeonDieOptionReq) })
	c.regMsg(DungeonDieOptionRsp, func() any { return new(proto.DungeonDieOptionRsp) })
	c.regMsg(DungeonShowReminderNotify, func() any { return new(proto.DungeonShowReminderNotify) })
	c.regMsg(DungeonPlayerDieReq, func() any { return new(proto.DungeonPlayerDieReq) })
	c.regMsg(DungeonPlayerDieRsp, func() any { return new(proto.DungeonPlayerDieRsp) })
	c.regMsg(DungeonDataNotify, func() any { return new(proto.DungeonDataNotify) })
	c.regMsg(DungeonChallengeBeginNotify, func() any { return new(proto.DungeonChallengeBeginNotify) })
	c.regMsg(DungeonChallengeFinishNotify, func() any { return new(proto.DungeonChallengeFinishNotify) })
	c.regMsg(ChallengeDataNotify, func() any { return new(proto.ChallengeDataNotify) })
	c.regMsg(DungeonFollowNotify, func() any { return new(proto.DungeonFollowNotify) })
	c.regMsg(DungeonGetStatueDropReq, func() any { return new(proto.DungeonGetStatueDropReq) })
	c.regMsg(DungeonGetStatueDropRsp, func() any { return new(proto.DungeonGetStatueDropRsp) })
	c.regMsg(ChallengeRecordNotify, func() any { return new(proto.ChallengeRecordNotify) })
	c.regMsg(DungeonCandidateTeamInfoNotify, func() any { return new(proto.DungeonCandidateTeamInfoNotify) })
	c.regMsg(DungeonCandidateTeamInviteNotify, func() any { return new(proto.DungeonCandidateTeamInviteNotify) })
	c.regMsg(DungeonCandidateTeamRefuseNotify, func() any { return new(proto.DungeonCandidateTeamRefuseNotify) })
	c.regMsg(DungeonCandidateTeamPlayerLeaveNotify, func() any { return new(proto.DungeonCandidateTeamPlayerLeaveNotify) })
	c.regMsg(DungeonCandidateTeamDismissNotify, func() any { return new(proto.DungeonCandidateTeamDismissNotify) })
	c.regMsg(DungeonCandidateTeamCreateReq, func() any { return new(proto.DungeonCandidateTeamCreateReq) })
	c.regMsg(DungeonCandidateTeamCreateRsp, func() any { return new(proto.DungeonCandidateTeamCreateRsp) })
	c.regMsg(DungeonCandidateTeamInviteReq, func() any { return new(proto.DungeonCandidateTeamInviteReq) })
	c.regMsg(DungeonCandidateTeamInviteRsp, func() any { return new(proto.DungeonCandidateTeamInviteRsp) })
	c.regMsg(DungeonCandidateTeamKickReq, func() any { return new(proto.DungeonCandidateTeamKickReq) })
	c.regMsg(DungeonCandidateTeamKickRsp, func() any { return new(proto.DungeonCandidateTeamKickRsp) })
	c.regMsg(DungeonCandidateTeamLeaveReq, func() any { return new(proto.DungeonCandidateTeamLeaveReq) })
	c.regMsg(DungeonCandidateTeamLeaveRsp, func() any { return new(proto.DungeonCandidateTeamLeaveRsp) })
	c.regMsg(DungeonCandidateTeamReplyInviteReq, func() any { return new(proto.DungeonCandidateTeamReplyInviteReq) })
	c.regMsg(DungeonCandidateTeamReplyInviteRsp, func() any { return new(proto.DungeonCandidateTeamReplyInviteRsp) })
	c.regMsg(DungeonCandidateTeamSetReadyReq, func() any { return new(proto.DungeonCandidateTeamSetReadyReq) })
	c.regMsg(DungeonCandidateTeamSetReadyRsp, func() any { return new(proto.DungeonCandidateTeamSetReadyRsp) })
	c.regMsg(DungeonCandidateTeamChangeAvatarReq, func() any { return new(proto.DungeonCandidateTeamChangeAvatarReq) })
	c.regMsg(DungeonCandidateTeamChangeAvatarRsp, func() any { return new(proto.DungeonCandidateTeamChangeAvatarRsp) })
	c.regMsg(GetDailyDungeonEntryInfoReq, func() any { return new(proto.GetDailyDungeonEntryInfoReq) })
	c.regMsg(GetDailyDungeonEntryInfoRsp, func() any { return new(proto.GetDailyDungeonEntryInfoRsp) })
	c.regMsg(DungeonSlipRevivePointActivateReq, func() any { return new(proto.DungeonSlipRevivePointActivateReq) })
	c.regMsg(DungeonSlipRevivePointActivateRsp, func() any { return new(proto.DungeonSlipRevivePointActivateRsp) })
	c.regMsg(DungeonInterruptChallengeReq, func() any { return new(proto.DungeonInterruptChallengeReq) })
	c.regMsg(DungeonInterruptChallengeRsp, func() any { return new(proto.DungeonInterruptChallengeRsp) })
	c.regMsg(InteractDailyDungeonInfoNotify, func() any { return new(proto.InteractDailyDungeonInfoNotify) })
	c.regMsg(EvtBeingHitNotify, func() any { return new(proto.EvtBeingHitNotify) })
	c.regMsg(EvtAnimatorParameterNotify, func() any { return new(proto.EvtAnimatorParameterNotify) })
	c.regMsg(HostPlayerNotify, func() any { return new(proto.HostPlayerNotify) })
	c.regMsg(EvtDoSkillSuccNotify, func() any { return new(proto.EvtDoSkillSuccNotify) })
	c.regMsg(EvtCreateGadgetNotify, func() any { return new(proto.EvtCreateGadgetNotify) })
	c.regMsg(EvtDestroyGadgetNotify, func() any { return new(proto.EvtDestroyGadgetNotify) })
	c.regMsg(EvtFaceToEntityNotify, func() any { return new(proto.EvtFaceToEntityNotify) })
	c.regMsg(EvtFaceToDirNotify, func() any { return new(proto.EvtFaceToDirNotify) })
	c.regMsg(EvtCostStaminaNotify, func() any { return new(proto.EvtCostStaminaNotify) })
	c.regMsg(EvtSetAttackTargetNotify, func() any { return new(proto.EvtSetAttackTargetNotify) })
	c.regMsg(EvtAnimatorStateChangedNotify, func() any { return new(proto.EvtAnimatorStateChangedNotify) })
	c.regMsg(EvtRushMoveNotify, func() any { return new(proto.EvtRushMoveNotify) })
	c.regMsg(EvtBulletHitNotify, func() any { return new(proto.EvtBulletHitNotify) })
	c.regMsg(EvtBulletDeactiveNotify, func() any { return new(proto.EvtBulletDeactiveNotify) })
	c.regMsg(EvtEntityStartDieEndNotify, func() any { return new(proto.EvtEntityStartDieEndNotify) })
	c.regMsg(EvtBulletMoveNotify, func() any { return new(proto.EvtBulletMoveNotify) })
	c.regMsg(EvtAvatarEnterFocusNotify, func() any { return new(proto.EvtAvatarEnterFocusNotify) })
	c.regMsg(EvtAvatarExitFocusNotify, func() any { return new(proto.EvtAvatarExitFocusNotify) })
	c.regMsg(EvtAvatarUpdateFocusNotify, func() any { return new(proto.EvtAvatarUpdateFocusNotify) })
	c.regMsg(EntityAuthorityChangeNotify, func() any { return new(proto.EntityAuthorityChangeNotify) })
	c.regMsg(AvatarBuffAddNotify, func() any { return new(proto.AvatarBuffAddNotify) })
	c.regMsg(AvatarBuffDelNotify, func() any { return new(proto.AvatarBuffDelNotify) })
	c.regMsg(MonsterAlertChangeNotify, func() any { return new(proto.MonsterAlertChangeNotify) })
	c.regMsg(MonsterForceAlertNotify, func() any { return new(proto.MonsterForceAlertNotify) })
	c.regMsg(AvatarEnterElementViewNotify, func() any { return new(proto.AvatarEnterElementViewNotify) })
	c.regMsg(TriggerCreateGadgetToEquipPartNotify, func() any { return new(proto.TriggerCreateGadgetToEquipPartNotify) })
	c.regMsg(EvtEntityRenderersChangedNotify, func() any { return new(proto.EvtEntityRenderersChangedNotify) })
	c.regMsg(AnimatorForceSetAirMoveNotify, func() any { return new(proto.AnimatorForceSetAirMoveNotify) })
	c.regMsg(EvtAiSyncSkillCdNotify, func() any { return new(proto.EvtAiSyncSkillCdNotify) })
	c.regMsg(EvtBeingHitsCombineNotify, func() any { return new(proto.EvtBeingHitsCombineNotify) })
	c.regMsg(EvtAvatarSitDownNotify, func() any { return new(proto.EvtAvatarSitDownNotify) })
	c.regMsg(EvtAvatarStandUpNotify, func() any { return new(proto.EvtAvatarStandUpNotify) })
	c.regMsg(CreateMassiveEntityReq, func() any { return new(proto.CreateMassiveEntityReq) })
	c.regMsg(CreateMassiveEntityRsp, func() any { return new(proto.CreateMassiveEntityRsp) })
	c.regMsg(CreateMassiveEntityNotify, func() any { return new(proto.CreateMassiveEntityNotify) })
	c.regMsg(DestroyMassiveEntityNotify, func() any { return new(proto.DestroyMassiveEntityNotify) })
	c.regMsg(MassiveEntityStateChangedNotify, func() any { return new(proto.MassiveEntityStateChangedNotify) })
	c.regMsg(SyncTeamEntityNotify, func() any { return new(proto.SyncTeamEntityNotify) })
	c.regMsg(DelTeamEntityNotify, func() any { return new(proto.DelTeamEntityNotify) })
	c.regMsg(CombatInvocationsNotify, func() any { return new(proto.CombatInvocationsNotify) })
	c.regMsg(ServerBuffChangeNotify, func() any { return new(proto.ServerBuffChangeNotify) })
	c.regMsg(EvtAiSyncCombatThreatInfoNotify, func() any { return new(proto.EvtAiSyncCombatThreatInfoNotify) })
	c.regMsg(MassiveEntityElementOpBatchNotify, func() any { return new(proto.MassiveEntityElementOpBatchNotify) })
	c.regMsg(EntityAiSyncNotify, func() any { return new(proto.EntityAiSyncNotify) })
	c.regMsg(GetGachaInfoReq, func() any { return new(proto.GetGachaInfoReq) })
	c.regMsg(GetGachaInfoRsp, func() any { return new(proto.GetGachaInfoRsp) })
	c.regMsg(DoGachaReq, func() any { return new(proto.DoGachaReq) })
	c.regMsg(DoGachaRsp, func() any { return new(proto.DoGachaRsp) })
	c.regMsg(GadgetInteractReq, func() any { return new(proto.GadgetInteractReq) })
	c.regMsg(GadgetInteractRsp, func() any { return new(proto.GadgetInteractRsp) })
	c.regMsg(GadgetStateNotify, func() any { return new(proto.GadgetStateNotify) })
	c.regMsg(WorktopOptionNotify, func() any { return new(proto.WorktopOptionNotify) })
	c.regMsg(SelectWorktopOptionReq, func() any { return new(proto.SelectWorktopOptionReq) })
	c.regMsg(SelectWorktopOptionRsp, func() any { return new(proto.SelectWorktopOptionRsp) })
	c.regMsg(BossChestActivateNotify, func() any { return new(proto.BossChestActivateNotify) })
	c.regMsg(BlossomChestInfoNotify, func() any { return new(proto.BlossomChestInfoNotify) })
	c.regMsg(GadgetPlayStartNotify, func() any { return new(proto.GadgetPlayStartNotify) })
	c.regMsg(GadgetPlayStopNotify, func() any { return new(proto.GadgetPlayStopNotify) })
	c.regMsg(GadgetPlayDataNotify, func() any { return new(proto.GadgetPlayDataNotify) })
	c.regMsg(GadgetPlayUidOpNotify, func() any { return new(proto.GadgetPlayUidOpNotify) })
	c.regMsg(PlayerInvestigationAllInfoNotify, func() any { return new(proto.PlayerInvestigationAllInfoNotify) })
	c.regMsg(TakeInvestigationRewardReq, func() any { return new(proto.TakeInvestigationRewardReq) })
	c.regMsg(TakeInvestigationRewardRsp, func() any { return new(proto.TakeInvestigationRewardRsp) })
	c.regMsg(TakeInvestigationTargetRewardReq, func() any { return new(proto.TakeInvestigationTargetRewardReq) })
	c.regMsg(TakeInvestigationTargetRewardRsp, func() any { return new(proto.TakeInvestigationTargetRewardRsp) })
	c.regMsg(GetInvestigationMonsterReq, func() any { return new(proto.GetInvestigationMonsterReq) })
	c.regMsg(GetInvestigationMonsterRsp, func() any { return new(proto.GetInvestigationMonsterRsp) })
	c.regMsg(PlayerInvestigationNotify, func() any { return new(proto.PlayerInvestigationNotify) })
	c.regMsg(PlayerInvestigationTargetNotify, func() any { return new(proto.PlayerInvestigationTargetNotify) })
	c.regMsg(PlayerStoreNotify, func() any { return new(proto.PlayerStoreNotify) })
	c.regMsg(StoreWeightLimitNotify, func() any { return new(proto.StoreWeightLimitNotify) })
	c.regMsg(StoreItemChangeNotify, func() any { return new(proto.StoreItemChangeNotify) })
	c.regMsg(StoreItemDelNotify, func() any { return new(proto.StoreItemDelNotify) })
	c.regMsg(ItemAddHintNotify, func() any { return new(proto.ItemAddHintNotify) })
	c.regMsg(UseItemReq, func() any { return new(proto.UseItemReq) })
	c.regMsg(UseItemRsp, func() any { return new(proto.UseItemRsp) })
	c.regMsg(DropItemReq, func() any { return new(proto.DropItemReq) })
	c.regMsg(DropItemRsp, func() any { return new(proto.DropItemRsp) })
	c.regMsg(WearEquipReq, func() any { return new(proto.WearEquipReq) })
	c.regMsg(WearEquipRsp, func() any { return new(proto.WearEquipRsp) })
	c.regMsg(TakeoffEquipReq, func() any { return new(proto.TakeoffEquipReq) })
	c.regMsg(TakeoffEquipRsp, func() any { return new(proto.TakeoffEquipRsp) })
	c.regMsg(AvatarEquipChangeNotify, func() any { return new(proto.AvatarEquipChangeNotify) })
	c.regMsg(WeaponUpgradeReq, func() any { return new(proto.WeaponUpgradeReq) })
	c.regMsg(WeaponUpgradeRsp, func() any { return new(proto.WeaponUpgradeRsp) })
	c.regMsg(WeaponPromoteReq, func() any { return new(proto.WeaponPromoteReq) })
	c.regMsg(WeaponPromoteRsp, func() any { return new(proto.WeaponPromoteRsp) })
	c.regMsg(ReliquaryUpgradeReq, func() any { return new(proto.ReliquaryUpgradeReq) })
	c.regMsg(ReliquaryUpgradeRsp, func() any { return new(proto.ReliquaryUpgradeRsp) })
	c.regMsg(ReliquaryPromoteReq, func() any { return new(proto.ReliquaryPromoteReq) })
	c.regMsg(ReliquaryPromoteRsp, func() any { return new(proto.ReliquaryPromoteRsp) })
	c.regMsg(AvatarCardChangeReq, func() any { return new(proto.AvatarCardChangeReq) })
	c.regMsg(AvatarCardChangeRsp, func() any { return new(proto.AvatarCardChangeRsp) })
	c.regMsg(GrantRewardNotify, func() any { return new(proto.GrantRewardNotify) })
	c.regMsg(WeaponAwakenReq, func() any { return new(proto.WeaponAwakenReq) })
	c.regMsg(WeaponAwakenRsp, func() any { return new(proto.WeaponAwakenRsp) })
	c.regMsg(ItemCdGroupTimeNotify, func() any { return new(proto.ItemCdGroupTimeNotify) })
	c.regMsg(DropHintNotify, func() any { return new(proto.DropHintNotify) })
	c.regMsg(CombineReq, func() any { return new(proto.CombineReq) })
	c.regMsg(CombineRsp, func() any { return new(proto.CombineRsp) })
	c.regMsg(ForgeQueueDataNotify, func() any { return new(proto.ForgeQueueDataNotify) })
	c.regMsg(ForgeGetQueueDataReq, func() any { return new(proto.ForgeGetQueueDataReq) })
	c.regMsg(ForgeGetQueueDataRsp, func() any { return new(proto.ForgeGetQueueDataRsp) })
	c.regMsg(ForgeStartReq, func() any { return new(proto.ForgeStartReq) })
	c.regMsg(ForgeStartRsp, func() any { return new(proto.ForgeStartRsp) })
	c.regMsg(ForgeQueueManipulateReq, func() any { return new(proto.ForgeQueueManipulateReq) })
	c.regMsg(ForgeQueueManipulateRsp, func() any { return new(proto.ForgeQueueManipulateRsp) })
	c.regMsg(ResinChangeNotify, func() any { return new(proto.ResinChangeNotify) })
	c.regMsg(BuyResinReq, func() any { return new(proto.BuyResinReq) })
	c.regMsg(BuyResinRsp, func() any { return new(proto.BuyResinRsp) })
	c.regMsg(MaterialDeleteReturnNotify, func() any { return new(proto.MaterialDeleteReturnNotify) })
	c.regMsg(TakeMaterialDeleteReturnReq, func() any { return new(proto.TakeMaterialDeleteReturnReq) })
	c.regMsg(TakeMaterialDeleteReturnRsp, func() any { return new(proto.TakeMaterialDeleteReturnRsp) })
	c.regMsg(MaterialDeleteUpdateNotify, func() any { return new(proto.MaterialDeleteUpdateNotify) })
	c.regMsg(McoinExchangeHcoinReq, func() any { return new(proto.McoinExchangeHcoinReq) })
	c.regMsg(McoinExchangeHcoinRsp, func() any { return new(proto.McoinExchangeHcoinRsp) })
	c.regMsg(DestroyMaterialReq, func() any { return new(proto.DestroyMaterialReq) })
	c.regMsg(DestroyMaterialRsp, func() any { return new(proto.DestroyMaterialRsp) })
	c.regMsg(MailChangeNotify, func() any { return new(proto.MailChangeNotify) })
	c.regMsg(ReadMailNotify, func() any { return new(proto.ReadMailNotify) })
	c.regMsg(GetMailItemReq, func() any { return new(proto.GetMailItemReq) })
	c.regMsg(GetMailItemRsp, func() any { return new(proto.GetMailItemRsp) })
	c.regMsg(DelMailReq, func() any { return new(proto.DelMailReq) })
	c.regMsg(DelMailRsp, func() any { return new(proto.DelMailRsp) })
	c.regMsg(GetAuthkeyReq, func() any { return new(proto.GetAuthkeyReq) })
	c.regMsg(GetAuthkeyRsp, func() any { return new(proto.GetAuthkeyRsp) })
	c.regMsg(ClientNewMailNotify, func() any { return new(proto.ClientNewMailNotify) })
	c.regMsg(GetAllMailReq, func() any { return new(proto.GetAllMailReq) })
	c.regMsg(GetAllMailRsp, func() any { return new(proto.GetAllMailRsp) })
	c.regMsg(PlayerStartMatchReq, func() any { return new(proto.PlayerStartMatchReq) })
	c.regMsg(PlayerStartMatchRsp, func() any { return new(proto.PlayerStartMatchRsp) })
	c.regMsg(PlayerMatchInfoNotify, func() any { return new(proto.PlayerMatchInfoNotify) })
	c.regMsg(PlayerCancelMatchReq, func() any { return new(proto.PlayerCancelMatchReq) })
	c.regMsg(PlayerCancelMatchRsp, func() any { return new(proto.PlayerCancelMatchRsp) })
	c.regMsg(PlayerMatchStopNotify, func() any { return new(proto.PlayerMatchStopNotify) })
	c.regMsg(PlayerMatchSuccNotify, func() any { return new(proto.PlayerMatchSuccNotify) })
	c.regMsg(PlayerConfirmMatchReq, func() any { return new(proto.PlayerConfirmMatchReq) })
	c.regMsg(PlayerConfirmMatchRsp, func() any { return new(proto.PlayerConfirmMatchRsp) })
	c.regMsg(PlayerAllowEnterMpAfterAgreeMatchNotify, func() any { return new(proto.PlayerAllowEnterMpAfterAgreeMatchNotify) })
	c.regMsg(PlayerMatchAgreedResultNotify, func() any { return new(proto.PlayerMatchAgreedResultNotify) })
	c.regMsg(PlayerApplyEnterMpAfterMatchAgreedNotify, func() any { return new(proto.PlayerApplyEnterMpAfterMatchAgreedNotify) })
	c.regMsg(KeepAliveNotify, func() any { return new(proto.KeepAliveNotify) })
	c.regMsg(GmTalkReq, func() any { return new(proto.GmTalkReq) })
	c.regMsg(GmTalkRsp, func() any { return new(proto.GmTalkRsp) })
	c.regMsg(ShowMessageNotify, func() any { return new(proto.ShowMessageNotify) })
	c.regMsg(PingReq, func() any { return new(proto.PingReq) })
	c.regMsg(PingRsp, func() any { return new(proto.PingRsp) })
	c.regMsg(GetOnlinePlayerListReq, func() any { return new(proto.GetOnlinePlayerListReq) })
	c.regMsg(GetOnlinePlayerListRsp, func() any { return new(proto.GetOnlinePlayerListRsp) })
	c.regMsg(ServerTimeNotify, func() any { return new(proto.ServerTimeNotify) })
	c.regMsg(ServerLogNotify, func() any { return new(proto.ServerLogNotify) })
	c.regMsg(ClientReconnectNotify, func() any { return new(proto.ClientReconnectNotify) })
	c.regMsg(RobotPushPlayerDataNotify, func() any { return new(proto.RobotPushPlayerDataNotify) })
	c.regMsg(ClientReportNotify, func() any { return new(proto.ClientReportNotify) })
	c.regMsg(UnionCmdNotify, func() any { return new(proto.UnionCmdNotify) })
	c.regMsg(GetOnlinePlayerInfoReq, func() any { return new(proto.GetOnlinePlayerInfoReq) })
	c.regMsg(GetOnlinePlayerInfoRsp, func() any { return new(proto.GetOnlinePlayerInfoRsp) })
	c.regMsg(CheckSegmentCRCNotify, func() any { return new(proto.CheckSegmentCRCNotify) })
	c.regMsg(CheckSegmentCRCReq, func() any { return new(proto.CheckSegmentCRCReq) })
	c.regMsg(WorldPlayerRTTNotify, func() any { return new(proto.WorldPlayerRTTNotify) })
	c.regMsg(EchoNotify, func() any { return new(proto.EchoNotify) })
	c.regMsg(MonsterSummonTagNotify, func() any { return new(proto.MonsterSummonTagNotify) })
	c.regMsg(PlayerApplyEnterMpNotify, func() any { return new(proto.PlayerApplyEnterMpNotify) })
	c.regMsg(PlayerApplyEnterMpReq, func() any { return new(proto.PlayerApplyEnterMpReq) })
	c.regMsg(PlayerApplyEnterMpRsp, func() any { return new(proto.PlayerApplyEnterMpRsp) })
	c.regMsg(PlayerApplyEnterMpResultNotify, func() any { return new(proto.PlayerApplyEnterMpResultNotify) })
	c.regMsg(PlayerApplyEnterMpResultReq, func() any { return new(proto.PlayerApplyEnterMpResultReq) })
	c.regMsg(PlayerApplyEnterMpResultRsp, func() any { return new(proto.PlayerApplyEnterMpResultRsp) })
	c.regMsg(PlayerQuitFromMpNotify, func() any { return new(proto.PlayerQuitFromMpNotify) })
	c.regMsg(PlayerPreEnterMpNotify, func() any { return new(proto.PlayerPreEnterMpNotify) })
	c.regMsg(GetPlayerMpModeAvailabilityReq, func() any { return new(proto.GetPlayerMpModeAvailabilityReq) })
	c.regMsg(GetPlayerMpModeAvailabilityRsp, func() any { return new(proto.GetPlayerMpModeAvailabilityRsp) })
	c.regMsg(PlayerSetOnlyMPWithPSPlayerReq, func() any { return new(proto.PlayerSetOnlyMPWithPSPlayerReq) })
	c.regMsg(PlayerSetOnlyMPWithPSPlayerRsp, func() any { return new(proto.PlayerSetOnlyMPWithPSPlayerRsp) })
	c.regMsg(PSPlayerApplyEnterMpReq, func() any { return new(proto.PSPlayerApplyEnterMpReq) })
	c.regMsg(PSPlayerApplyEnterMpRsp, func() any { return new(proto.PSPlayerApplyEnterMpRsp) })
	c.regMsg(MpPlayOwnerCheckReq, func() any { return new(proto.MpPlayOwnerCheckReq) })
	c.regMsg(MpPlayOwnerCheckRsp, func() any { return new(proto.MpPlayOwnerCheckRsp) })
	c.regMsg(MpPlayOwnerStartInviteReq, func() any { return new(proto.MpPlayOwnerStartInviteReq) })
	c.regMsg(MpPlayOwnerStartInviteRsp, func() any { return new(proto.MpPlayOwnerStartInviteRsp) })
	c.regMsg(MpPlayOwnerInviteNotify, func() any { return new(proto.MpPlayOwnerInviteNotify) })
	c.regMsg(MpPlayGuestReplyInviteReq, func() any { return new(proto.MpPlayGuestReplyInviteReq) })
	c.regMsg(MpPlayGuestReplyInviteRsp, func() any { return new(proto.MpPlayGuestReplyInviteRsp) })
	c.regMsg(MpPlayGuestReplyNotify, func() any { return new(proto.MpPlayGuestReplyNotify) })
	c.regMsg(MpPlayPrepareNotify, func() any { return new(proto.MpPlayPrepareNotify) })
	c.regMsg(MpPlayInviteResultNotify, func() any { return new(proto.MpPlayInviteResultNotify) })
	c.regMsg(MpPlayPrepareInterruptNotify, func() any { return new(proto.MpPlayPrepareInterruptNotify) })
	c.regMsg(NpcTalkReq, func() any { return new(proto.NpcTalkReq) })
	c.regMsg(NpcTalkRsp, func() any { return new(proto.NpcTalkRsp) })
	c.regMsg(GetSceneNpcPositionReq, func() any { return new(proto.GetSceneNpcPositionReq) })
	c.regMsg(GetSceneNpcPositionRsp, func() any { return new(proto.GetSceneNpcPositionRsp) })
	c.regMsg(QueryPathReq, func() any { return new(proto.QueryPathReq) })
	c.regMsg(QueryPathRsp, func() any { return new(proto.QueryPathRsp) })
	c.regMsg(ObstacleModifyNotify, func() any { return new(proto.ObstacleModifyNotify) })
	c.regMsg(PathfindingPingNotify, func() any { return new(proto.PathfindingPingNotify) })
	c.regMsg(PathfindingEnterSceneReq, func() any { return new(proto.PathfindingEnterSceneReq) })
	c.regMsg(PathfindingEnterSceneRsp, func() any { return new(proto.PathfindingEnterSceneRsp) })
	c.regMsg(GMShowObstacleReq, func() any { return new(proto.GMShowObstacleReq) })
	c.regMsg(GMShowObstacleRsp, func() any { return new(proto.GMShowObstacleRsp) })
	c.regMsg(GMShowNavMeshReq, func() any { return new(proto.GMShowNavMeshReq) })
	c.regMsg(GMShowNavMeshRsp, func() any { return new(proto.GMShowNavMeshRsp) })
	c.regMsg(NavMeshStatsNotify, func() any { return new(proto.NavMeshStatsNotify) })
	c.regMsg(GetPlayerTokenRsp, func() any { return new(proto.GetPlayerTokenRsp) })
	c.regMsg(PlayerLoginReq, func() any { return new(proto.PlayerLoginReq) })
	c.regMsg(PlayerLoginRsp, func() any { return new(proto.PlayerLoginRsp) })
	c.regMsg(PlayerLogoutReq, func() any { return new(proto.PlayerLogoutReq) })
	c.regMsg(PlayerLogoutRsp, func() any { return new(proto.PlayerLogoutRsp) })
	c.regMsg(PlayerLogoutNotify, func() any { return new(proto.PlayerLogoutNotify) })
	c.regMsg(PlayerDataNotify, func() any { return new(proto.PlayerDataNotify) })
	c.regMsg(ChangeGameTimeReq, func() any { return new(proto.ChangeGameTimeReq) })
	c.regMsg(ChangeGameTimeRsp, func() any { return new(proto.ChangeGameTimeRsp) })
	c.regMsg(PlayerGameTimeNotify, func() any { return new(proto.PlayerGameTimeNotify) })
	c.regMsg(PlayerPropNotify, func() any { return new(proto.PlayerPropNotify) })
	c.regMsg(ClientTriggerEventNotify, func() any { return new(proto.ClientTriggerEventNotify) })
	c.regMsg(SetPlayerPropReq, func() any { return new(proto.SetPlayerPropReq) })
	c.regMsg(SetPlayerPropRsp, func() any { return new(proto.SetPlayerPropRsp) })
	c.regMsg(SetPlayerBornDataReq, func() any { return new(proto.SetPlayerBornDataReq) })
	c.regMsg(SetPlayerBornDataRsp, func() any { return new(proto.SetPlayerBornDataRsp) })
	c.regMsg(DoSetPlayerBornDataNotify, func() any { return new(proto.DoSetPlayerBornDataNotify) })
	c.regMsg(PlayerPropChangeNotify, func() any { return new(proto.PlayerPropChangeNotify) })
	c.regMsg(SetPlayerNameReq, func() any { return new(proto.SetPlayerNameReq) })
	c.regMsg(SetPlayerNameRsp, func() any { return new(proto.SetPlayerNameRsp) })
	c.regMsg(SetOpenStateReq, func() any { return new(proto.SetOpenStateReq) })
	c.regMsg(SetOpenStateRsp, func() any { return new(proto.SetOpenStateRsp) })
	c.regMsg(OpenStateUpdateNotify, func() any { return new(proto.OpenStateUpdateNotify) })
	c.regMsg(OpenStateChangeNotify, func() any { return new(proto.OpenStateChangeNotify) })
	c.regMsg(PlayerCookReq, func() any { return new(proto.PlayerCookReq) })
	c.regMsg(PlayerCookRsp, func() any { return new(proto.PlayerCookRsp) })
	c.regMsg(PlayerRandomCookReq, func() any { return new(proto.PlayerRandomCookReq) })
	c.regMsg(PlayerRandomCookRsp, func() any { return new(proto.PlayerRandomCookRsp) })
	c.regMsg(CookDataNotify, func() any { return new(proto.CookDataNotify) })
	c.regMsg(CookRecipeDataNotify, func() any { return new(proto.CookRecipeDataNotify) })
	c.regMsg(CookGradeDataNotify, func() any { return new(proto.CookGradeDataNotify) })
	c.regMsg(PlayerCompoundMaterialReq, func() any { return new(proto.PlayerCompoundMaterialReq) })
	c.regMsg(PlayerCompoundMaterialRsp, func() any { return new(proto.PlayerCompoundMaterialRsp) })
	c.regMsg(TakeCompoundOutputReq, func() any { return new(proto.TakeCompoundOutputReq) })
	c.regMsg(TakeCompoundOutputRsp, func() any { return new(proto.TakeCompoundOutputRsp) })
	c.regMsg(CompoundDataNotify, func() any { return new(proto.CompoundDataNotify) })
	c.regMsg(GetCompoundDataReq, func() any { return new(proto.GetCompoundDataReq) })
	c.regMsg(GetCompoundDataRsp, func() any { return new(proto.GetCompoundDataRsp) })
	c.regMsg(PlayerTimeNotify, func() any { return new(proto.PlayerTimeNotify) })
	c.regMsg(PlayerSetPauseReq, func() any { return new(proto.PlayerSetPauseReq) })
	c.regMsg(PlayerSetPauseRsp, func() any { return new(proto.PlayerSetPauseRsp) })
	c.regMsg(PlayerSetLanguageReq, func() any { return new(proto.PlayerSetLanguageReq) })
	c.regMsg(PlayerSetLanguageRsp, func() any { return new(proto.PlayerSetLanguageRsp) })
	c.regMsg(DataResVersionNotify, func() any { return new(proto.DataResVersionNotify) })
	c.regMsg(DailyTaskDataNotify, func() any { return new(proto.DailyTaskDataNotify) })
	c.regMsg(DailyTaskProgressNotify, func() any { return new(proto.DailyTaskProgressNotify) })
	c.regMsg(DailyTaskScoreRewardNotify, func() any { return new(proto.DailyTaskScoreRewardNotify) })
	c.regMsg(WorldOwnerDailyTaskNotify, func() any { return new(proto.WorldOwnerDailyTaskNotify) })
	c.regMsg(AddRandTaskInfoNotify, func() any { return new(proto.AddRandTaskInfoNotify) })
	c.regMsg(RemoveRandTaskInfoNotify, func() any { return new(proto.RemoveRandTaskInfoNotify) })
	c.regMsg(TakePlayerLevelRewardReq, func() any { return new(proto.TakePlayerLevelRewardReq) })
	c.regMsg(TakePlayerLevelRewardRsp, func() any { return new(proto.TakePlayerLevelRewardRsp) })
	c.regMsg(PlayerLevelRewardUpdateNotify, func() any { return new(proto.PlayerLevelRewardUpdateNotify) })
	c.regMsg(GivingRecordNotify, func() any { return new(proto.GivingRecordNotify) })
	c.regMsg(GivingRecordChangeNotify, func() any { return new(proto.GivingRecordChangeNotify) })
	c.regMsg(ItemGivingReq, func() any { return new(proto.ItemGivingReq) })
	c.regMsg(ItemGivingRsp, func() any { return new(proto.ItemGivingRsp) })
	c.regMsg(PlayerCookArgsReq, func() any { return new(proto.PlayerCookArgsReq) })
	c.regMsg(PlayerCookArgsRsp, func() any { return new(proto.PlayerCookArgsRsp) })
	c.regMsg(PlayerLuaShellNotify, func() any { return new(proto.PlayerLuaShellNotify) })
	c.regMsg(ServerDisconnectClientNotify, func() any { return new(proto.ServerDisconnectClientNotify) })
	c.regMsg(AntiAddictNotify, func() any { return new(proto.AntiAddictNotify) })
	c.regMsg(PlayerForceExitReq, func() any { return new(proto.PlayerForceExitReq) })
	c.regMsg(PlayerForceExitRsp, func() any { return new(proto.PlayerForceExitRsp) })
	c.regMsg(PlayerInjectFixNotify, func() any { return new(proto.PlayerInjectFixNotify) })
	c.regMsg(TaskVarNotify, func() any { return new(proto.TaskVarNotify) })
	c.regMsg(ClientLockGameTimeNotify, func() any { return new(proto.ClientLockGameTimeNotify) })
	c.regMsg(EntityPropNotify, func() any { return new(proto.EntityPropNotify) })
	c.regMsg(LifeStateChangeNotify, func() any { return new(proto.LifeStateChangeNotify) })
	c.regMsg(EntityFightPropNotify, func() any { return new(proto.EntityFightPropNotify) })
	c.regMsg(EntityFightPropUpdateNotify, func() any { return new(proto.EntityFightPropUpdateNotify) })
	c.regMsg(AvatarFightPropNotify, func() any { return new(proto.AvatarFightPropNotify) })
	c.regMsg(AvatarFightPropUpdateNotify, func() any { return new(proto.AvatarFightPropUpdateNotify) })
	c.regMsg(EntityFightPropChangeReasonNotify, func() any { return new(proto.EntityFightPropChangeReasonNotify) })
	c.regMsg(AvatarLifeStateChangeNotify, func() any { return new(proto.AvatarLifeStateChangeNotify) })
	c.regMsg(AvatarPropChangeReasonNotify, func() any { return new(proto.AvatarPropChangeReasonNotify) })
	c.regMsg(PlayerPropChangeReasonNotify, func() any { return new(proto.PlayerPropChangeReasonNotify) })
	c.regMsg(AvatarPropNotify, func() any { return new(proto.AvatarPropNotify) })
	c.regMsg(MarkNewNotify, func() any { return new(proto.MarkNewNotify) })
	c.regMsg(QuestListNotify, func() any { return new(proto.QuestListNotify) })
	c.regMsg(QuestListUpdateNotify, func() any { return new(proto.QuestListUpdateNotify) })
	c.regMsg(QuestDelNotify, func() any { return new(proto.QuestDelNotify) })
	c.regMsg(FinishedParentQuestNotify, func() any { return new(proto.FinishedParentQuestNotify) })
	c.regMsg(FinishedParentQuestUpdateNotify, func() any { return new(proto.FinishedParentQuestUpdateNotify) })
	c.regMsg(AddQuestContentProgressReq, func() any { return new(proto.AddQuestContentProgressReq) })
	c.regMsg(AddQuestContentProgressRsp, func() any { return new(proto.AddQuestContentProgressRsp) })
	c.regMsg(GetQuestTalkHistoryReq, func() any { return new(proto.GetQuestTalkHistoryReq) })
	c.regMsg(GetQuestTalkHistoryRsp, func() any { return new(proto.GetQuestTalkHistoryRsp) })
	c.regMsg(QuestCreateEntityReq, func() any { return new(proto.QuestCreateEntityReq) })
	c.regMsg(QuestCreateEntityRsp, func() any { return new(proto.QuestCreateEntityRsp) })
	c.regMsg(QuestDestroyEntityReq, func() any { return new(proto.QuestDestroyEntityReq) })
	c.regMsg(QuestDestroyEntityRsp, func() any { return new(proto.QuestDestroyEntityRsp) })
	c.regMsg(ChapterStateNotify, func() any { return new(proto.ChapterStateNotify) })
	c.regMsg(QuestProgressUpdateNotify, func() any { return new(proto.QuestProgressUpdateNotify) })
	c.regMsg(QuestUpdateQuestVarReq, func() any { return new(proto.QuestUpdateQuestVarReq) })
	c.regMsg(QuestUpdateQuestVarRsp, func() any { return new(proto.QuestUpdateQuestVarRsp) })
	c.regMsg(QuestUpdateQuestVarNotify, func() any { return new(proto.QuestUpdateQuestVarNotify) })
	c.regMsg(QuestDestroyNpcReq, func() any { return new(proto.QuestDestroyNpcReq) })
	c.regMsg(QuestDestroyNpcRsp, func() any { return new(proto.QuestDestroyNpcRsp) })
	c.regMsg(BargainStartNotify, func() any { return new(proto.BargainStartNotify) })
	c.regMsg(BargainOfferPriceReq, func() any { return new(proto.BargainOfferPriceReq) })
	c.regMsg(BargainOfferPriceRsp, func() any { return new(proto.BargainOfferPriceRsp) })
	c.regMsg(BargainTerminateNotify, func() any { return new(proto.BargainTerminateNotify) })
	c.regMsg(GetBargainDataReq, func() any { return new(proto.GetBargainDataReq) })
	c.regMsg(GetBargainDataRsp, func() any { return new(proto.GetBargainDataRsp) })
	c.regMsg(GetAllActivatedBargainDataReq, func() any { return new(proto.GetAllActivatedBargainDataReq) })
	c.regMsg(GetAllActivatedBargainDataRsp, func() any { return new(proto.GetAllActivatedBargainDataRsp) })
	c.regMsg(ServerCondMeetQuestListUpdateNotify, func() any { return new(proto.ServerCondMeetQuestListUpdateNotify) })
	c.regMsg(QuestGlobalVarNotify, func() any { return new(proto.QuestGlobalVarNotify) })
	c.regMsg(QuestTransmitReq, func() any { return new(proto.QuestTransmitReq) })
	c.regMsg(QuestTransmitRsp, func() any { return new(proto.QuestTransmitRsp) })
	c.regMsg(PersonalLineAllDataReq, func() any { return new(proto.PersonalLineAllDataReq) })
	c.regMsg(PersonalLineAllDataRsp, func() any { return new(proto.PersonalLineAllDataRsp) })
	c.regMsg(RedeemLegendaryKeyReq, func() any { return new(proto.RedeemLegendaryKeyReq) })
	c.regMsg(RedeemLegendaryKeyRsp, func() any { return new(proto.RedeemLegendaryKeyRsp) })
	c.regMsg(UnlockPersonalLineReq, func() any { return new(proto.UnlockPersonalLineReq) })
	c.regMsg(UnlockPersonalLineRsp, func() any { return new(proto.UnlockPersonalLineRsp) })
	c.regMsg(RechargeReq, func() any { return new(proto.RechargeReq) })
	c.regMsg(RechargeRsp, func() any { return new(proto.RechargeRsp) })
	c.regMsg(OrderFinishNotify, func() any { return new(proto.OrderFinishNotify) })
	c.regMsg(CardProductRewardNotify, func() any { return new(proto.CardProductRewardNotify) })
	c.regMsg(PlayerRechargeDataNotify, func() any { return new(proto.PlayerRechargeDataNotify) })
	c.regMsg(OrderDisplayNotify, func() any { return new(proto.OrderDisplayNotify) })
	c.regMsg(PlayerEnterSceneNotify, func() any { return new(proto.PlayerEnterSceneNotify) })
	c.regMsg(LeaveSceneReq, func() any { return new(proto.LeaveSceneReq) })
	c.regMsg(LeaveSceneRsp, func() any { return new(proto.LeaveSceneRsp) })
	c.regMsg(SceneInitFinishReq, func() any { return new(proto.SceneInitFinishReq) })
	c.regMsg(SceneInitFinishRsp, func() any { return new(proto.SceneInitFinishRsp) })
	c.regMsg(SceneEntityAppearNotify, func() any { return new(proto.SceneEntityAppearNotify) })
	c.regMsg(SceneEntityDisappearNotify, func() any { return new(proto.SceneEntityDisappearNotify) })
	c.regMsg(SceneEntityMoveReq, func() any { return new(proto.SceneEntityMoveReq) })
	c.regMsg(SceneEntityMoveRsp, func() any { return new(proto.SceneEntityMoveRsp) })
	c.regMsg(SceneAvatarStaminaStepReq, func() any { return new(proto.SceneAvatarStaminaStepReq) })
	c.regMsg(SceneAvatarStaminaStepRsp, func() any { return new(proto.SceneAvatarStaminaStepRsp) })
	c.regMsg(SceneEntityMoveNotify, func() any { return new(proto.SceneEntityMoveNotify) })
	c.regMsg(ScenePlayerLocationNotify, func() any { return new(proto.ScenePlayerLocationNotify) })
	c.regMsg(GetScenePointReq, func() any { return new(proto.GetScenePointReq) })
	c.regMsg(GetScenePointRsp, func() any { return new(proto.GetScenePointRsp) })
	c.regMsg(EnterTransPointRegionNotify, func() any { return new(proto.EnterTransPointRegionNotify) })
	c.regMsg(ExitTransPointRegionNotify, func() any { return new(proto.ExitTransPointRegionNotify) })
	c.regMsg(ScenePointUnlockNotify, func() any { return new(proto.ScenePointUnlockNotify) })
	c.regMsg(SceneTransToPointReq, func() any { return new(proto.SceneTransToPointReq) })
	c.regMsg(SceneTransToPointRsp, func() any { return new(proto.SceneTransToPointRsp) })
	c.regMsg(EntityJumpNotify, func() any { return new(proto.EntityJumpNotify) })
	c.regMsg(GetSceneAreaReq, func() any { return new(proto.GetSceneAreaReq) })
	c.regMsg(GetSceneAreaRsp, func() any { return new(proto.GetSceneAreaRsp) })
	c.regMsg(SceneAreaUnlockNotify, func() any { return new(proto.SceneAreaUnlockNotify) })
	c.regMsg(SceneEntityDrownReq, func() any { return new(proto.SceneEntityDrownReq) })
	c.regMsg(SceneEntityDrownRsp, func() any { return new(proto.SceneEntityDrownRsp) })
	c.regMsg(SceneCreateEntityReq, func() any { return new(proto.SceneCreateEntityReq) })
	c.regMsg(SceneCreateEntityRsp, func() any { return new(proto.SceneCreateEntityRsp) })
	c.regMsg(SceneDestroyEntityReq, func() any { return new(proto.SceneDestroyEntityReq) })
	c.regMsg(SceneDestroyEntityRsp, func() any { return new(proto.SceneDestroyEntityRsp) })
	c.regMsg(SceneForceUnlockNotify, func() any { return new(proto.SceneForceUnlockNotify) })
	c.regMsg(SceneForceLockNotify, func() any { return new(proto.SceneForceLockNotify) })
	c.regMsg(EnterWorldAreaReq, func() any { return new(proto.EnterWorldAreaReq) })
	c.regMsg(EnterWorldAreaRsp, func() any { return new(proto.EnterWorldAreaRsp) })
	c.regMsg(EntityForceSyncReq, func() any { return new(proto.EntityForceSyncReq) })
	c.regMsg(EntityForceSyncRsp, func() any { return new(proto.EntityForceSyncRsp) })
	c.regMsg(SceneAreaExploreNotify, func() any { return new(proto.SceneAreaExploreNotify) })
	c.regMsg(SceneGetAreaExplorePercentReq, func() any { return new(proto.SceneGetAreaExplorePercentReq) })
	c.regMsg(SceneGetAreaExplorePercentRsp, func() any { return new(proto.SceneGetAreaExplorePercentRsp) })
	c.regMsg(ClientTransmitReq, func() any { return new(proto.ClientTransmitReq) })
	c.regMsg(ClientTransmitRsp, func() any { return new(proto.ClientTransmitRsp) })
	c.regMsg(EnterSceneWeatherAreaNotify, func() any { return new(proto.EnterSceneWeatherAreaNotify) })
	c.regMsg(ExitSceneWeatherAreaNotify, func() any { return new(proto.ExitSceneWeatherAreaNotify) })
	c.regMsg(SceneAreaWeatherNotify, func() any { return new(proto.SceneAreaWeatherNotify) })
	c.regMsg(ScenePlayerInfoNotify, func() any { return new(proto.ScenePlayerInfoNotify) })
	c.regMsg(WorldPlayerLocationNotify, func() any { return new(proto.WorldPlayerLocationNotify) })
	c.regMsg(BeginCameraSceneLookNotify, func() any { return new(proto.BeginCameraSceneLookNotify) })
	c.regMsg(EndCameraSceneLookNotify, func() any { return new(proto.EndCameraSceneLookNotify) })
	c.regMsg(MarkEntityInMinMapNotify, func() any { return new(proto.MarkEntityInMinMapNotify) })
	c.regMsg(UnmarkEntityInMinMapNotify, func() any { return new(proto.UnmarkEntityInMinMapNotify) })
	c.regMsg(DropSubfieldReq, func() any { return new(proto.DropSubfieldReq) })
	c.regMsg(DropSubfieldRsp, func() any { return new(proto.DropSubfieldRsp) })
	c.regMsg(ExecuteGroupTriggerReq, func() any { return new(proto.ExecuteGroupTriggerReq) })
	c.regMsg(ExecuteGroupTriggerRsp, func() any { return new(proto.ExecuteGroupTriggerRsp) })
	c.regMsg(LevelupCityReq, func() any { return new(proto.LevelupCityReq) })
	c.regMsg(LevelupCityRsp, func() any { return new(proto.LevelupCityRsp) })
	c.regMsg(SceneRouteChangeNotify, func() any { return new(proto.SceneRouteChangeNotify) })
	c.regMsg(PlatformStartRouteNotify, func() any { return new(proto.PlatformStartRouteNotify) })
	c.regMsg(PlatformStopRouteNotify, func() any { return new(proto.PlatformStopRouteNotify) })
	c.regMsg(PlatformChangeRouteNotify, func() any { return new(proto.PlatformChangeRouteNotify) })
	c.regMsg(ScenePlayerSoundNotify, func() any { return new(proto.ScenePlayerSoundNotify) })
	c.regMsg(PersonalSceneJumpReq, func() any { return new(proto.PersonalSceneJumpReq) })
	c.regMsg(PersonalSceneJumpRsp, func() any { return new(proto.PersonalSceneJumpRsp) })
	c.regMsg(SealBattleBeginNotify, func() any { return new(proto.SealBattleBeginNotify) })
	c.regMsg(SealBattleEndNotify, func() any { return new(proto.SealBattleEndNotify) })
	c.regMsg(SealBattleProgressNotify, func() any { return new(proto.SealBattleProgressNotify) })
	c.regMsg(ClientPauseNotify, func() any { return new(proto.ClientPauseNotify) })
	c.regMsg(PlayerEnterSceneInfoNotify, func() any { return new(proto.PlayerEnterSceneInfoNotify) })
	c.regMsg(JoinPlayerSceneReq, func() any { return new(proto.JoinPlayerSceneReq) })
	c.regMsg(JoinPlayerSceneRsp, func() any { return new(proto.JoinPlayerSceneRsp) })
	c.regMsg(SceneKickPlayerReq, func() any { return new(proto.SceneKickPlayerReq) })
	c.regMsg(SceneKickPlayerRsp, func() any { return new(proto.SceneKickPlayerRsp) })
	c.regMsg(SceneKickPlayerNotify, func() any { return new(proto.SceneKickPlayerNotify) })
	c.regMsg(HitClientTrivialNotify, func() any { return new(proto.HitClientTrivialNotify) })
	c.regMsg(BackMyWorldReq, func() any { return new(proto.BackMyWorldReq) })
	c.regMsg(BackMyWorldRsp, func() any { return new(proto.BackMyWorldRsp) })
	c.regMsg(SeeMonsterReq, func() any { return new(proto.SeeMonsterReq) })
	c.regMsg(SeeMonsterRsp, func() any { return new(proto.SeeMonsterRsp) })
	c.regMsg(AddSeenMonsterNotify, func() any { return new(proto.AddSeenMonsterNotify) })
	c.regMsg(AllSeenMonsterNotify, func() any { return new(proto.AllSeenMonsterNotify) })
	c.regMsg(SceneTimeNotify, func() any { return new(proto.SceneTimeNotify) })
	c.regMsg(EnterSceneReadyReq, func() any { return new(proto.EnterSceneReadyReq) })
	c.regMsg(EnterSceneReadyRsp, func() any { return new(proto.EnterSceneReadyRsp) })
	c.regMsg(EnterScenePeerNotify, func() any { return new(proto.EnterScenePeerNotify) })
	c.regMsg(EnterSceneDoneReq, func() any { return new(proto.EnterSceneDoneReq) })
	c.regMsg(EnterSceneDoneRsp, func() any { return new(proto.EnterSceneDoneRsp) })
	c.regMsg(WorldPlayerDieNotify, func() any { return new(proto.WorldPlayerDieNotify) })
	c.regMsg(WorldPlayerReviveReq, func() any { return new(proto.WorldPlayerReviveReq) })
	c.regMsg(WorldPlayerReviveRsp, func() any { return new(proto.WorldPlayerReviveRsp) })
	c.regMsg(JoinPlayerFailNotify, func() any { return new(proto.JoinPlayerFailNotify) })
	c.regMsg(SetSceneWeatherAreaReq, func() any { return new(proto.SetSceneWeatherAreaReq) })
	c.regMsg(SetSceneWeatherAreaRsp, func() any { return new(proto.SetSceneWeatherAreaRsp) })
	c.regMsg(ExecuteGadgetLuaReq, func() any { return new(proto.ExecuteGadgetLuaReq) })
	c.regMsg(ExecuteGadgetLuaRsp, func() any { return new(proto.ExecuteGadgetLuaRsp) })
	c.regMsg(CutSceneBeginNotify, func() any { return new(proto.CutSceneBeginNotify) })
	c.regMsg(CutSceneFinishNotify, func() any { return new(proto.CutSceneFinishNotify) })
	c.regMsg(CutSceneEndNotify, func() any { return new(proto.CutSceneEndNotify) })
	c.regMsg(ClientScriptEventNotify, func() any { return new(proto.ClientScriptEventNotify) })
	c.regMsg(SceneEntitiesMovesReq, func() any { return new(proto.SceneEntitiesMovesReq) })
	c.regMsg(SceneEntitiesMovesRsp, func() any { return new(proto.SceneEntitiesMovesRsp) })
	c.regMsg(SceneEntitiesMoveCombineNotify, func() any { return new(proto.SceneEntitiesMoveCombineNotify) })
	c.regMsg(UnlockTransPointReq, func() any { return new(proto.UnlockTransPointReq) })
	c.regMsg(UnlockTransPointRsp, func() any { return new(proto.UnlockTransPointRsp) })
	c.regMsg(PlatformRouteStateNotify, func() any { return new(proto.PlatformRouteStateNotify) })
	c.regMsg(SceneWeatherForcastReq, func() any { return new(proto.SceneWeatherForcastReq) })
	c.regMsg(SceneWeatherForcastRsp, func() any { return new(proto.SceneWeatherForcastRsp) })
	c.regMsg(MarkMapReq, func() any { return new(proto.MarkMapReq) })
	c.regMsg(MarkMapRsp, func() any { return new(proto.MarkMapRsp) })
	c.regMsg(AllMarkPointNotify, func() any { return new(proto.AllMarkPointNotify) })
	c.regMsg(WorldDataNotify, func() any { return new(proto.WorldDataNotify) })
	c.regMsg(EntityMoveRoomNotify, func() any { return new(proto.EntityMoveRoomNotify) })
	c.regMsg(WorldPlayerInfoNotify, func() any { return new(proto.WorldPlayerInfoNotify) })
	c.regMsg(PostEnterSceneReq, func() any { return new(proto.PostEnterSceneReq) })
	c.regMsg(PostEnterSceneRsp, func() any { return new(proto.PostEnterSceneRsp) })
	c.regMsg(PlayerChatReq, func() any { return new(proto.PlayerChatReq) })
	c.regMsg(PlayerChatRsp, func() any { return new(proto.PlayerChatRsp) })
	c.regMsg(PlayerChatNotify, func() any { return new(proto.PlayerChatNotify) })
	c.regMsg(PlayerChatCDNotify, func() any { return new(proto.PlayerChatCDNotify) })
	c.regMsg(ChatHistoryNotify, func() any { return new(proto.ChatHistoryNotify) })
	c.regMsg(SceneDataNotify, func() any { return new(proto.SceneDataNotify) })
	c.regMsg(DungeonEntryToBeExploreNotify, func() any { return new(proto.DungeonEntryToBeExploreNotify) })
	c.regMsg(GetDungeonEntryExploreConditionReq, func() any { return new(proto.GetDungeonEntryExploreConditionReq) })
	c.regMsg(GetDungeonEntryExploreConditionRsp, func() any { return new(proto.GetDungeonEntryExploreConditionRsp) })
	c.regMsg(UnfreezeGroupLimitNotify, func() any { return new(proto.UnfreezeGroupLimitNotify) })
	c.regMsg(SetEntityClientDataNotify, func() any { return new(proto.SetEntityClientDataNotify) })
	c.regMsg(GroupSuiteNotify, func() any { return new(proto.GroupSuiteNotify) })
	c.regMsg(GroupUnloadNotify, func() any { return new(proto.GroupUnloadNotify) })
	c.regMsg(MonsterAIConfigHashNotify, func() any { return new(proto.MonsterAIConfigHashNotify) })
	c.regMsg(EntityAbilityConfigHashNotify, func() any { return new(proto.EntityAbilityConfigHashNotify) })
	c.regMsg(ShowTemplateReminderNotify, func() any { return new(proto.ShowTemplateReminderNotify) })
	c.regMsg(ShowCommonTipsNotify, func() any { return new(proto.ShowCommonTipsNotify) })
	c.regMsg(CloseCommonTipsNotify, func() any { return new(proto.CloseCommonTipsNotify) })
}

func (c *CmdProtoMap) regMsg(cmdId uint16, protoObjNewFunc func() any) {
	_, exist := c.cmdDeDupMap[cmdId]
	if exist {
		logger.Error("reg dup msg, cmd id: %v\n", cmdId)
		return
	} else {
		c.cmdDeDupMap[cmdId] = true
	}
	protoObj := protoObjNewFunc().(pb.Message)
	refType := reflect.TypeOf(protoObj)
	// cmdId -> protoObj
	c.cmdIdProtoObjMap[cmdId] = refType
	// protoObj -> cmdId
	c.protoObjCmdIdMap[refType] = cmdId
	cmdName := refType.Elem().Name()
	// cmdId -> cmdName
	c.cmdIdCmdNameMap[cmdId] = cmdName
	// cmdName -> cmdId
	c.cmdNameCmdIdMap[cmdName] = cmdId
	// cmdId -> protoObjCache
	c.cmdIdProtoObjCacheMap[cmdId] = &sync.Pool{
		New: protoObjNewFunc,
	}
	// cmdId -> protoObjNewFunc
	c.cmdIdProtoObjFastNewMap[cmdId] = protoObjNewFunc
}

// 性能优化专用方法 若不满足使用条件 请老老实实的用下面的反射方法

// GetProtoObjCacheByCmdId 从缓存池获取一个对象 请务必确保能容忍获取到的对象含有使用过的脏数据 否则会产生不可预料的后果
func (c *CmdProtoMap) GetProtoObjCacheByCmdId(cmdId uint16) pb.Message {
	cachePool, exist := c.cmdIdProtoObjCacheMap[cmdId]
	if !exist {
		logger.Error("unknown cmd id: %v\n", cmdId)
		return nil
	}
	protoObj := cachePool.Get().(pb.Message)
	return protoObj
}

// PutProtoObjCache 将使用结束的对象放回缓存池 请务必确保对象的生命周期真的已经结束了 否则会产生不可预料的后果
func (c *CmdProtoMap) PutProtoObjCache(cmdId uint16, protoObj pb.Message) {
	cachePool, exist := c.cmdIdProtoObjCacheMap[cmdId]
	if !exist {
		logger.Error("unknown cmd id: %v\n", cmdId)
		return
	}
	cachePool.Put(protoObj)
}

func (c *CmdProtoMap) GetProtoObjFastNewByCmdId(cmdId uint16) pb.Message {
	fn, exist := c.cmdIdProtoObjFastNewMap[cmdId]
	if !exist {
		logger.Error("unknown cmd id: %v\n", cmdId)
		return nil
	}
	protoObj := fn().(pb.Message)
	return protoObj
}

// 反射方法

func (c *CmdProtoMap) GetProtoObjByCmdId(cmdId uint16) pb.Message {
	refType, exist := c.cmdIdProtoObjMap[cmdId]
	if !exist {
		logger.Error("unknown cmd id: %v\n", cmdId)
		return nil
	}
	protoObjInst := reflect.New(refType.Elem())
	protoObj := protoObjInst.Interface().(pb.Message)
	return protoObj
}

func (c *CmdProtoMap) GetCmdIdByProtoObj(protoObj pb.Message) uint16 {
	cmdId, exist := c.protoObjCmdIdMap[reflect.TypeOf(protoObj)]
	if !exist {
		logger.Error("unknown proto object: %v\n", protoObj)
		return 0
	}
	return cmdId
}

func (c *CmdProtoMap) GetCmdNameByCmdId(cmdId uint16) string {
	cmdName, exist := c.cmdIdCmdNameMap[cmdId]
	if !exist {
		logger.Error("unknown cmd id: %v\n", cmdId)
		return ""
	}
	return cmdName
}

func (c *CmdProtoMap) GetCmdIdByCmdName(cmdName string) uint16 {
	cmdId, exist := c.cmdNameCmdIdMap[cmdName]
	if !exist {
		logger.Error("unknown cmd name: %v\n", cmdName)
		return 0
	}
	return cmdId
}
